package mod.arcalitegames.odyssey.world.structure.structures.ruins.castle_ruins;

import java.util.Objects;

import mod.arcalitegames.odyssey.world.structure.StructureBase;
import mod.arcalitegames.system.parser.EntityParser;
import net.minecraft.block.Blocks;
import net.minecraft.entity.CreatureEntity;
import net.minecraft.util.Direction;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;

public class CastleRuins extends StructureBase
{

	public CastleRuins(World worldIn, BlockPos origin, int xRange, int yRange, int zRange)
	{
		super(worldIn, origin, xRange, yRange, zRange);
		CastleComponent0.init(world, origin, this);
		CastleComponent1.init(world, origin, this);
		CastleComponent2.init(world, origin, this);
		CastleComponent3.init(world, origin, this);
		CastleComponent4.init(world, origin, this);
		CastleComponent5.init(world, origin, this);
		CastleComponent6.init(world, origin, this);
		CastleComponent7.init(world, origin, this);
		CastleComponent8.init(world, origin, this);
		CastleComponent9.init(world, origin, this);
        this.fillWithBlocks(world, start, 14, 7, 10, 67, 40, 53, Blocks.AIR.getDefaultState());
        this.fillWithBlocks(world, start, 14, 7, 10, 93, 38, 29, Blocks.AIR.getDefaultState());
	}

	@Override
	public void addEntitiesAndSpawn()
	{
	    this.generateChest(world, Direction.EAST, -48, -25, 31, start, 1);
	    this.generateChest(world, Direction.SOUTH, -43, -25, 26, start, 1);
	    CreatureEntity dread_knight120 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight120, "dread_knight");
	    this.spawnEntity(dread_knight120, world, -43, -25, 29, start);
	    CreatureEntity dread_knight121 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight121, "dread_knight");
	    this.spawnEntity(dread_knight121, world, -43, -25, 33, start);
	    this.generateChest(world, Direction.NORTH, -43, -25, 36, start, 1);
	    this.generateChest(world, Direction.EAST, -30, -15, 31, start, 1);
	    this.generateChest(world, Direction.EAST, -27, -44, 1, start, 3);
	    this.generateChest(world, Direction.EAST, -27, -25, 1, start, 2);
	    this.generateChest(world, Direction.EAST, -26, -25, 81, start, 2);
	    this.generateChest(world, Direction.SOUTH, -25, -15, 26, start, 1);
	    this.generateChest(world, Direction.NORTH, -25, -15, 36, start, 1);
	    this.generateChest(world, Direction.EAST, -25, -14, 31, start, 2);
	    CreatureEntity dread_knight122 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight122, "dread_knight");
	    this.spawnEntity(dread_knight122, world, -23, -35, -39, start);
	    CreatureEntity dread_knight123 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight123, "dread_knight");
	    this.spawnEntity(dread_knight123, world, -23, -35, -27, start);
	    this.generateChest(world, Direction.SOUTH, -22, -25, -4, start, 1);
	    CreatureEntity dread_lich124 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich124, "dread_lich");
	    this.spawnEntity(dread_lich124, world, -22, -25, 1, start);
	    this.generateChest(world, Direction.NORTH, -22, -25, 6, start, 1);
	    CreatureEntity dread_thrall125 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall125, "dread_thrall");
	    this.spawnEntity(dread_thrall125, world, -21, -25, 63, start);
	    this.generateChest(world, Direction.NORTH, -21, -25, 86, start, 2);
	    CreatureEntity dread_knight126 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight126, "dread_knight");
	    this.spawnEntity(dread_knight126, world, -19, -55, -3, start);
	    CreatureEntity dread_lich127 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich127, "dread_lich");
	    this.spawnEntity(dread_lich127, world, -17, -45, -5, start);
	    CreatureEntity dread_lich128 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich128, "dread_lich");
	    this.spawnEntity(dread_lich128, world, -17, -35, -33, start);
	    CreatureEntity dread_beast129 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_beast")).create(world);
	    this.setItemsForEntity(dread_beast129, "dread_beast");
	    this.spawnEntity(dread_beast129, world, -17, -35, 18, start);
	    this.generateChest(world, Direction.WEST, -16, -25, 81, start, 2);
	    this.generateChest(world, Direction.SOUTH, -13, -55, -9, start, 2);
	    this.generateChest(world, Direction.NORTH, -13, -55, 3, start, 2);
	    CreatureEntity dread_lich130 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich130, "dread_lich");
	    this.spawnEntity(dread_lich130, world, -13, -45, 13, start);
	    CreatureEntity dread_knight131 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight131, "dread_knight");
	    this.spawnEntity(dread_knight131, world, -11, -35, -39, start);
	    CreatureEntity dread_knight132 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight132, "dread_knight");
	    this.spawnEntity(dread_knight132, world, -11, -35, -27, start);
	    CreatureEntity dread_thrall133 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall133, "dread_thrall");
	    this.spawnEntity(dread_thrall133, world, -6, -35, -10, start);
	    this.generateChest(world, Direction.EAST, -6, -25, -26, start, 1);
	    CreatureEntity dread_thrall134 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall134, "dread_thrall");
	    this.spawnEntity(dread_thrall134, world, -6, -15, 24, start);
	    CreatureEntity dread_lich135 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich135, "dread_lich");
	    this.spawnEntity(dread_lich135, world, -6, -15, 31, start);
	    CreatureEntity dread_thrall136 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall136, "dread_thrall");
	    this.spawnEntity(dread_thrall136, world, -6, -15, 38, start);
	    CreatureEntity dread_knight137 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight137, "dread_knight");
	    this.spawnEntity(dread_knight137, world, -5, -45, -5, start);
	    CreatureEntity dread_knight138 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight138, "dread_knight");
	    this.spawnEntity(dread_knight138, world, -5, -45, 7, start);
	    CreatureEntity dread_lich139 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich139, "dread_lich");
	    this.spawnEntity(dread_lich139, world, -1, -35, 18, start);
	    this.generateChest(world, Direction.SOUTH, -1, -25, -31, start, 2);
	    CreatureEntity dread_lich140 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich140, "dread_lich");
	    this.spawnEntity(dread_lich140, world, -1, -25, -26, start);
	    CreatureEntity dread_lich141 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich141, "dread_lich");
	    this.spawnEntity(dread_lich141, world, -1, -25, 1, start);
	    CreatureEntity dread_lich142 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich142, "dread_lich");
	    this.spawnEntity(dread_lich142, world, -1, -25, 31, start);
	    CreatureEntity dread_beast143 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_beast")).create(world);
	    this.setItemsForEntity(dread_beast143, "dread_beast");
	    this.spawnEntity(dread_beast143, world, -1, -25, 63, start);
	    CreatureEntity dread_knight144 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight144, "dread_knight");
	    this.spawnEntity(dread_knight144, world, 0, -35, -16, start);
	    CreatureEntity dread_ghoul145 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul145, "dread_ghoul");
	    this.spawnEntity(dread_ghoul145, world, 0, -35, 1, start);
	    this.generateChest(world, Direction.WEST, 0, -34, -33, start, 3);
	    this.generateChest(world, Direction.EAST, 3, -55, -29, start, 2);
	    this.generateChest(world, Direction.WEST, 4, -25, -26, start, 1);
	    CreatureEntity dread_thrall146 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall146, "dread_thrall");
	    this.spawnEntity(dread_thrall146, world, 6, -35, -22, start);
	    CreatureEntity dread_lich147 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich147, "dread_lich");
	    this.spawnEntity(dread_lich147, world, 6, -35, -16, start);
	    CreatureEntity dread_ghoul148 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul148, "dread_ghoul");
	    this.spawnEntity(dread_ghoul148, world, 6, -35, -10, start);
	    CreatureEntity dread_knight149 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight149, "dread_knight");
	    this.spawnEntity(dread_knight149, world, 7, -45, 27, start);
	    CreatureEntity dread_thrall150 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall150, "dread_thrall");
	    this.spawnEntity(dread_thrall150, world, 7, -45, 28, start);
	    CreatureEntity dread_knight151 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight151, "dread_knight");
	    this.spawnEntity(dread_knight151, world, 7, -45, 29, start);
	    this.generateChest(world, Direction.EAST, 10, -58, 36, start, 3);
	    CreatureEntity dread_lich152 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich152, "dread_lich");
	    this.spawnEntity(dread_lich152, world, 10, -57, 36, start);
	    this.generateChest(world, Direction.EAST, 10, -35, 18, start, 1);
	    this.generateChest(world, Direction.EAST, 10, -25, 91, start, 1);
	    this.generateChest(world, Direction.EAST, 10, -15, 1, start, 1);
	    this.generateChest(world, Direction.EAST, 10, -14, 62, start, 1);
	    this.generateChest(world, Direction.EAST, 11, -45, -9, start, 1);
	    CreatureEntity dread_thrall153 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall153, "dread_thrall");
	    this.spawnEntity(dread_thrall153, world, 11, -45, 7, start);
	    this.generateChest(world, Direction.EAST, 12, -44, -29, start, 1);
	    CreatureEntity dread_knight154 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight154, "dread_knight");
	    this.spawnEntity(dread_knight154, world, 14, -15, 76, start);
	    this.generateChest(world, Direction.NORTH, 14, -14, 83, start, 2);
	    CreatureEntity dread_ghoul155 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul155, "dread_ghoul");
	    this.spawnEntity(dread_ghoul155, world, 15, -25, 39, start);
	    CreatureEntity dread_ghoul156 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul156, "dread_ghoul");
	    this.spawnEntity(dread_ghoul156, world, 15, -25, 61, start);
	    CreatureEntity dread_lich157 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich157, "dread_lich");
	    this.spawnEntity(dread_lich157, world, 15, -25, 91, start);
	    this.generateChest(world, Direction.NORTH, 15, -25, 96, start, 2);
	    this.generateChest(world, Direction.SOUTH, 15, -15, -4, start, 1);
	    CreatureEntity dread_knight158 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight158, "dread_knight");
	    this.spawnEntity(dread_knight158, world, 15, -15, 1, start);
	    CreatureEntity dread_knight159 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight159, "dread_knight");
	    this.spawnEntity(dread_knight159, world, 16, -45, 40, start);
	    CreatureEntity dread_lich160 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich160, "dread_lich");
	    this.spawnEntity(dread_lich160, world, 17, -45, -9, start);
	    CreatureEntity dread_thrall161 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall161, "dread_thrall");
	    this.spawnEntity(dread_thrall161, world, 17, -45, 40, start);
	    this.generateChest(world, Direction.SOUTH, 17, -44, -15, start, 2);
	    CreatureEntity dread_beast162 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_beast")).create(world);
	    this.setItemsForEntity(dread_beast162, "dread_beast");
	    this.spawnEntity(dread_beast162, world, 17, -35, -30, start);
	    CreatureEntity dread_lich163 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich163, "dread_lich");
	    this.spawnEntity(dread_lich163, world, 17, -35, 18, start);
	    this.generateChest(world, Direction.NORTH, 17, -35, 25, start, 1);
	    CreatureEntity dread_lich164 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich164, "dread_lich");
	    this.spawnEntity(dread_lich164, world, 18, -55, -34, start);
	    CreatureEntity dread_beast165 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_beast")).create(world);
	    this.setItemsForEntity(dread_beast165, "dread_beast");
	    this.spawnEntity(dread_beast165, world, 18, -55, -3, start);
	    CreatureEntity dread_knight166 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight166, "dread_knight");
	    this.spawnEntity(dread_knight166, world, 18, -45, 40, start);
	    CreatureEntity dread_knight167 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight167, "dread_knight");
	    this.spawnEntity(dread_knight167, world, 20, -45, -29, start);
	    this.generateChest(world, Direction.WEST, 20, -25, 91, start, 1);
	    this.generateChest(world, Direction.WEST, 20, -15, 1, start, 1);
	    this.generateChest(world, Direction.WEST, 23, -45, -9, start, 1);
	    CreatureEntity dread_knight168 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight168, "dread_knight");
	    this.spawnEntity(dread_knight168, world, 23, -45, 7, start);
	    CreatureEntity dread_knight169 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight169, "dread_knight");
	    this.spawnEntity(dread_knight169, world, 23, -45, 19, start);
	    CreatureEntity dread_knight170 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight170, "dread_knight");
	    this.spawnEntity(dread_knight170, world, 23, -45, 34, start);
	    CreatureEntity dread_knight171 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight171, "dread_knight");
	    this.spawnEntity(dread_knight171, world, 26, -25, 20, start);
	    this.generateChest(world, Direction.SOUTH, 26, -24, 15, start, 2);
	    this.generateChest(world, Direction.EAST, 26, -15, 82, start, 1);
	    CreatureEntity dread_thrall172 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall172, "dread_thrall");
	    this.spawnEntity(dread_thrall172, world, 27, -45, -49, start);
	    CreatureEntity dread_knight173 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight173, "dread_knight");
	    this.spawnEntity(dread_knight173, world, 28, -45, 29, start);
	    CreatureEntity dread_knight174 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight174, "dread_knight");
	    this.spawnEntity(dread_knight174, world, 28, -45, 41, start);
	    CreatureEntity dread_ghoul175 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul175, "dread_ghoul");
	    this.spawnEntity(dread_ghoul175, world, 28, -35, 12, start);
	    CreatureEntity dread_ghoul176 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul176, "dread_ghoul");
	    this.spawnEntity(dread_ghoul176, world, 28, -35, 24, start);
	    this.generateChest(world, Direction.EAST, 30, -44, -17, start, 1);
	    CreatureEntity dread_knight177 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight177, "dread_knight");
	    this.spawnEntity(dread_knight177, world, 30, -35, -37, start);
	    CreatureEntity dread_knight178 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight178, "dread_knight");
	    this.spawnEntity(dread_knight178, world, 30, -35, -29, start);
	    CreatureEntity dread_ghoul179 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul179, "dread_ghoul");
	    this.spawnEntity(dread_ghoul179, world, 31, -15, 62, start);
	    this.generateChest(world, Direction.NORTH, 31, -15, 87, start, 1);
	    CreatureEntity goblin_trow180 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_trow")).create(world);
	    this.setItemsForEntity(goblin_trow180, "goblin_trow");
	    this.spawnEntity(goblin_trow180, world, 31, 15, 31, start);
	    this.generateChest(world, Direction.EAST, 33, -25, -14, start, 1);
	    this.generateChest(world, Direction.EAST, 33, -25, 63, start, 1);
	    this.generateChest(world, Direction.EAST, 33, -25, 83, start, 1);
	    CreatureEntity dread_knight181 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight181, "dread_knight");
	    this.spawnEntity(dread_knight181, world, 34, -45, -5, start);
	    CreatureEntity dread_lich182 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich182, "dread_lich");
	    this.spawnEntity(dread_lich182, world, 34, -45, 53, start);
	    this.generateChest(world, Direction.SOUTH, 34, -44, -55, start, 2);
	    this.generateChest(world, Direction.SOUTH, 34, -34, -33, start, 3);
	    this.generateChest(world, Direction.WEST, 34, -34, 18, start, 2);
	    this.generateChest(world, Direction.WEST, 36, -15, 82, start, 1);
	    CreatureEntity goblin_kobold183 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_kobold")).create(world);
	    this.setItemsForEntity(goblin_kobold183, "goblin_kobold");
	    this.spawnEntity(goblin_kobold183, world, 36, 13, 46, start);
	    CreatureEntity dread_knight184 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight184, "dread_knight");
	    this.spawnEntity(dread_knight184, world, 38, -35, -37, start);
	    CreatureEntity dread_knight185 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight185, "dread_knight");
	    this.spawnEntity(dread_knight185, world, 38, -35, -29, start);
	    this.generateChest(world, Direction.SOUTH, 38, -25, -19, start, 1);
	    CreatureEntity dread_knight186 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight186, "dread_knight");
	    this.spawnEntity(dread_knight186, world, 38, -25, -14, start);
	    CreatureEntity dread_beast187 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_beast")).create(world);
	    this.setItemsForEntity(dread_beast187, "dread_beast");
	    this.spawnEntity(dread_beast187, world, 38, -25, 31, start);
	    CreatureEntity dread_ghoul188 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul188, "dread_ghoul");
	    this.spawnEntity(dread_ghoul188, world, 38, -25, 63, start);
	    CreatureEntity dread_thrall189 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall189, "dread_thrall");
	    this.spawnEntity(dread_thrall189, world, 38, -25, 83, start);
	    this.generateChest(world, Direction.NORTH, 38, -25, 88, start, 1);
	    CreatureEntity goblin_kobold190 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_kobold")).create(world);
	    this.setItemsForEntity(goblin_kobold190, "goblin_kobold");
	    this.spawnEntity(goblin_kobold190, world, 38, 19, 38, start);
	    CreatureEntity hobgoblin191 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_hobgoblin")).create(world);
	    this.setItemsForEntity(hobgoblin191, "hobgoblin");
	    this.spawnEntity(hobgoblin191, world, 38, 20, 31, start);
	    CreatureEntity dread_thrall192 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall192, "dread_thrall");
	    this.spawnEntity(dread_thrall192, world, 40, -45, 29, start);
	    CreatureEntity dread_knight193 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight193, "dread_knight");
	    this.spawnEntity(dread_knight193, world, 40, -45, 41, start);
	    this.generateChest(world, Direction.WEST, 40, 14, 45, start, 2);
	    CreatureEntity goblin_kobold194 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_kobold")).create(world);
	    this.setItemsForEntity(goblin_kobold194, "goblin_kobold");
	    this.spawnEntity(goblin_kobold194, world, 40, 19, 23, start);
	    CreatureEntity dread_thrall195 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall195, "dread_thrall");
	    this.spawnEntity(dread_thrall195, world, 41, -45, -49, start);
	    CreatureEntity dread_thrall196 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall196, "dread_thrall");
	    this.spawnEntity(dread_thrall196, world, 41, -45, 7, start);
	    CreatureEntity dread_knight197 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight197, "dread_knight");
	    this.spawnEntity(dread_knight197, world, 41, -45, 19, start);
	    this.generateChest(world, Direction.WEST, 41, 22, 32, start, 1);
	    CreatureEntity hobgoblin198 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_hobgoblin")).create(world);
	    this.setItemsForEntity(hobgoblin198, "hobgoblin");
	    this.spawnEntity(hobgoblin198, world, 42, 11, 17, start);
	    CreatureEntity dread_knight199 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight199, "dread_knight");
	    this.spawnEntity(dread_knight199, world, 43, -58, 32, start);
	    CreatureEntity dread_knight200 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight200, "dread_knight");
	    this.spawnEntity(dread_knight200, world, 43, -58, 40, start);
	    this.generateChest(world, Direction.WEST, 43, -25, -14, start, 1);
	    this.generateChest(world, Direction.WEST, 43, -25, 83, start, 1);
	    this.generateChest(world, Direction.SOUTH, 44, -45, -33, start, 2);
	    this.generateChest(world, Direction.SOUTH, 47, -57, -63, start, 3);
	    CreatureEntity dread_beast201 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_beast")).create(world);
	    this.setItemsForEntity(dread_beast201, "dread_beast");
	    this.spawnEntity(dread_beast201, world, 47, -56, -63, start);
	    CreatureEntity dread_thrall202 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall202, "dread_thrall");
	    this.spawnEntity(dread_thrall202, world, 47, -55, -29, start);
	    CreatureEntity dread_ghoul203 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul203, "dread_ghoul");
	    this.spawnEntity(dread_ghoul203, world, 47, -55, -11, start);
	    CreatureEntity dread_ghoul204 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul204, "dread_ghoul");
	    this.spawnEntity(dread_ghoul204, world, 47, -55, 5, start);
	    CreatureEntity dread_thrall206 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall206, "dread_thrall");
	    this.spawnEntity(dread_thrall206, world, 47, -55, 58, start);
	    this.generateChest(world, Direction.NORTH, 47, -55, 64, start, 3);
	    CreatureEntity dread_knight207 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight207, "dread_knight");
	    this.spawnEntity(dread_knight207, world, 47, -45, 42, start);
	    this.generateChest(world, Direction.NORTH, 47, -44, 43, start, 2);
	    CreatureEntity dread_knight208 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight208, "dread_knight");
	    this.spawnEntity(dread_knight208, world, 51, -58, 32, start);
	    CreatureEntity dread_knight209 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight209, "dread_knight");
	    this.spawnEntity(dread_knight209, world, 51, -58, 40, start);
	    CreatureEntity dread_knight210 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight210, "dread_knight");
	    this.spawnEntity(dread_knight210, world, 53, -45, 7, start);
	    CreatureEntity dread_thrall211 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall211, "dread_thrall");
	    this.spawnEntity(dread_thrall211, world, 53, -45, 19, start);
	    CreatureEntity goblin_kobold212 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_kobold")).create(world);
	    this.setItemsForEntity(goblin_kobold212, "goblin_kobold");
	    this.spawnEntity(goblin_kobold212, world, 53, 13, 25, start);
	    CreatureEntity goblin_kobold213 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_kobold")).create(world);
	    this.setItemsForEntity(goblin_kobold213, "goblin_kobold");
	    this.spawnEntity(goblin_kobold213, world, 53, 13, 35, start);
	    CreatureEntity dread_ghoul214 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul214, "dread_ghoul");
	    this.spawnEntity(dread_ghoul214, world, 56, -15, 31, start);
	    CreatureEntity dread_knight215 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight215, "dread_knight");
	    this.spawnEntity(dread_knight215, world, 60, -45, 34, start);
	    CreatureEntity dread_thrall216 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall216, "dread_thrall");
	    this.spawnEntity(dread_thrall216, world, 60, -45, 35, start);
	    CreatureEntity dread_knight217 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight217, "dread_knight");
	    this.spawnEntity(dread_knight217, world, 60, -45, 36, start);
	    CreatureEntity dread_beast218 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_beast")).create(world);
	    this.setItemsForEntity(dread_beast218, "dread_beast");
	    this.spawnEntity(dread_beast218, world, 63, -45, -29, start);
	    CreatureEntity dread_knight219 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight219, "dread_knight");
	    this.spawnEntity(dread_knight219, world, 63, -25, 13, start);
	    CreatureEntity dread_lich220 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich220, "dread_lich");
	    this.spawnEntity(dread_lich220, world, 63, -25, 31, start);
	    this.generateChest(world, Direction.SOUTH, 63, -24, 5, start, 2);
	    CreatureEntity hobgoblin221 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_hobgoblin")).create(world);
	    this.setItemsForEntity(hobgoblin221, "hobgoblin");
	    this.spawnEntity(hobgoblin221, world, 67, 11, 19, start);
	    this.generateChest(world, Direction.WEST, 69, -58, 36, start, 3);
	    CreatureEntity dread_beast222 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_beast")).create(world);
	    this.setItemsForEntity(dread_beast222, "dread_beast");
	    this.spawnEntity(dread_beast222, world, 69, -55, 57, start);
	    this.generateChest(world, Direction.SOUTH, 69, -25, 58, start, 1);
	    CreatureEntity dread_thrall223 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall223, "dread_thrall");
	    this.spawnEntity(dread_thrall223, world, 69, -25, 63, start);
	    this.generateChest(world, Direction.NORTH, 69, -25, 68, start, 1);
	    this.generateChest(world, Direction.WEST, 74, -25, 63, start, 1);
	    CreatureEntity goblin_knocker224 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_knocker")).create(world);
	    this.setItemsForEntity(goblin_knocker224, "goblin_knocker");
	    this.spawnEntity(goblin_knocker224, world, 74, 9, 20, start);
	    this.generateChest(world, Direction.SOUTH, 75, -45, 7, start, 2);
	    CreatureEntity dread_knight225 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight225, "dread_knight");
	    this.spawnEntity(dread_knight225, world, 75, -45, 12, start);
	    CreatureEntity dread_lich226 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich226, "dread_lich");
	    this.spawnEntity(dread_lich226, world, 75, -45, 13, start);
	    CreatureEntity dread_knight227 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight227, "dread_knight");
	    this.spawnEntity(dread_knight227, world, 75, -45, 14, start);
	    this.generateChest(world, Direction.NORTH, 75, -45, 19, start, 2);
	    CreatureEntity goblin_knocker228 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_knocker")).create(world);
	    this.setItemsForEntity(goblin_knocker228, "goblin_knocker");
	    this.spawnEntity(goblin_knocker228, world, 78, 9, 16, start);
	    CreatureEntity dread_ghoul229 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul229, "dread_ghoul");
	    this.spawnEntity(dread_ghoul229, world, 81, -55, -31, start);
	    CreatureEntity dread_ghoul230 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul230, "dread_ghoul");
	    this.spawnEntity(dread_ghoul230, world, 81, -55, -27, start);
	    this.generateChest(world, Direction.WEST, 81, -45, 13, start, 2);
	    CreatureEntity dread_knight231 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight231, "dread_knight");
	    this.spawnEntity(dread_knight231, world, 86, -25, 31, start);
	    this.generateChest(world, Direction.SOUTH, 89, -15, 26, start, 1);
	    CreatureEntity dread_thrall232 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall232, "dread_thrall");
	    this.spawnEntity(dread_thrall232, world, 89, -15, 29, start);
	    CreatureEntity dread_thrall233 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall233, "dread_thrall");
	    this.spawnEntity(dread_thrall233, world, 89, -15, 33, start);
	    this.generateChest(world, Direction.NORTH, 89, -15, 36, start, 1);
	    CreatureEntity goblin_knocker234 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_knocker")).create(world);
	    this.setItemsForEntity(goblin_knocker234, "goblin_knocker");
	    this.spawnEntity(goblin_knocker234, world, 91, 8, 17, start);
	    this.generateChest(world, Direction.WEST, 92, -24, 31, start, 2);
	    this.generateChest(world, Direction.WEST, 94, -15, 31, start, 1);
	    CreatureEntity dread_lich235 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich235, "dread_lich");
	    this.spawnEntity(dread_lich235, world, 99, -55, -29, start);
	    this.executeCommand(world);
	}

}
