package mod.arcalitegames.odyssey.world.structure.structures.dungeons.masoleum;

import java.util.Objects;

import mod.arcalitegames.odyssey.world.structure.StructureBase;
import mod.arcalitegames.system.parser.EntityParser;
import net.minecraft.block.Blocks;
import net.minecraft.entity.CreatureEntity;
import net.minecraft.util.Direction;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;

public class DesertMasoleum extends StructureBase
{

	public DesertMasoleum(World worldIn, BlockPos origin, int xRange, int yRange, int zRange)
	{
		super(worldIn, origin, xRange, yRange, zRange);
		MasoleumComponent0.init(world, origin, this);
		MasoleumComponent1.init(world, origin, this);
		MasoleumComponent2.init(world, origin, this);
		MasoleumComponent3.init(world, origin, this);
		MasoleumComponent4.init(world, origin, this);
        this.fillWithBlocks(world, start, 28, 8, 20, 205, 77, 136, Blocks.AIR.getDefaultState());
	}

	@Override
	public void addEntitiesAndSpawn()
	{
	    this.generateChest(world, Direction.EAST, 29, -49, 28, start, 3);
	    this.generateChest(world, Direction.EAST, 32, -39, 28, start, 3);
	    CreatureEntity skeleton1 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton1, "skeleton");
	    this.spawnEntity(skeleton1, world, 34, -40, 28, start);
	    CreatureEntity skeleton2 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton2, "skeleton");
	    this.spawnEntity(skeleton2, world, 36, -40, 23, start);
	    CreatureEntity skeleton3 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton3, "skeleton");
	    this.spawnEntity(skeleton3, world, 36, -40, 33, start);
	    this.generateChest(world, Direction.EAST, 37, -28, 0, start, 1);
	    this.generateChest(world, Direction.EAST, 37, -28, 22, start, 1);
	    CreatureEntity skeleton4 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton4, "skeleton");
	    this.spawnEntity(skeleton4, world, 38, -29, 22, start);
	    CreatureEntity troll5 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:troll")).create(world);
	    this.setItemsForEntity(troll5, "troll");
	    this.spawnEntity(troll5, world, 39, -49, 28, start);
	    CreatureEntity skeleton6 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton6, "skeleton");
	    this.spawnEntity(skeleton6, world, 39, -29, 5, start);
	    this.generateChest(world, Direction.EAST, 40, -18, 28, start, 2);
	    CreatureEntity vindicator7 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator7, "vindicator");
	    this.spawnEntity(vindicator7, world, 40, 9, 107, start);
	    CreatureEntity skeleton8 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton8, "skeleton");
	    this.spawnEntity(skeleton8, world, 42, -40, 23, start);
	    CreatureEntity skeleton9 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton9, "skeleton");
	    this.spawnEntity(skeleton9, world, 42, -40, 33, start);
	    CreatureEntity zombie10 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie10, "zombie");
	    this.spawnEntity(zombie10, world, 45, -29, 17, start);
	    this.generateChest(world, Direction.NORTH, 45, -28, 28, start, 2);
	    this.generateChest(world, Direction.EAST, 45, -28, 45, start, 2);
	    CreatureEntity skeleton11 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton11, "skeleton");
	    this.spawnEntity(skeleton11, world, 45, -19, 28, start);
	    this.generateChest(world, Direction.EAST, 46, -39, 11, start, 1);
	    CreatureEntity skeleton12 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton12, "skeleton");
	    this.spawnEntity(skeleton12, world, 46, -39, 28, start);
	    CreatureEntity zombie13 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie13, "zombie");
	    this.spawnEntity(zombie13, world, 46, -29, -6, start);
	    CreatureEntity zombie14 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie14, "zombie");
	    this.spawnEntity(zombie14, world, 48, -29, -3, start);
	    CreatureEntity zombie15 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie15, "zombie");
	    this.spawnEntity(zombie15, world, 48, -29, 45, start);
	    CreatureEntity skeleton16 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton16, "skeleton");
	    this.spawnEntity(skeleton16, world, 49, -40, 42, start);
	    CreatureEntity skeleton17 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton17, "skeleton");
	    this.spawnEntity(skeleton17, world, 49, -40, 48, start);
	    CreatureEntity skeleton18 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton18, "skeleton");
	    this.spawnEntity(skeleton18, world, 51, -29, 5, start);
	    CreatureEntity zombie19 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie19, "zombie");
	    this.spawnEntity(zombie19, world, 51, -29, 11, start);
	    this.generateChest(world, Direction.SOUTH, 51, -28, -14, start, 1);
	    this.generateChest(world, Direction.SOUTH, 51, -28, 37, start, 1);
	    this.generateChest(world, Direction.NORTH, 51, -28, 53, start, 1);
	    CreatureEntity zombie20 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie20, "zombie");
	    this.spawnEntity(zombie20, world, 52, -39, 11, start);
	    CreatureEntity skeleton21 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton21, "skeleton");
	    this.spawnEntity(skeleton21, world, 53, -40, 49, start);
	    this.generateChest(world, Direction.SOUTH, 53, -39, 4, start, 1);
	    CreatureEntity zombie22 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie22, "zombie");
	    this.spawnEntity(zombie22, world, 53, -39, 10, start);
	    CreatureEntity zombie23 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie23, "zombie");
	    this.spawnEntity(zombie23, world, 53, -39, 11, start);
	    CreatureEntity zombie24 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie24, "zombie");
	    this.spawnEntity(zombie24, world, 53, -39, 12, start);
	    CreatureEntity skeleton25 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton25, "skeleton");
	    this.spawnEntity(skeleton25, world, 53, -39, 37, start);
	    this.generateChest(world, Direction.NORTH, 53, -39, 52, start, 3);
	    this.generateChest(world, Direction.WEST, 53, -28, 22, start, 1);
	    CreatureEntity zombie26 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie26, "zombie");
	    this.spawnEntity(zombie26, world, 54, -39, 11, start);
	    CreatureEntity skeleton27 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton27, "skeleton");
	    this.spawnEntity(skeleton27, world, 57, -40, 42, start);
	    CreatureEntity skeleton28 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton28, "skeleton");
	    this.spawnEntity(skeleton28, world, 57, -40, 48, start);
	    CreatureEntity zombie29 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie29, "zombie");
	    this.spawnEntity(zombie29, world, 58, -19, 26, start);
	    CreatureEntity zombie30 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie30, "zombie");
	    this.spawnEntity(zombie30, world, 58, -19, 30, start);
	    this.generateChest(world, Direction.EAST, 58, -18, 11, start, 1);
	    CreatureEntity pillager31 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager31, "pillager");
	    this.spawnEntity(pillager31, world, 58, 9, 130, start);
	    CreatureEntity skeleton32 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton32, "skeleton");
	    this.spawnEntity(skeleton32, world, 59, -19, 53, start);
	    this.generateChest(world, Direction.NORTH, 59, -18, 58, start, 1);
	    this.generateChest(world, Direction.WEST, 60, -39, 11, start, 1);
	    CreatureEntity skeleton33 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton33, "skeleton");
	    this.spawnEntity(skeleton33, world, 60, -29, 40, start);
	    CreatureEntity zombie34 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie34, "zombie");
	    this.spawnEntity(zombie34, world, 60, -19, 11, start);
	    CreatureEntity vindicator35 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator35, "vindicator");
	    this.spawnEntity(vindicator35, world, 60, 9, 45, start);
	    CreatureEntity pillager36 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager36, "pillager");
	    this.spawnEntity(pillager36, world, 60, 9, 70, start);
	    CreatureEntity husk37 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk37, "husk");
	    this.spawnEntity(husk37, world, 62, -29, 18, start);
	    CreatureEntity husk38 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk38, "husk");
	    this.spawnEntity(husk38, world, 62, -19, 26, start);
	    CreatureEntity husk39 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk39, "husk");
	    this.spawnEntity(husk39, world, 62, -19, 30, start);
	    CreatureEntity skeleton40 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton40, "skeleton");
	    this.spawnEntity(skeleton40, world, 63, -39, 28, start);
	    CreatureEntity skeleton41 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton41, "skeleton");
	    this.spawnEntity(skeleton41, world, 64, -29, 40, start);
	    this.generateChest(world, Direction.EAST, 70, -49, 62, start, 2);
	    CreatureEntity skeleton42 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton42, "skeleton");
	    this.spawnEntity(skeleton42, world, 72, -9, 26, start);
	    CreatureEntity skeleton43 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton43, "skeleton");
	    this.spawnEntity(skeleton43, world, 72, -9, 30, start);
	    this.generateChest(world, Direction.EAST, 72, -8, 28, start, 2);
	    CreatureEntity skeleton44 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton44, "skeleton");
	    this.spawnEntity(skeleton44, world, 73, -29, 38, start);
	    CreatureEntity skeleton45 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton45, "skeleton");
	    this.spawnEntity(skeleton45, world, 73, -29, 52, start);
	    this.generateChest(world, Direction.SOUTH, 73, -28, 37, start, 1);
	    this.generateChest(world, Direction.NORTH, 73, -28, 53, start, 1);
	    this.generateChest(world, Direction.EAST, 74, -38, 6, start, 1);
	    CreatureEntity zombie46 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie46, "zombie");
	    this.spawnEntity(zombie46, world, 74, -29, -6, start);
	    CreatureEntity zombie47 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie47, "zombie");
	    this.spawnEntity(zombie47, world, 75, -39, 6, start);
	    CreatureEntity vindicator48 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator48, "vindicator");
	    this.spawnEntity(vindicator48, world, 76, 9, 134, start);
	    CreatureEntity troll49 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:troll")).create(world);
	    this.setItemsForEntity(troll49, "troll");
	    this.spawnEntity(troll49, world, 77, -49, 28, start);
	    CreatureEntity troll50 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:troll")).create(world);
	    this.setItemsForEntity(troll50, "troll");
	    this.spawnEntity(troll50, world, 77, -49, 61, start);
	    this.generateChest(world, Direction.NORTH, 77, -49, 69, start, 2);
	    this.generateChest(world, Direction.SOUTH, 77, -48, 11, start, 3);
	    CreatureEntity pillager51 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager51, "pillager");
	    this.spawnEntity(pillager51, world, 78, 9, 41, start);
	    CreatureEntity skeleton52 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton52, "skeleton");
	    this.spawnEntity(skeleton52, world, 79, -29, -12, start);
	    CreatureEntity husk53 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk53, "husk");
	    this.spawnEntity(husk53, world, 79, -29, 11, start);
	    CreatureEntity skeleton54 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton54, "skeleton");
	    this.spawnEntity(skeleton54, world, 79, -19, 11, start);
	    CreatureEntity skeleton55 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton55, "skeleton");
	    this.spawnEntity(skeleton55, world, 79, -19, 63, start);
	    this.generateChest(world, Direction.NORTH, 79, -18, 65, start, 1);
	    CreatureEntity skeleton56 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton56, "skeleton");
	    this.spawnEntity(skeleton56, world, 82, -39, 72, start);
	    this.generateChest(world, Direction.SOUTH, 82, -38, 0, start, 2);
	    this.generateChest(world, Direction.NORTH, 82, -38, 73, start, 1);
	    this.generateChest(world, Direction.WEST, 84, -49, 62, start, 2);
	    CreatureEntity zombie57 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie57, "zombie");
	    this.spawnEntity(zombie57, world, 84, -29, -6, start);
	    CreatureEntity husk58 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk58, "husk");
	    this.spawnEntity(husk58, world, 85, -29, 40, start);
	    CreatureEntity husk59 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk59, "husk");
	    this.spawnEntity(husk59, world, 85, -29, 43, start);
	    CreatureEntity husk60 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk60, "husk");
	    this.spawnEntity(husk60, world, 85, -29, 47, start);
	    CreatureEntity husk61 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk61, "husk");
	    this.spawnEntity(husk61, world, 85, -29, 50, start);
	    this.generateChest(world, Direction.SOUTH, 85, -28, 37, start, 1);
	    this.generateChest(world, Direction.NORTH, 85, -28, 53, start, 1);
	    this.generateChest(world, Direction.EAST, 88, -49, 55, start, 2);
	    CreatureEntity zombie62 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie62, "zombie");
	    this.spawnEntity(zombie62, world, 88, -39, 44, start);
	    CreatureEntity zombie63 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie63, "zombie");
	    this.spawnEntity(zombie63, world, 88, -39, 55, start);
	    CreatureEntity zombie64 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie64, "zombie");
	    this.spawnEntity(zombie64, world, 89, -39, 6, start);
	    this.generateChest(world, Direction.WEST, 90, -38, 6, start, 1);
	    CreatureEntity husk65 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk65, "husk");
	    this.spawnEntity(husk65, world, 92, -9, 28, start);
	    CreatureEntity zombie66 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie66, "zombie");
	    this.spawnEntity(zombie66, world, 93, -39, 73, start);
	    this.generateChest(world, Direction.SOUTH, 95, -49, 48, start, 2);
	    CreatureEntity troll67 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:troll")).create(world);
	    this.setItemsForEntity(troll67, "troll");
	    this.spawnEntity(troll67, world, 95, -49, 55, start);
	    this.generateChest(world, Direction.NORTH, 95, -49, 62, start, 2);
	    CreatureEntity vindicator68 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator68, "vindicator");
	    this.spawnEntity(vindicator68, world, 95, 9, 94, start);
	    CreatureEntity skeleton69 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton69, "skeleton");
	    this.spawnEntity(skeleton69, world, 96, -39, 50, start);
	    this.generateChest(world, Direction.NORTH, 96, -38, 73, start, 2);
	    CreatureEntity zombie70 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie70, "zombie");
	    this.spawnEntity(zombie70, world, 96, -29, 12, start);
	    CreatureEntity zombie71 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie71, "zombie");
	    this.spawnEntity(zombie71, world, 96, -29, 23, start);
	    CreatureEntity skeleton72 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton72, "skeleton");
	    this.spawnEntity(skeleton72, world, 96, -29, 38, start);
	    CreatureEntity skeleton73 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton73, "skeleton");
	    this.spawnEntity(skeleton73, world, 96, -29, 52, start);
	    this.generateChest(world, Direction.WEST, 96, -28, -6, start, 1);
	    this.generateChest(world, Direction.WEST, 96, -28, 45, start, 3);
	    this.generateChest(world, Direction.EAST, 97, -49, 8, start, 1);
	    CreatureEntity zombie74 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie74, "zombie");
	    this.spawnEntity(zombie74, world, 99, -39, 73, start);
	    this.generateChest(world, Direction.EAST, 99, 10, 46, start, 1);
	    this.generateChest(world, Direction.EAST, 102, -49, -27, start, 2);
	    CreatureEntity skeleton75 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton75, "skeleton");
	    this.spawnEntity(skeleton75, world, 102, -49, -3, start);
	    CreatureEntity skeleton76 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton76, "skeleton");
	    this.spawnEntity(skeleton76, world, 102, -9, 121, start);
	    CreatureEntity vindicator77 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator77, "vindicator");
	    this.spawnEntity(vindicator77, world, 102, 9, 40, start);
	    CreatureEntity skeleton78 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton78, "skeleton");
	    this.spawnEntity(skeleton78, world, 103, -29, 45, start);
	    CreatureEntity vindicator79 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator79, "vindicator");
	    this.spawnEntity(vindicator79, world, 103, 9, 133, start);
	    CreatureEntity vindicator80 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator80, "vindicator");
	    this.spawnEntity(vindicator80, world, 103, 10, 48, start);
	    CreatureEntity skeleton81 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton81, "skeleton");
	    this.spawnEntity(skeleton81, world, 104, -40, -17, start);
	    CreatureEntity skeleton82 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton82, "skeleton");
	    this.spawnEntity(skeleton82, world, 104, -40, -11, start);
	    CreatureEntity skeleton83 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton83, "skeleton");
	    this.spawnEntity(skeleton83, world, 104, -19, 45, start);
	    CreatureEntity husk84 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk84, "husk");
	    this.spawnEntity(husk84, world, 104, -19, 75, start);
	    CreatureEntity husk85 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk85, "husk");
	    this.spawnEntity(husk85, world, 104, -19, 87, start);
	    CreatureEntity skeleton86 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton86, "skeleton");
	    this.spawnEntity(skeleton86, world, 104, -19, 99, start);
	    this.generateChest(world, Direction.NORTH, 104, -18, 101, start, 1);
	    CreatureEntity zombie87 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie87, "zombie");
	    this.spawnEntity(zombie87, world, 104, -9, 12, start);
	    CreatureEntity husk88 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk88, "husk");
	    this.spawnEntity(husk88, world, 104, -9, 33, start);
	    CreatureEntity husk89 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk89, "husk");
	    this.spawnEntity(husk89, world, 104, -9, 92, start);
	    this.generateChest(world, Direction.NORTH, 104, -8, 121, start, 2);
	    CreatureEntity vindicator90 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator90, "vindicator");
	    this.spawnEntity(vindicator90, world, 104, 10, 51, start);
	    CreatureEntity pillager91 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager91, "pillager");
	    this.spawnEntity(pillager91, world, 104, 12, 56, start);
	    CreatureEntity vindicator92 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator92, "vindicator");
	    this.spawnEntity(vindicator92, world, 105, 10, 48, start);
	    CreatureEntity zombie93 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie93, "zombie");
	    this.spawnEntity(zombie93, world, 106, -49, -6, start);
	    CreatureEntity zombie94 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie94, "zombie");
	    this.spawnEntity(zombie94, world, 106, -49, 0, start);
	    CreatureEntity skeleton95 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton95, "skeleton");
	    this.spawnEntity(skeleton95, world, 106, -9, 121, start);
	    CreatureEntity zombie96 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie96, "zombie");
	    this.spawnEntity(zombie96, world, 107, -39, 56, start);
	    CreatureEntity vindicator97 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator97, "vindicator");
	    this.spawnEntity(vindicator97, world, 107, 9, 40, start);
	    CreatureEntity husk98 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk98, "husk");
	    this.spawnEntity(husk98, world, 108, -19, 9, start);
	    CreatureEntity husk99 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk99, "husk");
	    this.spawnEntity(husk99, world, 108, -19, 13, start);
	    this.generateChest(world, Direction.NORTH, 108, 10, 54, start, 1);
	    this.generateChest(world, Direction.SOUTH, 109, -49, -34, start, 2);
	    CreatureEntity troll100 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:troll")).create(world);
	    this.setItemsForEntity(troll100, "troll");
	    this.spawnEntity(troll100, world, 109, -49, -26, start);
	    CreatureEntity zombie101 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie101, "zombie");
	    this.spawnEntity(zombie101, world, 109, -49, 21, start);
	    CreatureEntity skeleton102 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton102, "skeleton");
	    this.spawnEntity(skeleton102, world, 109, -40, -19, start);
	    this.generateChest(world, Direction.SOUTH, 109, -39, -21, start, 3);
	    CreatureEntity zombie103 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie103, "zombie");
	    this.spawnEntity(zombie103, world, 109, -39, -1, start);
	    CreatureEntity zombie104 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie104, "zombie");
	    this.spawnEntity(zombie104, world, 109, -39, 9, start);
	    CreatureEntity zombie105 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie105, "zombie");
	    this.spawnEntity(zombie105, world, 109, -39, 21, start);
	    this.generateChest(world, Direction.NORTH, 109, -38, 59, start, 2);
	    CreatureEntity zombie106 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie106, "zombie");
	    this.spawnEntity(zombie106, world, 111, -39, 56, start);
	    this.generateChest(world, Direction.WEST, 111, -18, 11, start, 2);
	    CreatureEntity zombie107 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie107, "zombie");
	    this.spawnEntity(zombie107, world, 112, -49, -6, start);
	    CreatureEntity zombie108 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie108, "zombie");
	    this.spawnEntity(zombie108, world, 112, -49, 0, start);
	    CreatureEntity husk109 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk109, "husk");
	    this.spawnEntity(husk109, world, 113, -9, 58, start);
	    CreatureEntity skeleton110 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton110, "skeleton");
	    this.spawnEntity(skeleton110, world, 114, -40, -17, start);
	    CreatureEntity skeleton111 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton111, "skeleton");
	    this.spawnEntity(skeleton111, world, 114, -40, -11, start);
	    CreatureEntity vindicator112 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator112, "vindicator");
	    this.spawnEntity(vindicator112, world, 115, 9, 78, start);
	    this.generateChest(world, Direction.WEST, 116, -49, -27, start, 2);
	    CreatureEntity skeleton113 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton113, "skeleton");
	    this.spawnEntity(skeleton113, world, 116, -49, -3, start);
	    CreatureEntity husk114 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk114, "husk");
	    this.spawnEntity(husk114, world, 116, -9, 28, start);
	    CreatureEntity skeleton115 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton115, "skeleton");
	    this.spawnEntity(skeleton115, world, 119, -40, 55, start);
	    CreatureEntity skeleton116 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton116, "skeleton");
	    this.spawnEntity(skeleton116, world, 119, -40, 61, start);
	    CreatureEntity skeleton117 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton117, "skeleton");
	    this.spawnEntity(skeleton117, world, 119, -40, 67, start);
	    CreatureEntity skeleton118 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton118, "skeleton");
	    this.spawnEntity(skeleton118, world, 119, -9, 12, start);
	    CreatureEntity skeleton119 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton119, "skeleton");
	    this.spawnEntity(skeleton119, world, 121, -40, 45, start);
	    CreatureEntity skeleton120 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton120, "skeleton");
	    this.spawnEntity(skeleton120, world, 121, -19, 56, start);
	    CreatureEntity skeleton121 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton121, "skeleton");
	    this.spawnEntity(skeleton121, world, 121, -19, 68, start);
	    this.generateChest(world, Direction.WEST, 121, -8, 12, start, 1);
	    CreatureEntity zombie122 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie122, "zombie");
	    this.spawnEntity(zombie122, world, 122, -50, -35, start);
	    CreatureEntity zombie123 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie123, "zombie");
	    this.spawnEntity(zombie123, world, 122, -50, -29, start);
	    CreatureEntity skeleton124 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton124, "skeleton");
	    this.spawnEntity(skeleton124, world, 122, -49, 25, start);
	    CreatureEntity skeleton125 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton125, "skeleton");
	    this.spawnEntity(skeleton125, world, 122, -49, 31, start);
	    CreatureEntity husk126 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk126, "husk");
	    this.spawnEntity(husk126, world, 123, -19, 60, start);
	    CreatureEntity husk127 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk127, "husk");
	    this.spawnEntity(husk127, world, 123, -19, 64, start);
	    CreatureEntity skeleton128 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton128, "skeleton");
	    this.spawnEntity(skeleton128, world, 124, -49, 23, start);
	    CreatureEntity skeleton129 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton129, "skeleton");
	    this.spawnEntity(skeleton129, world, 124, -49, 33, start);
	    CreatureEntity skeleton130 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton130, "skeleton");
	    this.spawnEntity(skeleton130, world, 124, -40, 69, start);
	    this.generateChest(world, Direction.NORTH, 124, -39, 71, start, 3);
	    CreatureEntity skeleton131 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton131, "skeleton");
	    this.spawnEntity(skeleton131, world, 125, -19, 28, start);
	    CreatureEntity skeleton132 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton132, "skeleton");
	    this.spawnEntity(skeleton132, world, 126, -9, 28, start);
	    CreatureEntity zombie133 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie133, "zombie");
	    this.spawnEntity(zombie133, world, 127, -50, -37, start);
	    CreatureEntity troll134 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:troll")).create(world);
	    this.setItemsForEntity(troll134, "troll");
	    this.spawnEntity(troll134, world, 127, -50, 7, start);
	    this.generateChest(world, Direction.SOUTH, 127, -49, -39, start, 3);
	    CreatureEntity troll135 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:troll")).create(world);
	    this.setItemsForEntity(troll135, "troll");
	    this.spawnEntity(troll135, world, 127, -49, 55, start);
	    CreatureEntity skeleton136 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton136, "skeleton");
	    this.spawnEntity(skeleton136, world, 127, -40, 45, start);
	    this.generateChest(world, Direction.WEST, 127, -18, 62, start, 2);
	    this.generateChest(world, Direction.WEST, 128, -8, 28, start, 2);
	    CreatureEntity skeleton137 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton137, "skeleton");
	    this.spawnEntity(skeleton137, world, 129, -40, 50, start);
	    CreatureEntity skeleton138 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton138, "skeleton");
	    this.spawnEntity(skeleton138, world, 129, -40, 61, start);
	    CreatureEntity skeleton139 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton139, "skeleton");
	    this.spawnEntity(skeleton139, world, 129, -40, 67, start);
	    CreatureEntity skeleton140 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton140, "skeleton");
	    this.spawnEntity(skeleton140, world, 130, -49, 23, start);
	    CreatureEntity skeleton141 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton141, "skeleton");
	    this.spawnEntity(skeleton141, world, 130, -49, 33, start);
	    CreatureEntity pillager142 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager142, "pillager");
	    this.spawnEntity(pillager142, world, 131, 13, 37, start);
	    CreatureEntity zombie143 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie143, "zombie");
	    this.spawnEntity(zombie143, world, 132, -50, -35, start);
	    CreatureEntity zombie144 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie144, "zombie");
	    this.spawnEntity(zombie144, world, 132, -50, -29, start);
	    CreatureEntity skeleton145 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton145, "skeleton");
	    this.spawnEntity(skeleton145, world, 132, -49, 25, start);
	    CreatureEntity skeleton146 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton146, "skeleton");
	    this.spawnEntity(skeleton146, world, 132, -49, 31, start);
	    CreatureEntity skeleton147 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton147, "skeleton");
	    this.spawnEntity(skeleton147, world, 134, -40, 33, start);
	    CreatureEntity skeleton148 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton148, "skeleton");
	    this.spawnEntity(skeleton148, world, 134, -40, 47, start);
	    CreatureEntity skeleton149 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton149, "skeleton");
	    this.spawnEntity(skeleton149, world, 134, -40, 53, start);
	    CreatureEntity skeleton150 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton150, "skeleton");
	    this.spawnEntity(skeleton150, world, 136, -40, 23, start);
	    CreatureEntity vindicator151 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator151, "vindicator");
	    this.spawnEntity(vindicator151, world, 138, 9, 75, start);
	    CreatureEntity skeleton152 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton152, "skeleton");
	    this.spawnEntity(skeleton152, world, 139, -40, 55, start);
	    this.generateChest(world, Direction.NORTH, 139, -39, 57, start, 3);
	    CreatureEntity zombie153 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie153, "zombie");
	    this.spawnEntity(zombie153, world, 140, -49, 8, start);
	    CreatureEntity skeleton154 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton154, "skeleton");
	    this.spawnEntity(skeleton154, world, 142, -40, 23, start);
	    CreatureEntity vindicator155 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator155, "vindicator");
	    this.spawnEntity(vindicator155, world, 142, 9, 75, start);
	    CreatureEntity vindicator156 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator156, "vindicator");
	    this.spawnEntity(vindicator156, world, 143, 9, 126, start);
	    CreatureEntity skeleton157 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton157, "skeleton");
	    this.spawnEntity(skeleton157, world, 144, -40, 33, start);
	    CreatureEntity skeleton158 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton158, "skeleton");
	    this.spawnEntity(skeleton158, world, 144, -40, 47, start);
	    CreatureEntity skeleton159 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton159, "skeleton");
	    this.spawnEntity(skeleton159, world, 144, -40, 53, start);
	    CreatureEntity pillager160 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager160, "pillager");
	    this.spawnEntity(pillager160, world, 144, 18, 68, start);
	    CreatureEntity zombie161 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie161, "zombie");
	    this.spawnEntity(zombie161, world, 146, -49, 8, start);
	    CreatureEntity skeleton162 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton162, "skeleton");
	    this.spawnEntity(skeleton162, world, 146, -19, 15, start);
	    CreatureEntity husk163 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk163, "husk");
	    this.spawnEntity(husk163, world, 146, -19, 28, start);
	    CreatureEntity skeleton164 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton164, "skeleton");
	    this.spawnEntity(skeleton164, world, 146, -19, 50, start);
	    this.generateChest(world, Direction.SOUTH, 146, -18, 13, start, 1);
	    this.generateChest(world, Direction.NORTH, 146, -18, 52, start, 1);
	    CreatureEntity skeleton165 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton165, "skeleton");
	    this.spawnEntity(skeleton165, world, 146, -9, 55, start);
	    CreatureEntity skeleton166 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton166, "skeleton");
	    this.spawnEntity(skeleton166, world, 146, -9, 61, start);
	    CreatureEntity pillager167 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager167, "pillager");
	    this.spawnEntity(pillager167, world, 147, 11, 112, start);
	    CreatureEntity vindicator168 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator168, "vindicator");
	    this.spawnEntity(vindicator168, world, 148, 9, 126, start);
	    CreatureEntity vindicator169 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator169, "vindicator");
	    this.spawnEntity(vindicator169, world, 151, 18, 52, start);
	    CreatureEntity zombie170 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie170, "zombie");
	    this.spawnEntity(zombie170, world, 152, -49, 8, start);
	    CreatureEntity skeleton171 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton171, "skeleton");
	    this.spawnEntity(skeleton171, world, 153, -50, 60, start);
	    CreatureEntity skeleton172 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton172, "skeleton");
	    this.spawnEntity(skeleton172, world, 154, -50, 50, start);
	    this.generateChest(world, Direction.WEST, 155, -38, 28, start, 2);
	    CreatureEntity husk173 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk173, "husk");
	    this.spawnEntity(husk173, world, 156, -49, 22, start);
	    CreatureEntity husk174 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk174, "husk");
	    this.spawnEntity(husk174, world, 156, -49, 34, start);
	    CreatureEntity zombie175 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie175, "zombie");
	    this.spawnEntity(zombie175, world, 158, -49, 8, start);
	    this.generateChest(world, Direction.WEST, 158, -8, 58, start, 2);
	    CreatureEntity skeleton176 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton176, "skeleton");
	    this.spawnEntity(skeleton176, world, 159, -50, 50, start);
	    CreatureEntity skeleton177 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton177, "skeleton");
	    this.spawnEntity(skeleton177, world, 159, -50, 60, start);
	    CreatureEntity skeleton178 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton178, "skeleton");
	    this.spawnEntity(skeleton178, world, 161, -50, 55, start);
	    this.generateChest(world, Direction.WEST, 162, -48, 28, start, 3);
	    CreatureEntity zombie179 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie179, "zombie");
	    this.spawnEntity(zombie179, world, 163, -49, 8, start);
	    this.generateChest(world, Direction.WEST, 163, -49, 55, start, 3);
	    this.generateChest(world, Direction.WEST, 167, -48, 8, start, 3);
	    CreatureEntity skeleton180 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton180, "skeleton");
	    this.spawnEntity(skeleton180, world, 170, -49, 5, start);
	    CreatureEntity skeleton181 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton181, "skeleton");
	    this.spawnEntity(skeleton181, world, 170, -49, 11, start);
	    CreatureEntity vindicator182 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator182, "vindicator");
	    this.spawnEntity(vindicator182, world, 170, 9, 98, start);
	    CreatureEntity vindicator183 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator183, "vindicator");
	    this.spawnEntity(vindicator183, world, 181, 9, 70, start);
	    CreatureEntity vindicator184 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator184, "vindicator");
	    this.spawnEntity(vindicator184, world, 184, 9, 41, start);
	    this.executeCommand(world);
	}

}
