package mod.arcalitegames.odyssey.world.structure.structures.dungeons.mayan_temple;

import java.util.Objects;

import mod.arcalitegames.odyssey.world.structure.StructureBase;
import mod.arcalitegames.system.parser.EntityParser;
import net.minecraft.block.Blocks;
import net.minecraft.entity.CreatureEntity;
import net.minecraft.util.Direction;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;

public class MayanTemple extends StructureBase
{

	public MayanTemple(World worldIn, BlockPos origin, int xRange, int yRange, int zRange)
	{
		super(worldIn, origin, xRange, yRange, zRange);
		TempleComponent0.init(world, origin, this);
		TempleComponent1.init(world, origin, this);
		TempleComponent2.init(world, origin, this);
		TempleComponent3.init(world, origin, this);
		TempleComponent4.init(world, origin, this);
		TempleComponent5.init(world, origin, this);
		TempleComponent6.init(world, origin, this);
		TempleComponent7.init(world, origin, this);
		TempleComponent8.init(world, origin, this);
		TempleComponent9.init(world, origin, this);
        this.fillWithBlocks(world, start, 18, 7, 18, 77, 45, 76, Blocks.AIR.getDefaultState());

	}

	@Override
	public void addEntitiesAndSpawn()
	{
	    this.generateChest(world, Direction.EAST, -31, -19, 47, start, 1);
	    this.generateChest(world, Direction.SOUTH, -26, -19, 42, start, 1);
	    CreatureEntity dread_knight1 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight1, "dread_knight");
	    this.spawnEntity(dread_knight1, world, -26, -19, 45, start);
	    CreatureEntity dread_knight2 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight2, "dread_knight");
	    this.spawnEntity(dread_knight2, world, -26, -19, 49, start);
	    this.generateChest(world, Direction.NORTH, -26, -19, 52, start, 1);
	    this.generateChest(world, Direction.EAST, -13, -9, 47, start, 1);
	    this.generateChest(world, Direction.EAST, -10, -38, 17, start, 3);
	    this.generateChest(world, Direction.EAST, -10, -19, 17, start, 2);
	    this.generateChest(world, Direction.EAST, -9, -19, 97, start, 2);
	    this.generateChest(world, Direction.SOUTH, -8, -9, 42, start, 1);
	    this.generateChest(world, Direction.NORTH, -8, -9, 52, start, 1);
	    this.generateChest(world, Direction.EAST, -8, -8, 47, start, 2);
	    CreatureEntity dread_knight3 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight3, "dread_knight");
	    this.spawnEntity(dread_knight3, world, -6, -29, -23, start);
	    CreatureEntity dread_knight4 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight4, "dread_knight");
	    this.spawnEntity(dread_knight4, world, -6, -29, -11, start);
	    this.generateChest(world, Direction.SOUTH, -5, -19, 12, start, 1);
	    CreatureEntity dread_lich5 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich5, "dread_lich");
	    this.spawnEntity(dread_lich5, world, -5, -19, 17, start);
	    this.generateChest(world, Direction.NORTH, -5, -19, 22, start, 1);
	    CreatureEntity dread_thrall6 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall6, "dread_thrall");
	    this.spawnEntity(dread_thrall6, world, -4, -19, 79, start);
	    this.generateChest(world, Direction.NORTH, -4, -19, 102, start, 2);
	    CreatureEntity dread_knight7 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight7, "dread_knight");
	    this.spawnEntity(dread_knight7, world, -2, -49, 13, start);
	    CreatureEntity dread_lich8 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich8, "dread_lich");
	    this.spawnEntity(dread_lich8, world, 0, -39, 11, start);
	    CreatureEntity dread_lich9 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich9, "dread_lich");
	    this.spawnEntity(dread_lich9, world, 0, -29, -17, start);
	    CreatureEntity dread_beast10 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_beast")).create(world);
	    this.setItemsForEntity(dread_beast10, "dread_beast");
	    this.spawnEntity(dread_beast10, world, 0, -29, 34, start);
	    this.generateChest(world, Direction.WEST, 1, -19, 97, start, 2);
	    this.generateChest(world, Direction.SOUTH, 4, -49, 7, start, 2);
	    this.generateChest(world, Direction.NORTH, 4, -49, 19, start, 2);
	    CreatureEntity dread_lich11 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich11, "dread_lich");
	    this.spawnEntity(dread_lich11, world, 4, -39, 29, start);
	    CreatureEntity dread_knight12 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight12, "dread_knight");
	    this.spawnEntity(dread_knight12, world, 6, -29, -23, start);
	    CreatureEntity dread_knight13 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight13, "dread_knight");
	    this.spawnEntity(dread_knight13, world, 6, -29, -11, start);
	    CreatureEntity dread_thrall14 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall14, "dread_thrall");
	    this.spawnEntity(dread_thrall14, world, 11, -29, 6, start);
	    this.generateChest(world, Direction.EAST, 11, -19, -10, start, 1);
	    CreatureEntity dread_thrall15 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall15, "dread_thrall");
	    this.spawnEntity(dread_thrall15, world, 11, -9, 40, start);
	    CreatureEntity dread_lich16 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich16, "dread_lich");
	    this.spawnEntity(dread_lich16, world, 11, -9, 47, start);
	    CreatureEntity dread_thrall17 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall17, "dread_thrall");
	    this.spawnEntity(dread_thrall17, world, 11, -9, 54, start);
	    CreatureEntity dread_knight18 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight18, "dread_knight");
	    this.spawnEntity(dread_knight18, world, 12, -39, 11, start);
	    CreatureEntity dread_knight19 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight19, "dread_knight");
	    this.spawnEntity(dread_knight19, world, 12, -39, 23, start);
	    CreatureEntity dread_lich20 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich20, "dread_lich");
	    this.spawnEntity(dread_lich20, world, 16, -29, 34, start);
	    this.generateChest(world, Direction.SOUTH, 16, -19, -15, start, 2);
	    CreatureEntity dread_lich21 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich21, "dread_lich");
	    this.spawnEntity(dread_lich21, world, 16, -19, -10, start);
	    CreatureEntity dread_lich22 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich22, "dread_lich");
	    this.spawnEntity(dread_lich22, world, 16, -19, 17, start);
	    CreatureEntity dread_lich23 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich23, "dread_lich");
	    this.spawnEntity(dread_lich23, world, 16, -19, 47, start);
	    CreatureEntity dread_beast24 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_beast")).create(world);
	    this.setItemsForEntity(dread_beast24, "dread_beast");
	    this.spawnEntity(dread_beast24, world, 16, -19, 79, start);
	    CreatureEntity dread_knight25 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight25, "dread_knight");
	    this.spawnEntity(dread_knight25, world, 17, -29, 0, start);
	    CreatureEntity dread_ghoul26 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul26, "dread_ghoul");
	    this.spawnEntity(dread_ghoul26, world, 17, -29, 17, start);
	    this.generateChest(world, Direction.WEST, 17, -28, -17, start, 3);
	    CreatureEntity goblin_kobold27 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_kobold")).create(world);
	    this.setItemsForEntity(goblin_kobold27, "goblin_kobold");
	    this.spawnEntity(goblin_kobold27, world, 19, 8, 47, start);
	    CreatureEntity goblin_knocker28 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_knocker")).create(world);
	    this.setItemsForEntity(goblin_knocker28, "goblin_knocker");
	    this.spawnEntity(goblin_knocker28, world, 19, 8, 73, start);
	    this.generateChest(world, Direction.EAST, 20, -49, -13, start, 2);
	    CreatureEntity goblin_knocker29 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_knocker")).create(world);
	    this.setItemsForEntity(goblin_knocker29, "goblin_knocker");
	    this.spawnEntity(goblin_knocker29, world, 20, 8, 74, start);
	    this.generateChest(world, Direction.WEST, 21, -19, -10, start, 1);
	    CreatureEntity goblin_knocker30 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_knocker")).create(world);
	    this.setItemsForEntity(goblin_knocker30, "goblin_knocker");
	    this.spawnEntity(goblin_knocker30, world, 21, 8, 20, start);
	    CreatureEntity goblin_knocker31 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_knocker")).create(world);
	    this.setItemsForEntity(goblin_knocker31, "goblin_knocker");
	    this.spawnEntity(goblin_knocker31, world, 21, 8, 21, start);
	    CreatureEntity dread_thrall32 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall32, "dread_thrall");
	    this.spawnEntity(dread_thrall32, world, 23, -29, -6, start);
	    CreatureEntity dread_lich33 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich33, "dread_lich");
	    this.spawnEntity(dread_lich33, world, 23, -29, 0, start);
	    CreatureEntity dread_ghoul34 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul34, "dread_ghoul");
	    this.spawnEntity(dread_ghoul34, world, 23, -29, 6, start);
	    CreatureEntity dread_knight35 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight35, "dread_knight");
	    this.spawnEntity(dread_knight35, world, 24, -39, 43, start);
	    CreatureEntity dread_thrall36 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall36, "dread_thrall");
	    this.spawnEntity(dread_thrall36, world, 24, -39, 44, start);
	    CreatureEntity dread_knight37 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight37, "dread_knight");
	    this.spawnEntity(dread_knight37, world, 24, -39, 45, start);
	    this.generateChest(world, Direction.EAST, 27, -52, 52, start, 3);
	    CreatureEntity dread_lich38 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich38, "dread_lich");
	    this.spawnEntity(dread_lich38, world, 27, -51, 52, start);
	    this.generateChest(world, Direction.EAST, 27, -29, 34, start, 1);
	    this.generateChest(world, Direction.EAST, 27, -19, 107, start, 1);
	    this.generateChest(world, Direction.EAST, 27, -9, 17, start, 1);
	    this.generateChest(world, Direction.EAST, 27, -8, 78, start, 1);
	    this.generateChest(world, Direction.EAST, 28, -39, 7, start, 1);
	    CreatureEntity dread_thrall39 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall39, "dread_thrall");
	    this.spawnEntity(dread_thrall39, world, 28, -39, 23, start);
	    this.generateChest(world, Direction.EAST, 29, -38, -13, start, 1);
	    CreatureEntity dread_knight40 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight40, "dread_knight");
	    this.spawnEntity(dread_knight40, world, 31, -9, 92, start);
	    this.generateChest(world, Direction.NORTH, 31, -8, 99, start, 2);
	    CreatureEntity dread_ghoul41 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul41, "dread_ghoul");
	    this.spawnEntity(dread_ghoul41, world, 32, -19, 55, start);
	    CreatureEntity dread_ghoul42 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul42, "dread_ghoul");
	    this.spawnEntity(dread_ghoul42, world, 32, -19, 77, start);
	    CreatureEntity dread_lich43 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich43, "dread_lich");
	    this.spawnEntity(dread_lich43, world, 32, -19, 107, start);
	    this.generateChest(world, Direction.NORTH, 32, -19, 112, start, 2);
	    this.generateChest(world, Direction.SOUTH, 32, -9, 12, start, 1);
	    CreatureEntity dread_knight44 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight44, "dread_knight");
	    this.spawnEntity(dread_knight44, world, 32, -9, 17, start);
	    CreatureEntity dread_knight45 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight45, "dread_knight");
	    this.spawnEntity(dread_knight45, world, 33, -39, 56, start);
	    CreatureEntity dread_lich46 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich46, "dread_lich");
	    this.spawnEntity(dread_lich46, world, 34, -39, 7, start);
	    CreatureEntity dread_thrall47 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall47, "dread_thrall");
	    this.spawnEntity(dread_thrall47, world, 34, -39, 56, start);
	    this.generateChest(world, Direction.SOUTH, 34, -38, 1, start, 2);
	    CreatureEntity dread_beast48 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_beast")).create(world);
	    this.setItemsForEntity(dread_beast48, "dread_beast");
	    this.spawnEntity(dread_beast48, world, 34, -29, -14, start);
	    CreatureEntity dread_lich49 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich49, "dread_lich");
	    this.spawnEntity(dread_lich49, world, 34, -29, 34, start);
	    this.generateChest(world, Direction.NORTH, 34, -29, 41, start, 1);
	    CreatureEntity dread_lich50 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich50, "dread_lich");
	    this.spawnEntity(dread_lich50, world, 35, -49, -18, start);
	    CreatureEntity dread_beast51 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_beast")).create(world);
	    this.setItemsForEntity(dread_beast51, "dread_beast");
	    this.spawnEntity(dread_beast51, world, 35, -49, 13, start);
	    CreatureEntity dread_knight52 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight52, "dread_knight");
	    this.spawnEntity(dread_knight52, world, 35, -39, 56, start);
	    CreatureEntity dread_knight53 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight53, "dread_knight");
	    this.spawnEntity(dread_knight53, world, 37, -39, -13, start);
	    this.generateChest(world, Direction.WEST, 37, -19, 107, start, 1);
	    this.generateChest(world, Direction.WEST, 37, -9, 17, start, 1);
	    this.generateChest(world, Direction.WEST, 40, -39, 7, start, 1);
	    CreatureEntity dread_knight54 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight54, "dread_knight");
	    this.spawnEntity(dread_knight54, world, 40, -39, 23, start);
	    CreatureEntity dread_knight55 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight55, "dread_knight");
	    this.spawnEntity(dread_knight55, world, 40, -39, 35, start);
	    CreatureEntity dread_knight56 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight56, "dread_knight");
	    this.spawnEntity(dread_knight56, world, 40, -39, 50, start);
	    CreatureEntity hobgoblin57 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_hobgoblin")).create(world);
	    this.setItemsForEntity(hobgoblin57, "hobgoblin");
	    this.spawnEntity(hobgoblin57, world, 42, 18, 46, start);
	    CreatureEntity goblin_knocker58 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_knocker")).create(world);
	    this.setItemsForEntity(goblin_knocker58, "goblin_knocker");
	    this.spawnEntity(goblin_knocker58, world, 42, 29, 47, start);
	    CreatureEntity dread_knight59 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight59, "dread_knight");
	    this.spawnEntity(dread_knight59, world, 43, -19, 36, start);
	    this.generateChest(world, Direction.SOUTH, 43, -18, 31, start, 2);
	    this.generateChest(world, Direction.EAST, 43, -9, 98, start, 1);
	    CreatureEntity dread_thrall60 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall60, "dread_thrall");
	    this.spawnEntity(dread_thrall60, world, 44, -39, -33, start);
	    CreatureEntity dread_knight61 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight61, "dread_knight");
	    this.spawnEntity(dread_knight61, world, 45, -39, 45, start);
	    CreatureEntity dread_knight62 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight62, "dread_knight");
	    this.spawnEntity(dread_knight62, world, 45, -39, 57, start);
	    CreatureEntity dread_ghoul63 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul63, "dread_ghoul");
	    this.spawnEntity(dread_ghoul63, world, 45, -29, 28, start);
	    CreatureEntity dread_ghoul64 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul64, "dread_ghoul");
	    this.spawnEntity(dread_ghoul64, world, 45, -29, 40, start);
	    this.generateChest(world, Direction.EAST, 47, -38, -1, start, 1);
	    CreatureEntity dread_knight65 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight65, "dread_knight");
	    this.spawnEntity(dread_knight65, world, 47, -29, -21, start);
	    CreatureEntity dread_knight66 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight66, "dread_knight");
	    this.spawnEntity(dread_knight66, world, 47, -29, -13, start);
	    this.generateChest(world, Direction.EAST, 47, 18, 44, start, 2);
	    CreatureEntity dread_ghoul67 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul67, "dread_ghoul");
	    this.spawnEntity(dread_ghoul67, world, 48, -9, 78, start);
	    this.generateChest(world, Direction.NORTH, 48, -9, 103, start, 1);
	    CreatureEntity goblin_kobold68 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_kobold")).create(world);
	    this.setItemsForEntity(goblin_kobold68, "goblin_kobold");
	    this.spawnEntity(goblin_kobold68, world, 48, 8, 18, start);
	    CreatureEntity goblin_kobold69 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_kobold")).create(world);
	    this.setItemsForEntity(goblin_kobold69, "goblin_kobold");
	    this.spawnEntity(goblin_kobold69, world, 48, 8, 76, start);
	    CreatureEntity goblin_knocker70 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_knocker")).create(world);
	    this.setItemsForEntity(goblin_knocker70, "goblin_knocker");
	    this.spawnEntity(goblin_knocker70, world, 48, 18, 40, start);
	    CreatureEntity hobgoblin71 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_hobgoblin")).create(world);
	    this.setItemsForEntity(hobgoblin71, "hobgoblin");
	    this.spawnEntity(hobgoblin71, world, 48, 18, 51, start);
	    CreatureEntity goblin_knocker72 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_knocker")).create(world);
	    this.setItemsForEntity(goblin_knocker72, "goblin_knocker");
	    this.spawnEntity(goblin_knocker72, world, 48, 29, 41, start);
	    CreatureEntity goblin_knocker73 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_knocker")).create(world);
	    this.setItemsForEntity(goblin_knocker73, "goblin_knocker");
	    this.spawnEntity(goblin_knocker73, world, 48, 29, 53, start);
	    this.generateChest(world, Direction.WEST, 49, 18, 44, start, 2);
	    this.generateChest(world, Direction.EAST, 50, -19, 2, start, 1);
	    this.generateChest(world, Direction.EAST, 50, -19, 79, start, 1);
	    this.generateChest(world, Direction.EAST, 50, -19, 99, start, 1);
	    CreatureEntity dread_knight74 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight74, "dread_knight");
	    this.spawnEntity(dread_knight74, world, 51, -39, 11, start);
	    CreatureEntity dread_lich75 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich75, "dread_lich");
	    this.spawnEntity(dread_lich75, world, 51, -39, 69, start);
	    this.generateChest(world, Direction.SOUTH, 51, -38, -39, start, 2);
	    this.generateChest(world, Direction.SOUTH, 51, -28, -17, start, 3);
	    this.generateChest(world, Direction.WEST, 51, -28, 34, start, 2);
	    this.generateChest(world, Direction.WEST, 53, -9, 98, start, 1);
	    CreatureEntity hobgoblin76 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_hobgoblin")).create(world);
	    this.setItemsForEntity(hobgoblin76, "hobgoblin");
	    this.spawnEntity(hobgoblin76, world, 54, 18, 43, start);
	    CreatureEntity goblin_knocker77 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_knocker")).create(world);
	    this.setItemsForEntity(goblin_knocker77, "goblin_knocker");
	    this.spawnEntity(goblin_knocker77, world, 54, 29, 47, start);
	    CreatureEntity dread_knight78 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight78, "dread_knight");
	    this.spawnEntity(dread_knight78, world, 55, -29, -21, start);
	    CreatureEntity dread_knight79 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight79, "dread_knight");
	    this.spawnEntity(dread_knight79, world, 55, -29, -13, start);
	    this.generateChest(world, Direction.SOUTH, 55, -19, -3, start, 1);
	    CreatureEntity dread_knight80 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight80, "dread_knight");
	    this.spawnEntity(dread_knight80, world, 55, -19, 2, start);
	    CreatureEntity dread_beast81 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_beast")).create(world);
	    this.setItemsForEntity(dread_beast81, "dread_beast");
	    this.spawnEntity(dread_beast81, world, 55, -19, 47, start);
	    CreatureEntity dread_ghoul82 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul82, "dread_ghoul");
	    this.spawnEntity(dread_ghoul82, world, 55, -19, 79, start);
	    CreatureEntity dread_thrall83 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall83, "dread_thrall");
	    this.spawnEntity(dread_thrall83, world, 55, -19, 99, start);
	    this.generateChest(world, Direction.NORTH, 55, -19, 104, start, 1);
	    CreatureEntity dread_thrall84 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall84, "dread_thrall");
	    this.spawnEntity(dread_thrall84, world, 57, -39, 45, start);
	    CreatureEntity dread_knight85 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight85, "dread_knight");
	    this.spawnEntity(dread_knight85, world, 57, -39, 57, start);
	    CreatureEntity dread_thrall86 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall86, "dread_thrall");
	    this.spawnEntity(dread_thrall86, world, 58, -39, -33, start);
	    CreatureEntity dread_thrall87 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall87, "dread_thrall");
	    this.spawnEntity(dread_thrall87, world, 58, -39, 23, start);
	    CreatureEntity dread_knight88 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight88, "dread_knight");
	    this.spawnEntity(dread_knight88, world, 58, -39, 35, start);
	    CreatureEntity dread_knight89 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight89, "dread_knight");
	    this.spawnEntity(dread_knight89, world, 60, -52, 48, start);
	    CreatureEntity dread_knight90 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight90, "dread_knight");
	    this.spawnEntity(dread_knight90, world, 60, -52, 56, start);
	    this.generateChest(world, Direction.WEST, 60, -19, 2, start, 1);
	    this.generateChest(world, Direction.WEST, 60, -19, 99, start, 1);
	    this.generateChest(world, Direction.SOUTH, 61, -39, -17, start, 2);
	    this.generateChest(world, Direction.SOUTH, 64, -51, -47, start, 3);
	    CreatureEntity dread_beast91 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_beast")).create(world);
	    this.setItemsForEntity(dread_beast91, "dread_beast");
	    this.spawnEntity(dread_beast91, world, 64, -50, -47, start);
	    CreatureEntity dread_thrall92 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall92, "dread_thrall");
	    this.spawnEntity(dread_thrall92, world, 64, -49, -13, start);
	    CreatureEntity dread_ghoul93 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul93, "dread_ghoul");
	    this.spawnEntity(dread_ghoul93, world, 64, -49, 5, start);
	    CreatureEntity dread_ghoul94 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul94, "dread_ghoul");
	    this.spawnEntity(dread_ghoul94, world, 64, -49, 21, start);
	    CreatureEntity dread_thrall96 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall96, "dread_thrall");
	    this.spawnEntity(dread_thrall96, world, 64, -49, 74, start);
	    this.generateChest(world, Direction.NORTH, 64, -49, 80, start, 3);
	    CreatureEntity dread_knight97 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight97, "dread_knight");
	    this.spawnEntity(dread_knight97, world, 64, -39, 58, start);
	    this.generateChest(world, Direction.NORTH, 64, -38, 59, start, 2);
	    CreatureEntity dread_knight98 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight98, "dread_knight");
	    this.spawnEntity(dread_knight98, world, 68, -52, 48, start);
	    CreatureEntity dread_knight99 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight99, "dread_knight");
	    this.spawnEntity(dread_knight99, world, 68, -52, 56, start);
	    CreatureEntity dread_knight100 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight100, "dread_knight");
	    this.spawnEntity(dread_knight100, world, 70, -39, 23, start);
	    CreatureEntity dread_thrall101 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall101, "dread_thrall");
	    this.spawnEntity(dread_thrall101, world, 70, -39, 35, start);
	    CreatureEntity dread_ghoul102 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul102, "dread_ghoul");
	    this.spawnEntity(dread_ghoul102, world, 73, -9, 47, start);
	    CreatureEntity goblin_knocker103 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_knocker")).create(world);
	    this.setItemsForEntity(goblin_knocker103, "goblin_knocker");
	    this.spawnEntity(goblin_knocker103, world, 75, 8, 20, start);
	    CreatureEntity goblin_knocker104 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_knocker")).create(world);
	    this.setItemsForEntity(goblin_knocker104, "goblin_knocker");
	    this.spawnEntity(goblin_knocker104, world, 75, 8, 21, start);
	    CreatureEntity goblin_knocker105 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_knocker")).create(world);
	    this.setItemsForEntity(goblin_knocker105, "goblin_knocker");
	    this.spawnEntity(goblin_knocker105, world, 76, 8, 73, start);
	    CreatureEntity goblin_knocker106 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_knocker")).create(world);
	    this.setItemsForEntity(goblin_knocker106, "goblin_knocker");
	    this.spawnEntity(goblin_knocker106, world, 76, 8, 74, start);
	    CreatureEntity dread_knight107 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight107, "dread_knight");
	    this.spawnEntity(dread_knight107, world, 77, -39, 50, start);
	    CreatureEntity dread_thrall108 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall108, "dread_thrall");
	    this.spawnEntity(dread_thrall108, world, 77, -39, 51, start);
	    CreatureEntity dread_knight109 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight109, "dread_knight");
	    this.spawnEntity(dread_knight109, world, 77, -39, 52, start);
	    CreatureEntity goblin_kobold110 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_kobold")).create(world);
	    this.setItemsForEntity(goblin_kobold110, "goblin_kobold");
	    this.spawnEntity(goblin_kobold110, world, 77, 8, 47, start);
	    CreatureEntity dread_beast111 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_beast")).create(world);
	    this.setItemsForEntity(dread_beast111, "dread_beast");
	    this.spawnEntity(dread_beast111, world, 80, -39, -13, start);
	    CreatureEntity dread_knight112 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight112, "dread_knight");
	    this.spawnEntity(dread_knight112, world, 80, -19, 29, start);
	    CreatureEntity dread_lich113 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich113, "dread_lich");
	    this.spawnEntity(dread_lich113, world, 80, -19, 47, start);
	    this.generateChest(world, Direction.SOUTH, 80, -18, 21, start, 2);
	    this.generateChest(world, Direction.WEST, 86, -52, 52, start, 3);
	    CreatureEntity dread_beast114 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_beast")).create(world);
	    this.setItemsForEntity(dread_beast114, "dread_beast");
	    this.spawnEntity(dread_beast114, world, 86, -49, 73, start);
	    this.generateChest(world, Direction.SOUTH, 86, -19, 74, start, 1);
	    CreatureEntity dread_thrall115 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall115, "dread_thrall");
	    this.spawnEntity(dread_thrall115, world, 86, -19, 79, start);
	    this.generateChest(world, Direction.NORTH, 86, -19, 84, start, 1);
	    this.generateChest(world, Direction.WEST, 91, -19, 79, start, 1);
	    this.generateChest(world, Direction.SOUTH, 92, -39, 23, start, 2);
	    CreatureEntity dread_knight116 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight116, "dread_knight");
	    this.spawnEntity(dread_knight116, world, 92, -39, 28, start);
	    CreatureEntity dread_lich117 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich117, "dread_lich");
	    this.spawnEntity(dread_lich117, world, 92, -39, 29, start);
	    CreatureEntity dread_knight118 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight118, "dread_knight");
	    this.spawnEntity(dread_knight118, world, 92, -39, 30, start);
	    this.generateChest(world, Direction.NORTH, 92, -39, 35, start, 2);
	    CreatureEntity dread_ghoul119 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul119, "dread_ghoul");
	    this.spawnEntity(dread_ghoul119, world, 98, -49, -15, start);
	    CreatureEntity dread_ghoul120 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul120, "dread_ghoul");
	    this.spawnEntity(dread_ghoul120, world, 98, -49, -11, start);
	    this.generateChest(world, Direction.WEST, 98, -39, 29, start, 2);
	    CreatureEntity dread_knight121 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight121, "dread_knight");
	    this.spawnEntity(dread_knight121, world, 103, -19, 47, start);
	    this.generateChest(world, Direction.SOUTH, 106, -9, 42, start, 1);
	    CreatureEntity dread_thrall122 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall122, "dread_thrall");
	    this.spawnEntity(dread_thrall122, world, 106, -9, 45, start);
	    CreatureEntity dread_thrall123 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall123, "dread_thrall");
	    this.spawnEntity(dread_thrall123, world, 106, -9, 49, start);
	    this.generateChest(world, Direction.NORTH, 106, -9, 52, start, 1);
	    this.generateChest(world, Direction.WEST, 109, -18, 47, start, 2);
	    this.generateChest(world, Direction.WEST, 111, -9, 47, start, 1);
	    CreatureEntity dread_lich124 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich124, "dread_lich");
	    this.spawnEntity(dread_lich124, world, 116, -49, -13, start);
	    this.executeCommand(world);
	}

}
