package mod.arcalitegames.odyssey.world.structure.town.bashkarcity;

import java.util.Objects;

import mod.arcalitegames.odyssey.entity.CounterEntity;
import mod.arcalitegames.odyssey.entity.citizens.bashkarcity.guards.BashkarPatrollingGuard;
import mod.arcalitegames.odyssey.entity.citizens.bashkarcity.guards.BashkarStandingGuard;
import mod.arcalitegames.odyssey.entity.passive.CitizenEntity;
import mod.arcalitegames.odyssey.entity.passive.MerchantEntity;
import mod.arcalitegames.odyssey.world.structure.town.TownStructure;
import mod.arcalitegames.odyssey.world.structure.town.TownStructures;
import mod.arcalitegames.system.parser.EntityParser;
import net.minecraft.block.Blocks;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;

public class BashkarCity extends TownStructure
{

	public BashkarCity(World worldIn, BlockPos origin, int xRange, int yRange, int zRange)
	{
		super(worldIn, origin, xRange, yRange, zRange);
		BashkarComponent0.init(world, origin, this);
		BashkarComponent1.init(world, origin, this);
		BashkarComponent2.init(world, origin, this);
        this.fillWithBlocks(world, start, -32, -6, -68, 111, 65, 55, Blocks.AIR.getDefaultState());
	}

	@Override
	public void addEntitiesAndSpawn()
	{
	    BashkarStandingGuard standing_guard1 = (BashkarStandingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bashkar_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard1, "standing_guard");
	    this.spawnEntity(standing_guard1, world, -27, -5, -20, start);
	    BashkarStandingGuard standing_guard2 = (BashkarStandingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bashkar_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard2, "standing_guard");
	    this.spawnEntity(standing_guard2, world, -27, -5, -12, start);
	    CitizenEntity jaza_riaz = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:jaza_riaz")).create(world);
	    this.setItemsForEntity(jaza_riaz, "citizen");
	    this.spawnEntity(jaza_riaz, world, -24, -5, -42, start);
	    BashkarPatrollingGuard patrolling_guard4 = (BashkarPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bashkar_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard4, "patrolling_guard");
	    this.spawnEntity(patrolling_guard4, world, -22, -5, -58, start);
	    BashkarStandingGuard standing_guard5 = (BashkarStandingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bashkar_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard5, "standing_guard");
	    this.spawnEntity(standing_guard5, world, -16, -5, 27, start);
	    MerchantEntity horse_merchant = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:horse_merchant")).create(world);
	    this.setItemsForEntity(horse_merchant, "merchant");
	    this.spawnEntity(horse_merchant, world, -15, -5, -26, start);
	    CitizenEntity kadyn_ghazi = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:kadyn_ghazi")).create(world);
	    this.setItemsForEntity(kadyn_ghazi, "citizen");
	    this.spawnEntity(kadyn_ghazi, world, -15, -5, 29, start);
	    CounterEntity counter8 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter8, "counter");
	    this.spawnEntity(counter8, world, -15, -4, -25, start);
	    CitizenEntity abdullah_mahfouz = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:abdullah_mahfouz")).create(world);
	    this.setItemsForEntity(abdullah_mahfouz, "citizen");
	    this.spawnEntity(abdullah_mahfouz, world, -13, -5, -55, start);
	    BashkarStandingGuard standing_guard10 = (BashkarStandingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bashkar_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard10, "standing_guard");
	    this.spawnEntity(standing_guard10, world, -13, -5, 2, start);
	    BashkarPatrollingGuard patrolling_guard11 = (BashkarPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bashkar_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard11, "patrolling_guard");
	    this.spawnEntity(patrolling_guard11, world, -11, -5, 51, start);
	    CitizenEntity umair_khalili = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:umair_khalili")).create(world);
	    this.setItemsForEntity(umair_khalili, "citizen");
	    this.spawnEntity(umair_khalili, world, -7, -5, -58, start);
	    BashkarStandingGuard standing_guard13 = (BashkarStandingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bashkar_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard13, "standing_guard");
	    this.spawnEntity(standing_guard13, world, -7, 5, -26, start);
	    CitizenEntity jamale_azzam = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:jamale_azzam")).create(world);
	    this.setItemsForEntity(jamale_azzam, "citizen");
	    this.spawnEntity(jamale_azzam, world, -4, 0, 27, start);
	    CitizenEntity khalid_meskin = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:khalid_meskin")).create(world);
	    this.setItemsForEntity(khalid_meskin, "citizen");
	    this.spawnEntity(khalid_meskin, world, -3, 0, -9, start);
	    BashkarPatrollingGuard patrolling_guard16 = (BashkarPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bashkar_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard16, "patrolling_guard");
	    this.spawnEntity(patrolling_guard16, world, -2, 0, -2, start);
	    CounterEntity counter17 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter17, "counter");
	    this.spawnEntity(counter17, world, -2, 1, 9, start);
	    CitizenEntity waleed_amen = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:waleed_amen")).create(world);
	    this.setItemsForEntity(waleed_amen, "citizen");
	    this.spawnEntity(waleed_amen, world, -1, 0, -30, start);
	    CitizenEntity qabil_shahan = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:qabil_shahan")).create(world);
	    this.setItemsForEntity(qabil_shahan, "citizen");
	    this.spawnEntity(qabil_shahan, world, -1, 0, -24, start);
	    MerchantEntity baker = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:baker")).create(world);
	    this.setItemsForEntity(baker, "merchant");
	    this.spawnEntity(baker, world, -1, 0, 9, start);
	    CitizenEntity lujayn_soliman = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:lujayn_soliman")).create(world);
	    this.setItemsForEntity(lujayn_soliman, "citizen");
	    this.spawnEntity(lujayn_soliman, world, -1, 5, -31, start);
	    CitizenEntity hawiya_dar = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:hawiya_dar")).create(world);
	    this.setItemsForEntity(hawiya_dar, "citizen");
	    this.spawnEntity(hawiya_dar, world, 0, 0, -19, start);
	    CitizenEntity nash_habib = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:nash_habib")).create(world);
	    this.setItemsForEntity(nash_habib, "citizen");
	    this.spawnEntity(nash_habib, world, 2, 0, -30, start);
	    BashkarStandingGuard standing_guard24 = (BashkarStandingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bashkar_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard24, "standing_guard");
	    this.spawnEntity(standing_guard24, world, 2, 5, -45, start);
	    CitizenEntity haziqa_kazemi = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:haziqa_kazemi")).create(world);
	    this.setItemsForEntity(haziqa_kazemi, "citizen");
	    this.spawnEntity(haziqa_kazemi, world, 3, 5, -38, start);
	    CitizenEntity azhar_madani = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:azhar_madani")).create(world);
	    this.setItemsForEntity(azhar_madani, "citizen");
	    this.spawnEntity(azhar_madani, world, 3, 5, 12, start);
	    CitizenEntity hulyah_rais = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:hulyah_rais")).create(world);
	    this.setItemsForEntity(hulyah_rais, "citizen");
	    this.spawnEntity(hulyah_rais, world, 4, 0, -26, start);
	    CitizenEntity noreen_wali = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:noreen_wali")).create(world);
	    this.setItemsForEntity(noreen_wali, "citizen");
	    this.spawnEntity(noreen_wali, world, 4, 0, -18, start);
	    BashkarPatrollingGuard patrolling_guard29 = (BashkarPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bashkar_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard29, "patrolling_guard");
	    this.spawnEntity(patrolling_guard29, world, 4, 0, 35, start);
	    MerchantEntity butcher = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:butcher")).create(world);
	    this.setItemsForEntity(butcher, "merchant");
	    this.spawnEntity(butcher, world, 4, 5, -24, start);
	    CounterEntity counter31 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter31, "counter");
	    this.spawnEntity(counter31, world, 5, 6, -24, start);
	    BashkarPatrollingGuard patrolling_guard32 = (BashkarPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bashkar_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard32, "patrolling_guard");
	    this.spawnEntity(patrolling_guard32, world, 6, 0, -54, start);
	    BashkarStandingGuard standing_guard33 = (BashkarStandingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bashkar_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard33, "standing_guard");
	    this.spawnEntity(standing_guard33, world, 6, 5, 12, start);
	    CitizenEntity shaffan_samara = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:shaffan_samara")).create(world);
	    this.setItemsForEntity(shaffan_samara, "citizen");
	    this.spawnEntity(shaffan_samara, world, 8, 0, -51, start);
	    CitizenEntity rukan_mansouri = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:rukan_mansouri")).create(world);
	    this.setItemsForEntity(rukan_mansouri, "citizen");
	    this.spawnEntity(rukan_mansouri, world, 8, 0, -5, start);
	    BashkarPatrollingGuard patrolling_guard36 = (BashkarPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bashkar_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard36, "patrolling_guard");
	    this.spawnEntity(patrolling_guard36, world, 8, 5, -47, start);
	    CitizenEntity nasya_abad = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:nasya_abad")).create(world);
	    this.setItemsForEntity(nasya_abad, "citizen");
	    this.spawnEntity(nasya_abad, world, 9, 5, -18, start);
	    CitizenEntity ghashia_saab = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:ghashia_saab")).create(world);
	    this.setItemsForEntity(ghashia_saab, "citizen");
	    this.spawnEntity(ghashia_saab, world, 10, 0, -30, start);
	    CitizenEntity tehmina_baluch = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:tehmina_baluch")).create(world);
	    this.setItemsForEntity(tehmina_baluch, "citizen");
	    this.spawnEntity(tehmina_baluch, world, 10, 0, -18, start);
	    CitizenEntity mahibah_rahman = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:mahibah_rahman")).create(world);
	    this.setItemsForEntity(mahibah_rahman, "citizen");
	    this.spawnEntity(mahibah_rahman, world, 10, 0, -15, start);
	    CitizenEntity yahminah_hashmi = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:yahminah_hashmi")).create(world);
	    this.setItemsForEntity(yahminah_hashmi, "citizen");
	    this.spawnEntity(yahminah_hashmi, world, 10, 5, -24, start);
	    CitizenEntity hashim_jabbour = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:hashim_jabbour")).create(world);
	    this.setItemsForEntity(hashim_jabbour, "citizen");
	    this.spawnEntity(hashim_jabbour, world, 12, 0, 30, start);
	    CounterEntity counter43 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter43, "counter");
	    this.spawnEntity(counter43, world, 12, 1, -16, start);
	    BashkarStandingGuard standing_guard44 = (BashkarStandingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bashkar_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard44, "standing_guard");
	    this.spawnEntity(standing_guard44, world, 13, -5, -65, start);
	    MerchantEntity inn_keeper = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:inn_keeper")).create(world);
	    this.setItemsForEntity(inn_keeper, "merchant");
	    this.spawnEntity(inn_keeper, world, 13, 0, -16, start);
	    MerchantEntity fletching_merchant = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:fletching_merchant")).create(world);
	    this.setItemsForEntity(fletching_merchant, "merchant");
	    this.spawnEntity(fletching_merchant, world, 13, 5, 12, start);
	    CounterEntity counter47 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter47, "counter");
	    this.spawnEntity(counter47, world, 14, 6, 12, start);
	    CitizenEntity mawiyah_popal = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:mawiyah_popal")).create(world);
	    this.setItemsForEntity(mawiyah_popal, "citizen");
	    this.spawnEntity(mawiyah_popal, world, 16, 0, -52, start);
	    MerchantEntity guildmaster = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:guildmaster")).create(world);
	    this.setItemsForEntity(guildmaster, "merchant");
	    this.spawnEntity(guildmaster, world, 16, 0, 9, start);
	    CitizenEntity faiqa_rauf = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:faiqa_rauf")).create(world);
	    this.setItemsForEntity(faiqa_rauf, "citizen");
	    this.spawnEntity(faiqa_rauf, world, 16, 0, 31, start);
	    CounterEntity counter51 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter51, "counter");
	    this.spawnEntity(counter51, world, 16, 1, 8, start);
	    BashkarPatrollingGuard patrolling_guard52 = (BashkarPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bashkar_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard52, "patrolling_guard");
	    this.spawnEntity(patrolling_guard52, world, 16, 5, 24, start);
	    CitizenEntity hafifah_maroun = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:hafifah_maroun")).create(world);
	    this.setItemsForEntity(hafifah_maroun, "citizen");
	    this.spawnEntity(hafifah_maroun, world, 17, 5, -19, start);
	    BashkarPatrollingGuard patrolling_guard54 = (BashkarPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bashkar_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard54, "patrolling_guard");
	    this.spawnEntity(patrolling_guard54, world, 18, 5, -22, start);
	    CitizenEntity amir_baksh = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:amir_baksh")).create(world);
	    this.setItemsForEntity(amir_baksh, "citizen");
	    this.spawnEntity(amir_baksh, world, 20, 5, 18, start);
	    MerchantEntity redstone_merchant = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:redstone_merchant")).create(world);
	    this.setItemsForEntity(redstone_merchant, "merchant");
	    this.spawnEntity(redstone_merchant, world, 22, 5, -10, start);
	    CitizenEntity afra_sarah = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:afra_sarah")).create(world);
	    this.setItemsForEntity(afra_sarah, "citizen");
	    this.spawnEntity(afra_sarah, world, 22, 5, 12, start);
	    CounterEntity counter58 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter58, "counter");
	    this.spawnEntity(counter58, world, 22, 6, -11, start);
	    BashkarPatrollingGuard patrolling_guard59 = (BashkarPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bashkar_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard59, "patrolling_guard");
	    this.spawnEntity(patrolling_guard59, world, 23, 5, 5, start);
	    BashkarStandingGuard standing_guard60 = (BashkarStandingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bashkar_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard60, "standing_guard");
	    this.spawnEntity(standing_guard60, world, 25, -5, 49, start);
	    CitizenEntity roheen_younis = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:roheen_younis")).create(world);
	    this.setItemsForEntity(roheen_younis, "citizen");
	    this.spawnEntity(roheen_younis, world, 25, 5, -40, start);
	    CitizenEntity wajeeda_kazmi = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:wajeeda_kazmi")).create(world);
	    this.setItemsForEntity(wajeeda_kazmi, "citizen");
	    this.spawnEntity(wajeeda_kazmi, world, 25, 5, -38, start);
	    CitizenEntity aalam_noori = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:aalam_noori")).create(world);
	    this.setItemsForEntity(aalam_noori, "citizen");
	    this.spawnEntity(aalam_noori, world, 25, 5, -24, start);
	    CounterEntity counter64 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter64, "counter");
	    this.spawnEntity(counter64, world, 31, 6, 17, start);
	    MerchantEntity decor_merchant = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:decor_merchant")).create(world);
	    this.setItemsForEntity(decor_merchant, "merchant");
	    this.spawnEntity(decor_merchant, world, 32, 5, 17, start);
	    MerchantEntity craftsman = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:craftsman")).create(world);
	    this.setItemsForEntity(craftsman, "merchant");
	    this.spawnEntity(craftsman, world, 33, 5, -28, start);
	    CounterEntity counter67 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter67, "counter");
	    this.spawnEntity(counter67, world, 33, 6, -27, start);
	    CounterEntity counter68 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter68, "counter");
	    this.spawnEntity(counter68, world, 33, 6, 4, start);
	    MerchantEntity farming_merchant = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:farming_merchant")).create(world);
	    this.setItemsForEntity(farming_merchant, "merchant");
	    this.spawnEntity(farming_merchant, world, 34, 5, 4, start);
	    BashkarPatrollingGuard patrolling_guard70 = (BashkarPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bashkar_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard70, "patrolling_guard");
	    this.spawnEntity(patrolling_guard70, world, 34, 5, 32, start);
	    MerchantEntity mineshop_merchant = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:mineshop_merchant")).create(world);
	    this.setItemsForEntity(mineshop_merchant, "merchant");
	    this.spawnEntity(mineshop_merchant, world, 38, 10, 1, start);
	    CounterEntity counter72 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter72, "counter");
	    this.spawnEntity(counter72, world, 38, 11, 0, start);
	    MerchantEntity produce_vendor = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:produce_vendor")).create(world);
	    this.setItemsForEntity(produce_vendor, "merchant");
	    this.spawnEntity(produce_vendor, world, 39, 5, -18, start);
	    CounterEntity counter74 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter74, "counter");
	    this.spawnEntity(counter74, world, 39, 6, -17, start);
	    CitizenEntity casildo_rassi = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:casildo_rassi")).create(world);
	    this.setItemsForEntity(casildo_rassi, "citizen");
	    this.spawnEntity(casildo_rassi, world, 39, 10, -7, start);
	    CitizenEntity shunnar_kamali = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:shunnar_kamali")).create(world);
	    this.setItemsForEntity(shunnar_kamali, "citizen");
	    this.spawnEntity(shunnar_kamali, world, 39, 10, -5, start);
	    BashkarPatrollingGuard patrolling_guard77 = (BashkarPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bashkar_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard77, "patrolling_guard");
	    this.spawnEntity(patrolling_guard77, world, 43, -5, -61, start);
	    BashkarPatrollingGuard patrolling_guard78 = (BashkarPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bashkar_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard78, "patrolling_guard");
	    this.spawnEntity(patrolling_guard78, world, 43, 10, 23, start);
	    CitizenEntity musfirah_abed = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:musfirah_abed")).create(world);
	    this.setItemsForEntity(musfirah_abed, "citizen");
	    this.spawnEntity(musfirah_abed, world, 45, 10, 21, start);
	    MerchantEntity alchemist = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:alchemist")).create(world);
	    this.setItemsForEntity(alchemist, "merchant");
	    this.spawnEntity(alchemist, world, 46, 1, 6, start);
	    CounterEntity counter81 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter81, "counter");
	    this.spawnEntity(counter81, world, 46, 2, 5, start);
	    CitizenEntity fanila_abdou = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:fanila_abdou")).create(world);
	    this.setItemsForEntity(fanila_abdou, "citizen");
	    this.spawnEntity(fanila_abdou, world, 46, 10, 14, start);
	    BashkarStandingGuard standing_guard83 = (BashkarStandingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bashkar_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard83, "standing_guard");
	    this.spawnEntity(standing_guard83, world, 47, 5, -38, start);
	    BashkarPatrollingGuard patrolling_guard84 = (BashkarPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bashkar_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard84, "patrolling_guard");
	    this.spawnEntity(patrolling_guard84, world, 49, 10, -28, start);
	    CitizenEntity asifa_waheed = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:asifa_waheed")).create(world);
	    this.setItemsForEntity(asifa_waheed, "citizen");
	    this.spawnEntity(asifa_waheed, world, 50, 0, -43, start);
	    CitizenEntity khulus_satter = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:khulus_satter")).create(world);
	    this.setItemsForEntity(khulus_satter, "citizen");
	    this.spawnEntity(khulus_satter, world, 51, 10, 5, start);
	    BashkarPatrollingGuard patrolling_guard87 = (BashkarPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bashkar_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard87, "patrolling_guard");
	    this.spawnEntity(patrolling_guard87, world, 53, 0, -45, start);
	    CitizenEntity bahir_islam = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bahir_islam")).create(world);
	    this.setItemsForEntity(bahir_islam, "citizen");
	    this.spawnEntity(bahir_islam, world, 54, 10, -8, start);
	    BashkarPatrollingGuard patrolling_guard89 = (BashkarPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bashkar_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard89, "patrolling_guard");
	    this.spawnEntity(patrolling_guard89, world, 55, 10, 0, start);
	    CitizenEntity gharam_naderi = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:gharam_naderi")).create(world);
	    this.setItemsForEntity(gharam_naderi, "citizen");
	    this.spawnEntity(gharam_naderi, world, 56, 0, 32, start);
	    CitizenEntity laseef_rabbani = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:laseef_rabbani")).create(world);
	    this.setItemsForEntity(laseef_rabbani, "citizen");
	    this.spawnEntity(laseef_rabbani, world, 57, 0, -49, start);
	    CounterEntity counter92 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter92, "counter");
	    this.spawnEntity(counter92, world, 57, 11, -17, start);
	    MerchantEntity blacksmith = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:blacksmith")).create(world);
	    this.setItemsForEntity(blacksmith, "merchant");
	    this.spawnEntity(blacksmith, world, 58, 10, -17, start);
	    CitizenEntity dabir_meer = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:dabir_meer")).create(world);
	    this.setItemsForEntity(dabir_meer, "citizen");
	    this.spawnEntity(dabir_meer, world, 59, 10, 5, start);
	    BashkarPatrollingGuard patrolling_guard95 = (BashkarPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bashkar_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard95, "patrolling_guard");
	    this.spawnEntity(patrolling_guard95, world, 63, -5, 44, start);
	    CitizenEntity latif_sani = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:latif_sani")).create(world);
	    this.setItemsForEntity(latif_sani, "citizen");
	    this.spawnEntity(latif_sani, world, 66, 5, -35, start);
	    BashkarStandingGuard standing_guard97 = (BashkarStandingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bashkar_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard97, "standing_guard");
	    this.spawnEntity(standing_guard97, world, 66, 5, 23, start);
	    CounterEntity counter98 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter98, "counter");
	    this.spawnEntity(counter98, world, 67, 11, -2, start);
	    MerchantEntity shop_keeper = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:shop_keeper")).create(world);
	    this.setItemsForEntity(shop_keeper, "merchant");
	    this.spawnEntity(shop_keeper, world, 68, 10, -2, start);
	    MerchantEntity fruit_vendor = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:fruit_vendor")).create(world);
	    this.setItemsForEntity(fruit_vendor, "merchant");
	    this.spawnEntity(fruit_vendor, world, 69, 10, -14, start);
	    CounterEntity counter101 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter101, "counter");
	    this.spawnEntity(counter101, world, 69, 11, -13, start);
	    CitizenEntity nasheem_mahdi = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:nasheem_mahdi")).create(world);
	    this.setItemsForEntity(nasheem_mahdi, "citizen");
	    this.spawnEntity(nasheem_mahdi, world, 70, 5, -40, start);
	    CitizenEntity raaina_ishmael = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:raaina_ishmael")).create(world);
	    this.setItemsForEntity(raaina_ishmael, "citizen");
	    this.spawnEntity(raaina_ishmael, world, 71, 5, 9, start);
	    BashkarStandingGuard standing_guard104 = (BashkarStandingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bashkar_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard104, "standing_guard");
	    this.spawnEntity(standing_guard104, world, 72, 5, -32, start);
	    CitizenEntity taima_abdalla = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:taima_abdalla")).create(world);
	    this.setItemsForEntity(taima_abdalla, "citizen");
	    this.spawnEntity(taima_abdalla, world, 74, 5, -7, start);
	    BashkarStandingGuard standing_guard106 = (BashkarStandingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bashkar_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard106, "standing_guard");
	    this.spawnEntity(standing_guard106, world, 76, 0, 30, start);
	    BashkarPatrollingGuard patrolling_guard107 = (BashkarPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bashkar_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard107, "patrolling_guard");
	    this.spawnEntity(patrolling_guard107, world, 76, 5, 13, start);
	    CitizenEntity murtadi_hariri = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:murtadi_hariri")).create(world);
	    this.setItemsForEntity(murtadi_hariri, "citizen");
	    this.spawnEntity(murtadi_hariri, world, 77, 5, -21, start);
	    CitizenEntity shafiq_hashemi = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:shafiq_hashemi")).create(world);
	    this.setItemsForEntity(shafiq_hashemi, "citizen");
	    this.spawnEntity(shafiq_hashemi, world, 80, 5, -18, start);
	    BashkarPatrollingGuard patrolling_guard110 = (BashkarPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bashkar_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard110, "patrolling_guard");
	    this.spawnEntity(patrolling_guard110, world, 82, -5, -53, start);
	    BashkarPatrollingGuard patrolling_guard111 = (BashkarPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bashkar_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard111, "patrolling_guard");
	    this.spawnEntity(patrolling_guard111, world, 82, 5, -13, start);
	    CitizenEntity faraz_ammar = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:faraz_ammar")).create(world);
	    this.setItemsForEntity(faraz_ammar, "citizen");
	    this.spawnEntity(faraz_ammar, world, 82, 5, -6, start);
	    CitizenEntity alyan_rabbani = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:alyan_rabbani")).create(world);
	    this.setItemsForEntity(alyan_rabbani, "citizen");
	    this.spawnEntity(alyan_rabbani, world, 83, 5, -18, start);
	    BashkarStandingGuard standing_guard114 = (BashkarStandingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bashkar_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard114, "standing_guard");
	    this.spawnEntity(standing_guard114, world, 93, 0, -15, start);
	    BashkarPatrollingGuard patrolling_guard115 = (BashkarPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bashkar_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard115, "patrolling_guard");
	    this.spawnEntity(patrolling_guard115, world, 96, -5, 29, start);
	    BashkarPatrollingGuard patrolling_guard116 = (BashkarPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bashkar_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard116, "patrolling_guard");
	    this.spawnEntity(patrolling_guard116, world, 96, 0, -26, start);
	    BashkarPatrollingGuard patrolling_guard117 = (BashkarPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bashkar_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard117, "patrolling_guard");
	    this.spawnEntity(patrolling_guard117, world, 99, -5, -40, start);
	    BashkarPatrollingGuard patrolling_guard118 = (BashkarPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bashkar_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard118, "patrolling_guard");
	    this.spawnEntity(patrolling_guard118, world, 102, -5, -1, start);
	    this.executeCommand(world);
	    if(TownStructures.teleportBashkarCity()) this.transportPlayertoTown(TownStructures.BASHKAR_CITY.get(), "Teleported player to Bashkar City.", 7, 6);
	}
	
	

}
