package mod.arcalitegames.odyssey.trades.merchants;

import mod.arcalitegames.odyssey.enums.CoinType;
import mod.arcalitegames.odyssey.trades.TradeManager;
import mod.arcalitegames.odyssey.trades.TradeOption;
import mod.arcalitegames.odyssey.trades.products.MerchantProduct;
import mod.arcalitegames.system.collections.MerchantSet;
import mod.arcalitegames.system.parser.ItemParser;
import net.minecraft.client.gui.widget.button.ImageButton;
import net.minecraft.item.Items;
public class GuildTrades extends TradeOption
{

	public static MerchantSet<MerchantProduct> getSpecialWeapons()
	{
		INSTANCE.addAll(  
				new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonbone_sword"), CoinType.SILVER, 160, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonbone_sword"), 160, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonbone_shovel"), CoinType.SILVER, 80, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonbone_shovel"), 80, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonbone_pickaxe"), CoinType.SILVER, 240, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonbone_pickaxe"), 240, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonbone_axe"), CoinType.SILVER, 240, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonbone_axe"), 240, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonbone_hoe"), CoinType.SILVER, 160, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonbone_hoe"), 160, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonbone_sword_fire"), CoinType.SILVER, 256, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonbone_sword_fire"), 256, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonbone_sword_ice"), CoinType.SILVER, 280, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonbone_sword_ice"), 280, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonbone_sword_lightning"), CoinType.SILVER, 320, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonbone_sword_lightning"), 320, false); })),
				new MerchantProduct(ItemParser.getItemFromName("iceandfire:myrmex_desert_sword"), CoinType.BRONZE, 348, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:myrmex_desert_sword"), 348, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:myrmex_desert_sword_venom"), CoinType.BRONZE, 400, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:myrmex_desert_sword_venom"), 400, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:myrmex_desert_shovel"), CoinType.BRONZE, 246, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:myrmex_desert_shovel"), 246, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:myrmex_desert_pickaxe"), CoinType.BRONZE, 546, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:myrmex_desert_pickaxe"), 546, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:myrmex_desert_axe"), CoinType.BRONZE, 546, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:myrmex_desert_axe"), 546, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:myrmex_desert_hoe"), CoinType.BRONZE, 348, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:myrmex_desert_hoe"), 348, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:myrmex_jungle_sword"), CoinType.BRONZE, 348, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:myrmex_jungle_sword"), 348, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:myrmex_jungle_sword_venom"), CoinType.BRONZE, 400, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:myrmex_jungle_sword_venom"), 400, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:myrmex_jungle_shovel"), CoinType.BRONZE, 246, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:myrmex_jungle_shovel"), 246, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:myrmex_jungle_pickaxe"), CoinType.BRONZE, 546, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:myrmex_jungle_pickaxe"), 546, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:myrmex_jungle_axe"), CoinType.BRONZE, 546, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:myrmex_jungle_axe"), 546, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:myrmex_jungle_hoe"), CoinType.BRONZE, 348, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:myrmex_jungle_hoe"), 348, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:myrmex_desert_swarm"), CoinType.BRONZE, 952, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:myrmex_desert_swarm"), 952, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:myrmex_jungle_swarm"), CoinType.BRONZE, 952, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:myrmex_jungle_swarm"), 952, false); })),
			 	new MerchantProduct(ItemParser.getItemFromName("iceandfire:tide_trident"), CoinType.GOLD, 54, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:tide_trident"), 54, false); }))
		);
		
		return INSTANCE.LIST;
	}
	
	public static MerchantSet<MerchantProduct> getSpecialTools()
	{
		INSTANCE.addAll(  
				new MerchantProduct(ItemParser.getItemFromName("iceandfire:bestiary"), CoinType.SILVER, 4, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:bestiary"), 4, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:manuscript"), CoinType.BRONZE, 128, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:manuscript"), 128, false); })),
			    new MerchantProduct(Items.END_PORTAL_FRAME, CoinType.GOLD, 24, new ImageButton(5, height, 65, 20 , 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(Items.END_PORTAL_FRAME, 24, false); })),
        		new MerchantProduct(Items.ENDER_CHEST, CoinType.SILVER, 48, new ImageButton(5, height, 65, 20 , 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(Items.ENDER_CHEST, 48, false); })), 
				new MerchantProduct(ItemParser.getItemFromName("iceandfire:lectern"), CoinType.BRONZE, 150, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:lectern"), 150, false); })),
				new MerchantProduct(Items.ENCHANTING_TABLE, CoinType.GOLD, 80, new ImageButton(5, height, 65, 20 , 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(Items.ENCHANTING_TABLE, 80, false); })),
			 	new MerchantProduct(ItemParser.getItemFromName("iceandfire:siren_flute"), CoinType.SILVER, 161, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:siren_flute"), 161, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:hippocampus_fin"), CoinType.GOLD, 32, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:hippocampus_fin"), 32, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:hippocampus_slapper"), CoinType.GOLD, 32, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:hippocampus_slapper"), 32, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:earplugs"), CoinType.BRONZE, 16, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:earplugs"), 16, false); })),	
				new MerchantProduct(ItemParser.getItemFromName("iceandfire:chain_link"), CoinType.BRONZE, 468, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:chain_link"), 468, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:chain_sticky"), CoinType.BRONZE, 476, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:chain_sticky"), 476, false); })),
				new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonforge_fire_input"), CoinType.SILVER, 221, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonforge_fire_input"), 221, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonforge_ice_input"), CoinType.SILVER, 221, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonforge_ice_input"), 221, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonforge_lightning_input"), CoinType.SILVER, 221, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonforge_lightning_input"), 221, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonforge_fire_core"), CoinType.GOLD, 2528, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonforge_fire_core"), 2528, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonforge_ice_core"), CoinType.GOLD, 2528, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonforge_ice_core"), 2528, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonforge_lightning_core"), CoinType.GOLD, 2528, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonforge_lightning_core"), 2528, false); }))
		);
		
		return INSTANCE.LIST;
	}
	
	public static MerchantSet<MerchantProduct> getRareItems()
	{
		INSTANCE.addAll(  
				new MerchantProduct(Items.CONDUIT, CoinType.GOLD, 112, new ImageButton(5, height, 65, 20 , 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(Items.CONDUIT, 112, false); })),
       		 	new MerchantProduct(Items.END_CRYSTAL, CoinType.SILVER, 24, new ImageButton(5, height, 65, 20 , 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(Items.END_CRYSTAL, 24, false); })),
       		 	new MerchantProduct(Items.ELYTRA, CoinType.GOLD, 2, new ImageButton(5, height, 65, 20 , 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(Items.ELYTRA, 2, false); })),
       		 	new MerchantProduct(Items.TOTEM_OF_UNDYING, CoinType.GOLD, 1, new ImageButton(5, height, 65, 20 , 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(Items.TOTEM_OF_UNDYING, 1, false); })),
       		 	new MerchantProduct(Items.TRIDENT, CoinType.GOLD, 10, new ImageButton(5, height, 65, 20 , 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(Items.TRIDENT, 10, false); })),
       		 	new MerchantProduct(Items.RESPAWN_ANCHOR, CoinType.SILVER, 25, new ImageButton(5, height, 65, 20 , 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(Items.RESPAWN_ANCHOR, 25, false); })),
			    new MerchantProduct(Items.ENDER_EYE, CoinType.SILVER, 16, new ImageButton(5, height, 65, 20 , 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(Items.ENDER_EYE, 16, false); })),
			    new MerchantProduct(Items.DRAGON_BREATH, CoinType.SILVER, 10, new ImageButton(5, height, 65, 20 , 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(Items.DRAGON_BREATH, 10, false); })),
				new MerchantProduct(ItemParser.getItemFromName("iceandfire:dread_key"), CoinType.SILVER, 8, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dread_key"), 8, false); })),
				new MerchantProduct(ItemParser.getItemFromName("iceandfire:fire_dragon_blood"), CoinType.SILVER, 96, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:fire_dragon_blood"), 96, false); })),
		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:ice_dragon_blood"), CoinType.SILVER, 120, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:ice_dragon_blood"), 120, false); })),
		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:lightning_dragon_blood"), CoinType.SILVER, 160, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:lightning_dragon_blood"), 160, false); }))
		);
		
		return INSTANCE.LIST;
	}
	
	public static MerchantSet<MerchantProduct> getGuildBanners()
	{
		INSTANCE.addAll(  
				new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_red_helmet"), CoinType.SILVER, 480, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_red_helmet"), 480, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_red_chestplate"), CoinType.SILVER, 768, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_red_chestplate"), 768, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_red_leggings"), CoinType.SILVER, 672, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_red_leggings"), 672, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_red_boots"), CoinType.SILVER, 384, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_red_boots"), 384, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_emerald_helmet"), CoinType.SILVER, 480, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_emerald_helmet"), 480, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_emerald_chestplate"), CoinType.SILVER, 768, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_emerald_chestplate"), 768, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_emerald_leggings"), CoinType.SILVER, 672, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_emerald_leggings"), 672, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_emerald_boots"), CoinType.SILVER, 384, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_emerald_boots"), 384, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_bronze_helmet"), CoinType.SILVER, 480, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_bronze_helmet"), 480, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_bronze_chestplate"), CoinType.SILVER, 768, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_bronze_chestplate"), 768, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_bronze_leggings"), CoinType.SILVER, 672, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_bronze_leggings"), 672, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_bronze_boots"), CoinType.SILVER, 384, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_bronze_boots"), 384, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_gray_helmet"), CoinType.SILVER, 480, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_gray_helmet"), 480, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_gray_chestplate"), CoinType.SILVER, 768, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_gray_chestplate"), 768, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_gray_leggings"), CoinType.SILVER, 672, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_gray_leggings"), 672, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_gray_boots"), CoinType.SILVER, 384, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_gray_boots"), 384, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_blue_helmet"), CoinType.SILVER, 480, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_blue_helmet"), 480, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_blue_chestplate"), CoinType.SILVER, 768, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_blue_chestplate"), 768, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_blue_leggings"), CoinType.SILVER, 672, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_blue_leggings"), 672, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_blue_boots"), CoinType.SILVER, 384, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_blue_boots"), 384, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_white_helmet"), CoinType.SILVER, 480, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_white_helmet"), 480, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_white_chestplate"), CoinType.SILVER, 768, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_white_chestplate"), 768, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_white_leggings"), CoinType.SILVER, 672, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_white_leggings"), 672, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_white_boots"), CoinType.SILVER, 384, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_white_boots"), 384, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_sapphire_helmet"), CoinType.SILVER, 480, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_sapphire_helmet"), 480, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_sapphire_chestplate"), CoinType.SILVER, 768, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_sapphire_chestplate"), 768, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_sapphire_leggings"), CoinType.SILVER, 672, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_sapphire_leggings"), 672, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_sapphire_boots"), CoinType.SILVER, 384, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_sapphire_boots"), 384, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_silver_helmet"), CoinType.SILVER, 480, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_silver_helmet"), 480, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_silver_chestplate"), CoinType.SILVER, 768, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_silver_chestplate"), 768, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_silver_leggings"), CoinType.SILVER, 672, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_silver_leggings"), 672, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_silver_boots"), CoinType.SILVER, 384, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_silver_boots"), 384, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_electric_helmet"), CoinType.SILVER, 480, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_electric_helmet"), 480, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_electric_chestplate"), CoinType.SILVER, 768, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_electric_chestplate"), 768, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_electric_leggings"), CoinType.SILVER, 672, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_electric_leggings"), 672, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_electric_boots"), CoinType.SILVER, 384, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_electric_boots"), 384, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_amethyst_helmet"), CoinType.SILVER, 480, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_amethyst_helmet"), 480, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_amethyst_chestplate"), CoinType.SILVER, 768, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_amethyst_chestplate"), 768, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_amethyst_leggings"), CoinType.SILVER, 672, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_amethyst_leggings"), 672, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_amethyst_boots"), CoinType.SILVER, 384, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_amethyst_boots"), 384, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_copper_helmet"), CoinType.SILVER, 480, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_copper_helmet"), 480, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_copper_chestplate"), CoinType.SILVER, 768, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_copper_chestplate"), 768, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_copper_leggings"), CoinType.SILVER, 672, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_copper_leggings"), 672, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_copper_boots"), CoinType.SILVER, 384, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_copper_boots"), 384, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_black_helmet"), CoinType.SILVER, 480, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_black_helmet"), 480, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_black_chestplate"), CoinType.SILVER, 768, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_black_chestplate"), 768, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_black_leggings"), CoinType.SILVER, 672, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_black_leggings"), 672, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:armor_black_boots"), CoinType.SILVER, 384, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:armor_black_boots"), 384, false); })),
				new MerchantProduct(ItemParser.getItemFromName("iceandfire:tide_blue_helmet"), CoinType.SILVER, 1040, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:tide_blue_helmet"), 1040, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:tide_blue_chestplate"), CoinType.SILVER, 1664, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:tide_blue_chestplate"), 1664, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:tide_blue_leggings"), CoinType.SILVER, 1456, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:tide_blue_leggings"), 1456, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:tide_blue_boots"), CoinType.SILVER, 832, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:tide_blue_boots"), 832, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:tide_bronze_helmet"), CoinType.SILVER, 1040, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:tide_bronze_helmet"), 1040, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:tide_bronze_chestplate"), CoinType.SILVER, 1664, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:tide_bronze_chestplate"), 1664, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:tide_bronze_leggings"), CoinType.SILVER, 1456, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:tide_bronze_leggings"), 1456, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:tide_bronze_boots"), CoinType.SILVER, 832, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:tide_bronze_boots"), 832, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:tide_deepblue_helmet"), CoinType.SILVER, 1040, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:tide_deepblue_helmet"), 1040, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:tide_deepblue_chestplate"), CoinType.SILVER, 1664, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:tide_deepblue_chestplate"), 1664, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:tide_deepblue_leggings"), CoinType.SILVER, 1456, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:tide_deepblue_leggings"), 1456, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:tide_deepblue_boots"), CoinType.SILVER, 832, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:tide_deepblue_boots"), 832, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:tide_green_helmet"), CoinType.SILVER, 1040, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:tide_green_helmet"), 1040, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:tide_green_chestplate"), CoinType.SILVER, 1664, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:tide_green_chestplate"), 1664, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:tide_deepblue_leggings"), CoinType.SILVER, 1456, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:tide_deepblue_leggings"), 1456, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:tide_green_boots"), CoinType.SILVER, 832, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:tide_green_boots"), 832, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:tide_purple_helmet"), CoinType.SILVER, 1040, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:tide_purple_helmet"), 1040, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:tide_purple_chestplate"), CoinType.SILVER, 1664, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:tide_purple_chestplate"), 1664, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:tide_purple_leggings"), CoinType.SILVER, 1456, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:tide_purple_leggings"), 1456, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:tide_purple_boots"), CoinType.SILVER, 832, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:tide_purple_boots"), 832, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:tide_red_helmet"), CoinType.SILVER, 1040, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:tide_red_helmet"), 1040, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:tide_red_chestplate"), CoinType.SILVER, 1664, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:tide_red_chestplate"), 1664, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:tide_red_leggings"), CoinType.SILVER, 1456, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:tide_red_leggings"), 1456, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:tide_red_boots"), CoinType.SILVER, 832, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:tide_red_boots"), 832, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:tide_teal_helmet"), CoinType.SILVER, 1040, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:tide_teal_helmet"), 1040, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:tide_teal_chestplate"), CoinType.SILVER, 1664, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:tide_teal_chestplate"), 1664, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:tide_teal_leggings"), CoinType.SILVER, 1456, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:tide_teal_leggings"), 1456, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:tide_teal_boots"), CoinType.SILVER, 832, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:tide_teal_boots"), 832, false); })),
				new MerchantProduct(ItemParser.getItemFromName("iceandfire:myrmex_desert_helmet"), CoinType.BRONZE, 750, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:myrmex_desert_helmet"), 750, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:myrmex_desert_chestplate"), CoinType.BRONZE, 1200, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:myrmex_desert_chestplate"), 1200, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:myrmex_desert_leggings"), CoinType.BRONZE, 1050, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:myrmex_desert_leggings"), 1050, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:myrmex_desert_boots"), CoinType.BRONZE, 600, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:myrmex_desert_boots"), 600, false); })),
				new MerchantProduct(ItemParser.getItemFromName("iceandfire:myrmex_jungle_helmet"), CoinType.BRONZE, 750, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:myrmex_jungle_helmet"), 750, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:myrmex_jungle_chestplate"), CoinType.BRONZE, 1200, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:myrmex_jungle_chestplate"), 1200, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:myrmex_jungle_leggings"), CoinType.BRONZE, 1050, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:myrmex_jungle_leggings"), 1050, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:myrmex_jungle_boots"), CoinType.BRONZE, 600, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:myrmex_jungle_boots"), 600, false); })),
				new MerchantProduct(ItemParser.getItemFromName("iceandfire:deathworm_yellow_helmet"), CoinType.BRONZE, 640, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:deathworm_yellow_helmet"), 640, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:deathworm_yellow_chestplate"), CoinType.BRONZE, 1024, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:deathworm_yellow_chestplate"), 1024, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:deathworm_yellow_leggings"), CoinType.BRONZE, 896, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:deathworm_yellow_leggings"), 896, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:deathworm_yellow_boots"), CoinType.BRONZE, 512, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:deathworm_yellow_boots"), 512, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:deathworm_white_helmet"), CoinType.BRONZE, 640, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:deathworm_white_helmet"), 640, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:deathworm_white_chestplate"), CoinType.BRONZE, 1024, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:deathworm_white_chestplate"), 1024, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:deathworm_white_leggings"), CoinType.BRONZE, 896, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:deathworm_white_leggings"), 896, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:deathworm_white_boots"), CoinType.BRONZE, 512, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:deathworm_white_boots"), 512, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:deathworm_red_helmet"), CoinType.BRONZE, 640, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:deathworm_red_helmet"), 640, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:deathworm_red_chestplate"), CoinType.BRONZE, 1024, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:deathworm_red_chestplate"), 1024, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:deathworm_red_leggings"), CoinType.BRONZE, 896, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:deathworm_red_leggings"), 896, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:deathworm_red_boots"), CoinType.BRONZE, 512, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:deathworm_red_boots"), 512, false); })),
				new MerchantProduct(ItemParser.getItemFromName("iceandfire:iron_hippogryph_armor"), CoinType.SILVER, 15, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:iron_hippogryph_armor"), 15, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:gold_hippogryph_armor"), CoinType.GOLD, 96, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:gold_hippogryph_armor"), 96, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:diamond_hippogryph_armor"), CoinType.GOLD, 480, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:diamond_hippogryph_armor"), 480, false); })),
				new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonarmor_iron_head"), CoinType.SILVER, 58, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonarmor_iron_head"), 58, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonarmor_iron_neck"), CoinType.SILVER, 58, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonarmor_iron_neck"), 58, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonarmor_iron_body"), CoinType.SILVER, 92, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonarmor_iron_body"), 92, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonarmor_iron_tail"), CoinType.SILVER, 35, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonarmor_iron_tail"), 35, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonarmor_copper_head"), CoinType.SILVER, 29, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonarmor_copper_head"), 29, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonarmor_copper_neck"), CoinType.SILVER, 29, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonarmor_copper_neck"), 29, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonarmor_copper_body"), CoinType.SILVER, 46, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonarmor_copper_body"), 46, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonarmor_copper_tail"), CoinType.SILVER, 17, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonarmor_copper_tail"), 17, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonarmor_gold_head"), CoinType.GOLD, 360, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonarmor_gold_head"), 360, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonarmor_gold_neck"), CoinType.GOLD, 360, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonarmor_gold_neck"), 360, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonarmor_gold_body"), CoinType.GOLD, 576, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonarmor_gold_body"), 576, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonarmor_gold_tail"), CoinType.GOLD, 216, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonarmor_gold_tail"), 216, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonarmor_diamond_head"), CoinType.GOLD, 1800, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonarmor_diamond_head"), 1800, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonarmor_diamond_neck"), CoinType.GOLD, 1800, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonarmor_diamond_neck"), 1800, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonarmor_diamond_body"), CoinType.GOLD, 2880, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonarmor_diamond_body"), 2880, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonarmor_diamond_tail"), CoinType.GOLD, 1080, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonarmor_diamond_tail"), 1080, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonarmor_silver_head"), CoinType.SILVER, 720, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonarmor_silver_head"), 720, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonarmor_silver_neck"), CoinType.SILVER, 720, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonarmor_silver_neck"), 720, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonarmor_silver_body"), CoinType.SILVER, 1152, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonarmor_silver_body"), 1152, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonarmor_silver_tail"), CoinType.SILVER, 432, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonarmor_silver_tail"), 432, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonarmor_dragonsteel_fire_head"), CoinType.GOLD, 360, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonarmor_dragonsteel_fire_head"), 360, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonarmor_dragonsteel_fire_neck"), CoinType.GOLD, 360, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonarmor_dragonsteel_fire_neck"), 360, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonarmor_dragonsteel_fire_body"), CoinType.GOLD, 576, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonarmor_dragonsteel_fire_body"), 576, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonarmor_dragonsteel_fire_tail"), CoinType.GOLD, 216, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonarmor_dragonsteel_fire_tail"), 216, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonarmor_dragonsteel_ice_head"), CoinType.GOLD, 360, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonarmor_dragonsteel_ice_head"), 360, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonarmor_dragonsteel_ice_neck"), CoinType.GOLD, 360, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonarmor_dragonsteel_ice_neck"), 360, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonarmor_dragonsteel_ice_body"), CoinType.GOLD, 576, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonarmor_dragonsteel_ice_body"), 576, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonarmor_dragonsteel_ice_tail"), CoinType.GOLD, 216, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonarmor_dragonsteel_ice_tail"), 216, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonarmor_dragonsteel_lightning_head"), CoinType.GOLD, 720, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonarmor_dragonsteel_lightning_head"), 720, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonarmor_dragonsteel_lightning_neck"), CoinType.GOLD, 720, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonarmor_dragonsteel_lightning_neck"), 720, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonarmor_dragonsteel_lightning_body"), CoinType.GOLD, 1152, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonarmor_dragonsteel_lightning_body"), 1152, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonarmor_dragonsteel_lightning_tail"), CoinType.GOLD, 432, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonarmor_dragonsteel_lightning_tail"), 432, false); }))
		);
		
		return INSTANCE.LIST;
	}
	
	public static MerchantSet<MerchantProduct> getDragonArmor()
	{
		INSTANCE.addAll( 
			 new MerchantProduct(Items.WHITE_BANNER, CoinType.SILVER, 2, new ImageButton(5, height, 65, 20 , 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(Items.WHITE_BANNER, 2, false); })),
       		 new MerchantProduct(Items.ORANGE_BANNER, CoinType.SILVER, 3, new ImageButton(5, height, 65, 20 , 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(Items.ORANGE_BANNER, 3, false); })),
       		 new MerchantProduct(Items.MAGENTA_BANNER, CoinType.SILVER, 3, new ImageButton(5, height, 65, 20 , 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(Items.MAGENTA_BANNER, 3, false); })),
       		 new MerchantProduct(Items.LIGHT_BLUE_BANNER, CoinType.SILVER, 3, new ImageButton(5, height, 65, 20 , 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(Items.LIGHT_BLUE_BANNER, 3, false); })),
       		 new MerchantProduct(Items.YELLOW_BANNER, CoinType.BRONZE, 240, new ImageButton(5, height, 65, 20 , 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(Items.YELLOW_BANNER, 240, false); })),
       		 new MerchantProduct(Items.LIME_BANNER, CoinType.SILVER, 3, new ImageButton(5, height, 65, 20 , 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(Items.LIME_BANNER, 3, false); })),
       		 new MerchantProduct(Items.PINK_BANNER, CoinType.SILVER, 3, new ImageButton(5, height, 65, 20 , 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(Items.PINK_BANNER, 3, false); })),
       		 new MerchantProduct(Items.GRAY_BANNER, CoinType.SILVER, 3, new ImageButton(5, height, 65, 20 , 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(Items.GRAY_BANNER, 3, false); })),
       		 new MerchantProduct(Items.LIGHT_GRAY_BANNER, CoinType.BRONZE, 432, new ImageButton(5, height, 65, 20 , 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(Items.LIGHT_GRAY_BANNER, 432, false); })),
       		 new MerchantProduct(Items.CYAN_BANNER, CoinType.SILVER, 4, new ImageButton(5, height, 65, 20 , 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(Items.CYAN_BANNER, 4, false); })),
       		 new MerchantProduct(Items.PURPLE_BANNER, CoinType.SILVER, 3, new ImageButton(5, height, 65, 20 , 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(Items.PURPLE_BANNER, 3, false); })),
       		 new MerchantProduct(Items.BLUE_BANNER, CoinType.SILVER, 4, new ImageButton(5, height, 65, 20 , 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(Items.BLUE_BANNER, 4, false); })),
       		 new MerchantProduct(Items.BROWN_BANNER, CoinType.SILVER, 4, new ImageButton(5, height, 65, 20 , 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(Items.BROWN_BANNER, 4, false); })),
       		 new MerchantProduct(Items.GREEN_BANNER, CoinType.SILVER, 4, new ImageButton(5, height, 65, 20 , 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(Items.GREEN_BANNER, 4, false); })),
       		 new MerchantProduct(Items.RED_BANNER, CoinType.BRONZE, 240, new ImageButton(5, height, 65, 20 , 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(Items.RED_BANNER, 240, false); })),
       		 new MerchantProduct(Items.BLACK_BANNER, CoinType.SILVER, 4, new ImageButton(5, height, 65, 20 , 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(Items.BLACK_BANNER, 4, false); })),
			 new MerchantProduct(Items.FLOWER_BANNER_PATTERN, CoinType.BRONZE, 40, new ImageButton(5, height, 65, 20 , 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(Items.FLOWER_BANNER_PATTERN, 40, false); })),
       		 new MerchantProduct(Items.CREEPER_BANNER_PATTERN, CoinType.SILVER, 8, new ImageButton(5, height, 65, 20 , 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(Items.CREEPER_BANNER_PATTERN, 8, false); })),
       		 new MerchantProduct(Items.SKULL_BANNER_PATTERN, CoinType.SILVER, 8, new ImageButton(5, height, 65, 20 , 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(Items.SKULL_BANNER_PATTERN, 8, false); })),
       		 new MerchantProduct(Items.GLOBE_BANNER_PATTERN, CoinType.SILVER, 8, new ImageButton(5, height, 65, 20 , 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(Items.GLOBE_BANNER_PATTERN, 8, false); })),
       		 new MerchantProduct(Items.PIGLIN_BANNER_PATTERN, CoinType.SILVER, 8, new ImageButton(5, height, 65, 20 , 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(Items.PIGLIN_BANNER_PATTERN, 8, false); })),
				 new MerchantProduct(ItemParser.getItemFromName("iceandfire:banner_pattern_fire"), CoinType.SILVER, 8, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:banner_pattern_fire"), 8, false); })),
		     	 new MerchantProduct(ItemParser.getItemFromName("iceandfire:banner_pattern_ice"), CoinType.SILVER, 8, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:banner_pattern_ice"), 8, false); })),
		     	 new MerchantProduct(ItemParser.getItemFromName("iceandfire:banner_pattern_lightning"), CoinType.SILVER, 8, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:banner_pattern_lightning"), 8, false); })),
		     	 new MerchantProduct(ItemParser.getItemFromName("iceandfire:banner_pattern_fire_head"), CoinType.GOLD, 8, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:banner_pattern_fire_head"), 8, false); })),
		     	 new MerchantProduct(ItemParser.getItemFromName("iceandfire:banner_pattern_ice_head"), CoinType.GOLD, 8, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:banner_pattern_ice_head"), 8, false); })),
		     	 new MerchantProduct(ItemParser.getItemFromName("iceandfire:banner_pattern_lightning_head"), CoinType.GOLD, 12, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:banner_pattern_lightning_head"), 12, false); })),
		     	 new MerchantProduct(ItemParser.getItemFromName("iceandfire:banner_pattern_amphithere"), CoinType.BRONZE, 128, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:banner_pattern_amphithere"), 128, false); })),
		     	 new MerchantProduct(ItemParser.getItemFromName("iceandfire:banner_pattern_bird"), CoinType.BRONZE, 128, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:banner_pattern_bird"), 128, false); })),
		     	 new MerchantProduct(ItemParser.getItemFromName("iceandfire:banner_pattern_eye"), CoinType.SILVER, 24, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:banner_pattern_eye"), 24, false); })),
		     	 new MerchantProduct(ItemParser.getItemFromName("iceandfire:banner_pattern_fae"), CoinType.GOLD, 8, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:banner_pattern_fae"), 8, false); })),
		     	 new MerchantProduct(ItemParser.getItemFromName("iceandfire:banner_pattern_feather"), CoinType.SILVER, 1, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:banner_pattern_feather"), 1, false); })),
		     	 new MerchantProduct(ItemParser.getItemFromName("iceandfire:banner_pattern_gorgon"), CoinType.SILVER, 204, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:banner_pattern_gorgon"), 204, false); })),
		     	 new MerchantProduct(ItemParser.getItemFromName("iceandfire:banner_pattern_hippocampus"), CoinType.BRONZE, 128, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:banner_pattern_hippocampus"), 128, false); })),
		     	 new MerchantProduct(ItemParser.getItemFromName("iceandfire:banner_pattern_hippogryph_head"), CoinType.BRONZE, 128, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:banner_pattern_hippogryph_head"), 128, false); })),
		     	 new MerchantProduct(ItemParser.getItemFromName("iceandfire:banner_pattern_mermaid"), CoinType.GOLD, 4, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:banner_pattern_mermaid"), 4, false); })),
		     	 new MerchantProduct(ItemParser.getItemFromName("iceandfire:banner_pattern_sea_serpent"), CoinType.SILVER, 320, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:banner_pattern_sea_serpent"), 320, false); })),
		     	 new MerchantProduct(ItemParser.getItemFromName("iceandfire:banner_pattern_troll"), CoinType.SILVER, 8, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:banner_pattern_troll"), 8, false); })),
		     	 new MerchantProduct(ItemParser.getItemFromName("iceandfire:banner_pattern_weezer"), CoinType.BRONZE, 128, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:banner_pattern_weezer"), 128, false); })),
		     	 new MerchantProduct(ItemParser.getItemFromName("iceandfire:banner_pattern_dread"), CoinType.BRONZE, 128, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:banner_pattern_dread"), 128, false); }))
		);
		
		return INSTANCE.LIST;
	}
	
	public static MerchantSet<MerchantProduct> getSpecialEggs()
	{
		INSTANCE.addAll(  
				new MerchantProduct(Items.DRAGON_EGG, CoinType.GOLD, 40, new ImageButton(5, height, 65, 20 , 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(Items.DRAGON_EGG, 40, false); })), 
			    new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonegg_red"), CoinType.GOLD, 1, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonegg_red"), 1, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonegg_emerald"), CoinType.GOLD, 1, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonegg_emerald"), 1, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonegg_bronze"), CoinType.GOLD, 1, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonegg_bronze"), 1, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonegg_gray"), CoinType.GOLD, 1, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonegg_gray"), 1, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonegg_blue"), CoinType.GOLD, 1, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonegg_blue"), 1, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonegg_white"), CoinType.GOLD, 1, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonegg_white"), 1, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonegg_sapphire"), CoinType.GOLD, 1, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonegg_sapphire"), 1, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonegg_silver"), CoinType.GOLD, 1, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonegg_silver"), 1, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonegg_electric"), CoinType.GOLD, 1, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonegg_electric"), 1, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonegg_amythest"), CoinType.GOLD, 1, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonegg_amythest"), 1, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonegg_copper"), CoinType.GOLD, 1, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonegg_copper"), 1, false); })),
 		     	new MerchantProduct(ItemParser.getItemFromName("iceandfire:dragonegg_black"), CoinType.GOLD, 1, new ImageButton(178, height, 65, 20, 0, 0, 0, BUTTON_TEXTURE, (button) ->{TradeManager.input(ItemParser.getItemFromName("iceandfire:dragonegg_black"), 1, false); }))
		);
		
		return INSTANCE.LIST;
	}

    
    public static final GuildTrades INSTANCE = new GuildTrades();
}
