package mod.arcalitegames.odyssey.world.structure.structures.towers.desert_tower;

import java.util.Objects;

import mod.arcalitegames.odyssey.world.structure.StructureBase;
import mod.arcalitegames.system.parser.EntityParser;
import net.minecraft.block.Blocks;
import net.minecraft.entity.CreatureEntity;
import net.minecraft.util.Direction;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;

public class DesertTower extends StructureBase
{

	public DesertTower(World worldIn, BlockPos origin, int xRange, int yRange, int zRange) 
	{
		super(worldIn, origin, xRange, yRange, zRange);
		DesertTowerComponents.init(world, origin, this);
        this.fillWithBlocks(world, start, -77, 6, -28, -14, 88, 35, Blocks.AIR.getDefaultState());
	}

	@Override
	public void addEntitiesAndSpawn()
	{
	    CreatureEntity vindicator1 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator1, "vindicator");
	    this.spawnEntity(vindicator1, world, 18, 7, 39, start);
	    CreatureEntity vindicator2 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator2, "vindicator");
	    this.spawnEntity(vindicator2, world, 18, 7, 51, start);
	    CreatureEntity vindicator3 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator3, "vindicator");
	    this.spawnEntity(vindicator3, world, 23, 7, 30, start);
	    CreatureEntity vindicator4 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator4, "vindicator");
	    this.spawnEntity(vindicator4, world, 23, 7, 59, start);
	    CreatureEntity pillager5 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager5, "pillager");
	    this.spawnEntity(pillager5, world, 25, 7, 42, start);
	    CreatureEntity pillager6 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager6, "pillager");
	    this.spawnEntity(pillager6, world, 25, 7, 47, start);
	    this.generateChest(world, Direction.EAST, 29, 6, 44, start, 2);
	    CreatureEntity vindicator7 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator7, "vindicator");
	    this.spawnEntity(vindicator7, world, 32, 7, 21, start);
	    CreatureEntity vindicator8 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator8, "vindicator");
	    this.spawnEntity(vindicator8, world, 32, 7, 68, start);
	    CreatureEntity pillager9 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager9, "pillager");
	    this.spawnEntity(pillager9, world, 36, 10, 41, start);
	    CreatureEntity pillager10 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager10, "pillager");
	    this.spawnEntity(pillager10, world, 36, 10, 48, start);
	    this.generateChest(world, Direction.EAST, 37, 21, 47, start, 1);
	    CreatureEntity vindicator11 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator11, "vindicator");
	    this.spawnEntity(vindicator11, world, 39, 20, 38, start);
	    CreatureEntity vindicator12 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator12, "vindicator");
	    this.spawnEntity(vindicator12, world, 39, 20, 52, start);
	    this.generateChest(world, Direction.EAST, 39, 36, 39, start, 1);
	    CreatureEntity evoker13 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:evoker")).create(world);
	    this.setItemsForEntity(evoker13, "evoker");
	    this.spawnEntity(evoker13, world, 40, 43, 51, start);
	    CreatureEntity vindicator14 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator14, "vindicator");
	    this.spawnEntity(vindicator14, world, 41, 7, 16, start);
	    CreatureEntity vindicator15 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator15, "vindicator");
	    this.spawnEntity(vindicator15, world, 41, 7, 75, start);
	    this.generateChest(world, Direction.SOUTH, 41, 28, 37, start, 1);
	    CreatureEntity evoker16 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:evoker")).create(world);
	    this.setItemsForEntity(evoker16, "evoker");
	    this.spawnEntity(evoker16, world, 41, 28, 44, start);
	    CreatureEntity vindicator17 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator17, "vindicator");
	    this.spawnEntity(vindicator17, world, 41, 36, 39, start);
	    CreatureEntity evoker18 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:evoker")).create(world);
	    this.setItemsForEntity(evoker18, "evoker");
	    this.spawnEntity(evoker18, world, 41, 43, 39, start);
	    CreatureEntity evoker19 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:evoker")).create(world);
	    this.setItemsForEntity(evoker19, "evoker");
	    this.spawnEntity(evoker19, world, 42, 10, 40, start);
	    CreatureEntity evoker20 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:evoker")).create(world);
	    this.setItemsForEntity(evoker20, "evoker");
	    this.spawnEntity(evoker20, world, 42, 10, 49, start);
	    CreatureEntity vindicator21 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator21, "vindicator");
	    this.spawnEntity(vindicator21, world, 42, 36, 47, start);
	    CreatureEntity pillager22 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager22, "pillager");
	    this.spawnEntity(pillager22, world, 43, 10, 34, start);
	    CreatureEntity pillager23 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager23, "pillager");
	    this.spawnEntity(pillager23, world, 43, 10, 55, start);
	    CreatureEntity pillager24 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager24, "pillager");
	    this.spawnEntity(pillager24, world, 43, 43, 45, start);
	    CreatureEntity pillager25 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager25, "pillager");
	    this.spawnEntity(pillager25, world, 44, 7, 23, start);
	    CreatureEntity pillager26 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager26, "pillager");
	    this.spawnEntity(pillager26, world, 44, 7, 66, start);
	    this.generateChest(world, Direction.SOUTH, 46, 6, 27, start, 1);
	    this.generateChest(world, Direction.NORTH, 46, 6, 62, start, 1);
	    CreatureEntity evoker27 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:evoker")).create(world);
	    this.setItemsForEntity(evoker27, "evoker");
	    this.spawnEntity(evoker27, world, 46, 28, 50, start);
	    this.generateChest(world, Direction.SOUTH, 46, 50, 42, start, 2);
	    CreatureEntity illusioner28 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:illusioner")).create(world);
	    this.setItemsForEntity(illusioner28, "illusioner");
	    this.spawnEntity(illusioner28, world, 46, 50, 44, start);
	    CreatureEntity evoker29 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:evoker")).create(world);
	    this.setItemsForEntity(evoker29, "evoker");
	    this.spawnEntity(evoker29, world, 47, 28, 39, start);
	    CreatureEntity pillager30 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager30, "pillager");
	    this.spawnEntity(pillager30, world, 47, 36, 40, start);
	    CreatureEntity pillager31 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager31, "pillager");
	    this.spawnEntity(pillager31, world, 47, 36, 49, start);
	    CreatureEntity pillager32 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager32, "pillager");
	    this.spawnEntity(pillager32, world, 47, 43, 41, start);
	    CreatureEntity pillager33 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager33, "pillager");
	    this.spawnEntity(pillager33, world, 49, 7, 23, start);
	    CreatureEntity pillager34 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager34, "pillager");
	    this.spawnEntity(pillager34, world, 49, 7, 66, start);
	    this.generateChest(world, Direction.SOUTH, 49, 21, 35, start, 1);
	    CreatureEntity pillager35 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager35, "pillager");
	    this.spawnEntity(pillager35, world, 50, 10, 34, start);
	    CreatureEntity pillager36 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager36, "pillager");
	    this.spawnEntity(pillager36, world, 50, 10, 55, start);
	    CreatureEntity pillager37 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager37, "pillager");
	    this.spawnEntity(pillager37, world, 50, 43, 45, start);
	    CreatureEntity ravager38 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:ravager")).create(world);
	    this.setItemsForEntity(ravager38, "ravager");
	    this.spawnEntity(ravager38, world, 51, 6, 44, start);
	    CreatureEntity evoker39 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:evoker")).create(world);
	    this.setItemsForEntity(evoker39, "evoker");
	    this.spawnEntity(evoker39, world, 51, 10, 40, start);
	    CreatureEntity evoker40 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:evoker")).create(world);
	    this.setItemsForEntity(evoker40, "evoker");
	    this.spawnEntity(evoker40, world, 51, 36, 44, start);
	    CreatureEntity vindicator41 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator41, "vindicator");
	    this.spawnEntity(vindicator41, world, 52, 7, 75, start);
	    CreatureEntity evoker42 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:evoker")).create(world);
	    this.setItemsForEntity(evoker42, "evoker");
	    this.spawnEntity(evoker42, world, 52, 10, 50, start);
	    CreatureEntity evoker43 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:evoker")).create(world);
	    this.setItemsForEntity(evoker43, "evoker");
	    this.spawnEntity(evoker43, world, 52, 28, 44, start);
	    this.generateChest(world, Direction.NORTH, 52, 36, 52, start, 1);
	    CreatureEntity evoker44 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:evoker")).create(world);
	    this.setItemsForEntity(evoker44, "evoker");
	    this.spawnEntity(evoker44, world, 52, 43, 39, start);
	    CreatureEntity evoker45 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:evoker")).create(world);
	    this.setItemsForEntity(evoker45, "evoker");
	    this.spawnEntity(evoker45, world, 52, 43, 50, start);
	    CreatureEntity vindicator46 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator46, "vindicator");
	    this.spawnEntity(vindicator46, world, 53, 7, 17, start);
	    CreatureEntity pillager47 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager47, "pillager");
	    this.spawnEntity(pillager47, world, 53, 20, 38, start);
	    CreatureEntity vindicator48 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator48, "vindicator");
	    this.spawnEntity(vindicator48, world, 53, 20, 52, start);
	    CreatureEntity pillager49 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager49, "pillager");
	    this.spawnEntity(pillager49, world, 57, 10, 41, start);
	    CreatureEntity pillager50 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager50, "pillager");
	    this.spawnEntity(pillager50, world, 57, 10, 48, start);
	    CreatureEntity vindicator51 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator51, "vindicator");
	    this.spawnEntity(vindicator51, world, 61, 7, 21, start);
	    CreatureEntity vindicator52 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator52, "vindicator");
	    this.spawnEntity(vindicator52, world, 61, 7, 70, start);
	    this.generateChest(world, Direction.WEST, 64, 6, 44, start, 1);
	    CreatureEntity vindicator53 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator53, "vindicator");
	    this.spawnEntity(vindicator53, world, 68, 7, 30, start);
	    CreatureEntity pillager54 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager54, "pillager");
	    this.spawnEntity(pillager54, world, 68, 7, 42, start);
	    CreatureEntity pillager55 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager55, "pillager");
	    this.spawnEntity(pillager55, world, 68, 7, 47, start);
	    CreatureEntity vindicator56 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator56, "vindicator");
	    this.spawnEntity(vindicator56, world, 70, 7, 59, start);
	    CreatureEntity vindicator57 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator57, "vindicator");
	    this.spawnEntity(vindicator57, world, 76, 7, 38, start);
	    CreatureEntity vindicator58 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator58, "vindicator");
	    this.spawnEntity(vindicator58, world, 76, 7, 50, start);
	    this.executeCommand(world);
	}

}
