package mod.arcalitegames.odyssey.world.structure.structures.dungeons.mayan_pyramid;

import java.util.Objects;

import mod.arcalitegames.odyssey.world.structure.StructureBase;
import mod.arcalitegames.system.parser.EntityParser;
import net.minecraft.block.Blocks;
import net.minecraft.entity.CreatureEntity;
import net.minecraft.util.Direction;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;

public class MayanPyramid extends StructureBase
{

	public MayanPyramid(World worldIn, BlockPos origin, int xRange, int yRange, int zRange)
	{
		super(worldIn, origin, xRange, yRange, zRange);
		PyramidComponent0.init(world, origin, this);
		PyramidComponent1.init(world, origin, this);
		PyramidComponent2.init(world, origin, this);
		PyramidComponent3.init(world, origin, this);
		PyramidComponent4.init(world, origin, this);
		PyramidComponent5.init(world, origin, this);
		PyramidComponent6.init(world, origin, this);
		PyramidComponent7.init(world, origin, this);
		PyramidComponent8.init(world, origin, this);
        this.fillWithBlocks(world, start, 26, 7, 18, 82, 41, 76, Blocks.AIR.getDefaultState());
	}

	@Override
	public void addEntitiesAndSpawn()
	{
	    this.generateChest(world, Direction.EAST, -25, -24, 46, start, 1);
	    this.generateChest(world, Direction.SOUTH, -20, -24, 41, start, 1);
	    CreatureEntity dread_knight1 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight1, "dread_knight");
	    this.spawnEntity(dread_knight1, world, -20, -24, 44, start);
	    CreatureEntity dread_knight2 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight2, "dread_knight");
	    this.spawnEntity(dread_knight2, world, -20, -24, 48, start);
	    this.generateChest(world, Direction.NORTH, -20, -24, 51, start, 1);
	    this.generateChest(world, Direction.EAST, -7, -14, 46, start, 1);
	    this.generateChest(world, Direction.EAST, -4, -43, 16, start, 3);
	    this.generateChest(world, Direction.EAST, -4, -24, 16, start, 2);
	    this.generateChest(world, Direction.EAST, -3, -24, 96, start, 2);
	    this.generateChest(world, Direction.SOUTH, -2, -14, 41, start, 1);
	    this.generateChest(world, Direction.NORTH, -2, -14, 51, start, 1);
	    this.generateChest(world, Direction.EAST, -2, -13, 46, start, 2);
	    CreatureEntity dread_knight3 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight3, "dread_knight");
	    this.spawnEntity(dread_knight3, world, 0, -34, -24, start);
	    CreatureEntity dread_knight4 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight4, "dread_knight");
	    this.spawnEntity(dread_knight4, world, 0, -34, -12, start);
	    this.generateChest(world, Direction.SOUTH, 1, -24, 11, start, 1);
	    CreatureEntity dread_lich5 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich5, "dread_lich");
	    this.spawnEntity(dread_lich5, world, 1, -24, 16, start);
	    this.generateChest(world, Direction.NORTH, 1, -24, 21, start, 1);
	    CreatureEntity dread_thrall6 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall6, "dread_thrall");
	    this.spawnEntity(dread_thrall6, world, 2, -24, 78, start);
	    this.generateChest(world, Direction.NORTH, 2, -24, 101, start, 2);
	    CreatureEntity dread_knight7 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight7, "dread_knight");
	    this.spawnEntity(dread_knight7, world, 4, -54, 12, start);
	    CreatureEntity dread_lich8 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich8, "dread_lich");
	    this.spawnEntity(dread_lich8, world, 6, -44, 10, start);
	    CreatureEntity dread_lich9 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich9, "dread_lich");
	    this.spawnEntity(dread_lich9, world, 6, -34, -18, start);
	    CreatureEntity dread_beast10 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_beast")).create(world);
	    this.setItemsForEntity(dread_beast10, "dread_beast");
	    this.spawnEntity(dread_beast10, world, 6, -34, 33, start);
	    this.generateChest(world, Direction.WEST, 7, -24, 96, start, 2);
	    this.generateChest(world, Direction.SOUTH, 10, -54, 6, start, 2);
	    this.generateChest(world, Direction.NORTH, 10, -54, 18, start, 2);
	    CreatureEntity dread_lich11 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich11, "dread_lich");
	    this.spawnEntity(dread_lich11, world, 10, -44, 28, start);
	    CreatureEntity dread_knight12 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight12, "dread_knight");
	    this.spawnEntity(dread_knight12, world, 12, -34, -24, start);
	    CreatureEntity dread_knight13 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight13, "dread_knight");
	    this.spawnEntity(dread_knight13, world, 12, -34, -12, start);
	    CreatureEntity dread_thrall14 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall14, "dread_thrall");
	    this.spawnEntity(dread_thrall14, world, 17, -34, 5, start);
	    this.generateChest(world, Direction.EAST, 17, -24, -11, start, 1);
	    CreatureEntity dread_thrall15 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall15, "dread_thrall");
	    this.spawnEntity(dread_thrall15, world, 17, -14, 39, start);
	    CreatureEntity dread_lich16 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich16, "dread_lich");
	    this.spawnEntity(dread_lich16, world, 17, -14, 46, start);
	    CreatureEntity dread_thrall17 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall17, "dread_thrall");
	    this.spawnEntity(dread_thrall17, world, 17, -14, 53, start);
	    CreatureEntity dread_knight18 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight18, "dread_knight");
	    this.spawnEntity(dread_knight18, world, 18, -44, 10, start);
	    CreatureEntity dread_knight19 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight19, "dread_knight");
	    this.spawnEntity(dread_knight19, world, 18, -44, 22, start);
	    CreatureEntity dread_lich20 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich20, "dread_lich");
	    this.spawnEntity(dread_lich20, world, 22, -34, 33, start);
	    this.generateChest(world, Direction.SOUTH, 22, -24, -16, start, 2);
	    CreatureEntity dread_lich21 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich21, "dread_lich");
	    this.spawnEntity(dread_lich21, world, 22, -24, -11, start);
	    CreatureEntity dread_lich22 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich22, "dread_lich");
	    this.spawnEntity(dread_lich22, world, 22, -24, 16, start);
	    CreatureEntity dread_lich23 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich23, "dread_lich");
	    this.spawnEntity(dread_lich23, world, 22, -24, 46, start);
	    CreatureEntity dread_beast24 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_beast")).create(world);
	    this.setItemsForEntity(dread_beast24, "dread_beast");
	    this.spawnEntity(dread_beast24, world, 22, -24, 78, start);
	    CreatureEntity dread_knight25 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight25, "dread_knight");
	    this.spawnEntity(dread_knight25, world, 23, -34, -1, start);
	    CreatureEntity dread_ghoul26 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul26, "dread_ghoul");
	    this.spawnEntity(dread_ghoul26, world, 23, -34, 16, start);
	    this.generateChest(world, Direction.WEST, 23, -33, -18, start, 3);
	    this.generateChest(world, Direction.EAST, 26, -54, -14, start, 2);
	    this.generateChest(world, Direction.WEST, 27, -24, -11, start, 1);
	    CreatureEntity goblin_knocker27 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_knocker")).create(world);
	    this.setItemsForEntity(goblin_knocker27, "goblin_knocker");
	    this.spawnEntity(goblin_knocker27, world, 27, 8, 44, start);
	    CreatureEntity goblin_knocker28 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_knocker")).create(world);
	    this.setItemsForEntity(goblin_knocker28, "goblin_knocker");
	    this.spawnEntity(goblin_knocker28, world, 27, 8, 50, start);
	    CreatureEntity dread_thrall29 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall29, "dread_thrall");
	    this.spawnEntity(dread_thrall29, world, 29, -34, -7, start);
	    CreatureEntity dread_lich30 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich30, "dread_lich");
	    this.spawnEntity(dread_lich30, world, 29, -34, -1, start);
	    CreatureEntity dread_ghoul31 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul31, "dread_ghoul");
	    this.spawnEntity(dread_ghoul31, world, 29, -34, 5, start);
	    CreatureEntity dread_knight32 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight32, "dread_knight");
	    this.spawnEntity(dread_knight32, world, 30, -44, 42, start);
	    CreatureEntity dread_thrall33 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall33, "dread_thrall");
	    this.spawnEntity(dread_thrall33, world, 30, -44, 43, start);
	    CreatureEntity dread_knight34 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight34, "dread_knight");
	    this.spawnEntity(dread_knight34, world, 30, -44, 44, start);
	    this.generateChest(world, Direction.EAST, 33, -57, 51, start, 3);
	    CreatureEntity dread_lich35 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich35, "dread_lich");
	    this.spawnEntity(dread_lich35, world, 33, -56, 51, start);
	    this.generateChest(world, Direction.EAST, 33, -34, 33, start, 1);
	    this.generateChest(world, Direction.EAST, 33, -24, 106, start, 1);
	    this.generateChest(world, Direction.EAST, 33, -14, 16, start, 1);
	    this.generateChest(world, Direction.EAST, 33, -13, 77, start, 1);
	    this.generateChest(world, Direction.EAST, 34, -44, 6, start, 1);
	    CreatureEntity dread_thrall36 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall36, "dread_thrall");
	    this.spawnEntity(dread_thrall36, world, 34, -44, 22, start);
	    this.generateChest(world, Direction.EAST, 35, -43, -14, start, 1);
	    CreatureEntity dread_knight37 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight37, "dread_knight");
	    this.spawnEntity(dread_knight37, world, 37, -14, 91, start);
	    this.generateChest(world, Direction.NORTH, 37, -13, 98, start, 2);
	    CreatureEntity dread_ghoul38 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul38, "dread_ghoul");
	    this.spawnEntity(dread_ghoul38, world, 38, -24, 54, start);
	    CreatureEntity dread_ghoul39 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul39, "dread_ghoul");
	    this.spawnEntity(dread_ghoul39, world, 38, -24, 76, start);
	    CreatureEntity dread_lich40 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich40, "dread_lich");
	    this.spawnEntity(dread_lich40, world, 38, -24, 106, start);
	    this.generateChest(world, Direction.NORTH, 38, -24, 111, start, 2);
	    this.generateChest(world, Direction.SOUTH, 38, -14, 11, start, 1);
	    CreatureEntity dread_knight41 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight41, "dread_knight");
	    this.spawnEntity(dread_knight41, world, 38, -14, 16, start);
	    CreatureEntity dread_knight42 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight42, "dread_knight");
	    this.spawnEntity(dread_knight42, world, 39, -44, 55, start);
	    CreatureEntity dread_lich43 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich43, "dread_lich");
	    this.spawnEntity(dread_lich43, world, 40, -44, 6, start);
	    CreatureEntity dread_thrall44 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall44, "dread_thrall");
	    this.spawnEntity(dread_thrall44, world, 40, -44, 55, start);
	    this.generateChest(world, Direction.SOUTH, 40, -43, 0, start, 2);
	    CreatureEntity dread_beast45 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_beast")).create(world);
	    this.setItemsForEntity(dread_beast45, "dread_beast");
	    this.spawnEntity(dread_beast45, world, 40, -34, -15, start);
	    CreatureEntity dread_lich46 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich46, "dread_lich");
	    this.spawnEntity(dread_lich46, world, 40, -34, 33, start);
	    this.generateChest(world, Direction.NORTH, 40, -34, 40, start, 1);
	    CreatureEntity dread_lich47 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich47, "dread_lich");
	    this.spawnEntity(dread_lich47, world, 41, -54, -19, start);
	    CreatureEntity dread_beast48 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_beast")).create(world);
	    this.setItemsForEntity(dread_beast48, "dread_beast");
	    this.spawnEntity(dread_beast48, world, 41, -54, 12, start);
	    CreatureEntity dread_knight49 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight49, "dread_knight");
	    this.spawnEntity(dread_knight49, world, 41, -44, 55, start);
	    CreatureEntity dread_knight50 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight50, "dread_knight");
	    this.spawnEntity(dread_knight50, world, 43, -44, -14, start);
	    this.generateChest(world, Direction.WEST, 43, -24, 106, start, 1);
	    this.generateChest(world, Direction.WEST, 43, -14, 16, start, 1);
	    this.generateChest(world, Direction.WEST, 46, -44, 6, start, 1);
	    CreatureEntity dread_knight51 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight51, "dread_knight");
	    this.spawnEntity(dread_knight51, world, 46, -44, 22, start);
	    CreatureEntity dread_knight52 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight52, "dread_knight");
	    this.spawnEntity(dread_knight52, world, 46, -44, 34, start);
	    CreatureEntity dread_knight53 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight53, "dread_knight");
	    this.spawnEntity(dread_knight53, world, 46, -44, 49, start);
	    CreatureEntity hobgoblin54 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_hobgoblin")).create(world);
	    this.setItemsForEntity(hobgoblin54, "hobgoblin");
	    this.spawnEntity(hobgoblin54, world, 47, 27, 47, start);
	    CreatureEntity dread_knight55 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight55, "dread_knight");
	    this.spawnEntity(dread_knight55, world, 49, -24, 35, start);
	    this.generateChest(world, Direction.SOUTH, 49, -23, 30, start, 2);
	    this.generateChest(world, Direction.EAST, 49, -14, 97, start, 1);
	    CreatureEntity dread_thrall56 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall56, "dread_thrall");
	    this.spawnEntity(dread_thrall56, world, 50, -44, -34, start);
	    CreatureEntity dread_knight57 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight57, "dread_knight");
	    this.spawnEntity(dread_knight57, world, 51, -44, 44, start);
	    CreatureEntity dread_knight58 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight58, "dread_knight");
	    this.spawnEntity(dread_knight58, world, 51, -44, 56, start);
	    CreatureEntity dread_ghoul59 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul59, "dread_ghoul");
	    this.spawnEntity(dread_ghoul59, world, 51, -34, 27, start);
	    CreatureEntity dread_ghoul60 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul60, "dread_ghoul");
	    this.spawnEntity(dread_ghoul60, world, 51, -34, 39, start);
	    CreatureEntity goblin_knocker61 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_knocker")).create(world);
	    this.setItemsForEntity(goblin_knocker61, "goblin_knocker");
	    this.spawnEntity(goblin_knocker61, world, 51, 8, 20, start);
	    CreatureEntity goblin_knocker62 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_knocker")).create(world);
	    this.setItemsForEntity(goblin_knocker62, "goblin_knocker");
	    this.spawnEntity(goblin_knocker62, world, 51, 8, 75, start);
	    this.generateChest(world, Direction.NORTH, 52, 27, 48, start, 1);
	    this.generateChest(world, Direction.EAST, 53, -43, -2, start, 1);
	    CreatureEntity dread_knight63 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight63, "dread_knight");
	    this.spawnEntity(dread_knight63, world, 53, -34, -22, start);
	    CreatureEntity dread_knight64 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight64, "dread_knight");
	    this.spawnEntity(dread_knight64, world, 53, -34, -14, start);
	    CreatureEntity dread_ghoul65 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul65, "dread_ghoul");
	    this.spawnEntity(dread_ghoul65, world, 54, -14, 77, start);
	    this.generateChest(world, Direction.NORTH, 54, -14, 102, start, 1);
	    CreatureEntity goblin_knocker66 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_knocker")).create(world);
	    this.setItemsForEntity(goblin_knocker66, "goblin_knocker");
	    this.spawnEntity(goblin_knocker66, world, 54, 8, 64, start);
	    CreatureEntity hobgoblin67 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_hobgoblin")).create(world);
	    this.setItemsForEntity(hobgoblin67, "hobgoblin");
	    this.spawnEntity(hobgoblin67, world, 54, 19, 49, start);
	    CreatureEntity hobgoblin68 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_hobgoblin")).create(world);
	    this.setItemsForEntity(hobgoblin68, "hobgoblin");
	    this.spawnEntity(hobgoblin68, world, 54, 27, 40, start);
	    CreatureEntity hobgoblin69 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_hobgoblin")).create(world);
	    this.setItemsForEntity(hobgoblin69, "hobgoblin");
	    this.spawnEntity(hobgoblin69, world, 54, 27, 53, start);
	    this.generateChest(world, Direction.EAST, 56, -24, 1, start, 1);
	    this.generateChest(world, Direction.EAST, 56, -24, 78, start, 1);
	    this.generateChest(world, Direction.EAST, 56, -24, 98, start, 1);
	    this.generateChest(world, Direction.NORTH, 56, 27, 48, start, 1);
	    CreatureEntity dread_knight70 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight70, "dread_knight");
	    this.spawnEntity(dread_knight70, world, 57, -44, 10, start);
	    CreatureEntity dread_lich71 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich71, "dread_lich");
	    this.spawnEntity(dread_lich71, world, 57, -44, 68, start);
	    this.generateChest(world, Direction.SOUTH, 57, -43, -40, start, 2);
	    this.generateChest(world, Direction.SOUTH, 57, -33, -18, start, 3);
	    this.generateChest(world, Direction.WEST, 57, -33, 33, start, 2);
	    CreatureEntity goblin_knocker72 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_knocker")).create(world);
	    this.setItemsForEntity(goblin_knocker72, "goblin_knocker");
	    this.spawnEntity(goblin_knocker72, world, 57, 8, 20, start);
	    CreatureEntity goblin_knocker73 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_knocker")).create(world);
	    this.setItemsForEntity(goblin_knocker73, "goblin_knocker");
	    this.spawnEntity(goblin_knocker73, world, 57, 8, 75, start);
	    this.generateChest(world, Direction.WEST, 59, -14, 97, start, 1);
	    CreatureEntity hobgoblin74 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_hobgoblin")).create(world);
	    this.setItemsForEntity(hobgoblin74, "hobgoblin");
	    this.spawnEntity(hobgoblin74, world, 60, 27, 47, start);
	    CreatureEntity dread_knight75 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight75, "dread_knight");
	    this.spawnEntity(dread_knight75, world, 61, -34, -22, start);
	    CreatureEntity dread_knight76 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight76, "dread_knight");
	    this.spawnEntity(dread_knight76, world, 61, -34, -14, start);
	    this.generateChest(world, Direction.SOUTH, 61, -24, -4, start, 1);
	    CreatureEntity dread_knight77 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight77, "dread_knight");
	    this.spawnEntity(dread_knight77, world, 61, -24, 1, start);
	    CreatureEntity dread_beast78 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_beast")).create(world);
	    this.setItemsForEntity(dread_beast78, "dread_beast");
	    this.spawnEntity(dread_beast78, world, 61, -24, 46, start);
	    CreatureEntity dread_ghoul79 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul79, "dread_ghoul");
	    this.spawnEntity(dread_ghoul79, world, 61, -24, 78, start);
	    CreatureEntity dread_thrall80 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall80, "dread_thrall");
	    this.spawnEntity(dread_thrall80, world, 61, -24, 98, start);
	    this.generateChest(world, Direction.NORTH, 61, -24, 103, start, 1);
	    CreatureEntity dread_thrall81 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall81, "dread_thrall");
	    this.spawnEntity(dread_thrall81, world, 63, -44, 44, start);
	    CreatureEntity dread_knight82 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight82, "dread_knight");
	    this.spawnEntity(dread_knight82, world, 63, -44, 56, start);
	    CreatureEntity dread_thrall83 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall83, "dread_thrall");
	    this.spawnEntity(dread_thrall83, world, 64, -44, -34, start);
	    CreatureEntity dread_thrall84 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall84, "dread_thrall");
	    this.spawnEntity(dread_thrall84, world, 64, -44, 22, start);
	    CreatureEntity dread_knight85 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight85, "dread_knight");
	    this.spawnEntity(dread_knight85, world, 64, -44, 34, start);
	    CreatureEntity dread_knight86 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight86, "dread_knight");
	    this.spawnEntity(dread_knight86, world, 66, -57, 47, start);
	    CreatureEntity dread_knight87 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight87, "dread_knight");
	    this.spawnEntity(dread_knight87, world, 66, -57, 55, start);
	    this.generateChest(world, Direction.WEST, 66, -24, 1, start, 1);
	    this.generateChest(world, Direction.WEST, 66, -24, 98, start, 1);
	    this.generateChest(world, Direction.SOUTH, 67, -44, -18, start, 2);
	    this.generateChest(world, Direction.SOUTH, 70, -56, -48, start, 3);
	    CreatureEntity dread_beast88 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_beast")).create(world);
	    this.setItemsForEntity(dread_beast88, "dread_beast");
	    this.spawnEntity(dread_beast88, world, 70, -55, -48, start);
	    CreatureEntity dread_thrall89 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall89, "dread_thrall");
	    this.spawnEntity(dread_thrall89, world, 70, -54, -14, start);
	    CreatureEntity dread_ghoul90 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul90, "dread_ghoul");
	    this.spawnEntity(dread_ghoul90, world, 70, -54, 4, start);
	    CreatureEntity dread_ghoul91 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul91, "dread_ghoul");
	    this.spawnEntity(dread_ghoul91, world, 70, -54, 20, start);
	    CreatureEntity dread_thrall93 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall93, "dread_thrall");
	    this.spawnEntity(dread_thrall93, world, 70, -54, 73, start);
	    this.generateChest(world, Direction.NORTH, 70, -54, 79, start, 3);
	    CreatureEntity dread_knight94 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight94, "dread_knight");
	    this.spawnEntity(dread_knight94, world, 70, -44, 57, start);
	    this.generateChest(world, Direction.NORTH, 70, -43, 58, start, 2);
	    CreatureEntity dread_knight95 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight95, "dread_knight");
	    this.spawnEntity(dread_knight95, world, 74, -57, 47, start);
	    CreatureEntity dread_knight96 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight96, "dread_knight");
	    this.spawnEntity(dread_knight96, world, 74, -57, 55, start);
	    CreatureEntity dread_knight97 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight97, "dread_knight");
	    this.spawnEntity(dread_knight97, world, 76, -44, 22, start);
	    CreatureEntity dread_thrall98 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall98, "dread_thrall");
	    this.spawnEntity(dread_thrall98, world, 76, -44, 34, start);
	    CreatureEntity dread_ghoul99 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul99, "dread_ghoul");
	    this.spawnEntity(dread_ghoul99, world, 79, -14, 46, start);
	    CreatureEntity goblin_knocker100 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_knocker")).create(world);
	    this.setItemsForEntity(goblin_knocker100, "goblin_knocker");
	    this.spawnEntity(goblin_knocker100, world, 82, 8, 44, start);
	    CreatureEntity goblin_knocker101 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_knocker")).create(world);
	    this.setItemsForEntity(goblin_knocker101, "goblin_knocker");
	    this.spawnEntity(goblin_knocker101, world, 82, 8, 50, start);
	    CreatureEntity dread_knight102 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight102, "dread_knight");
	    this.spawnEntity(dread_knight102, world, 83, -44, 49, start);
	    CreatureEntity dread_thrall103 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall103, "dread_thrall");
	    this.spawnEntity(dread_thrall103, world, 83, -44, 50, start);
	    CreatureEntity dread_knight104 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight104, "dread_knight");
	    this.spawnEntity(dread_knight104, world, 83, -44, 51, start);
	    CreatureEntity dread_beast105 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_beast")).create(world);
	    this.setItemsForEntity(dread_beast105, "dread_beast");
	    this.spawnEntity(dread_beast105, world, 86, -44, -14, start);
	    CreatureEntity dread_knight106 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight106, "dread_knight");
	    this.spawnEntity(dread_knight106, world, 86, -24, 28, start);
	    CreatureEntity dread_lich107 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich107, "dread_lich");
	    this.spawnEntity(dread_lich107, world, 86, -24, 46, start);
	    this.generateChest(world, Direction.SOUTH, 86, -23, 20, start, 2);
	    this.generateChest(world, Direction.WEST, 92, -57, 51, start, 3);
	    CreatureEntity dread_beast108 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_beast")).create(world);
	    this.setItemsForEntity(dread_beast108, "dread_beast");
	    this.spawnEntity(dread_beast108, world, 92, -54, 72, start);
	    this.generateChest(world, Direction.SOUTH, 92, -24, 73, start, 1);
	    CreatureEntity dread_thrall109 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall109, "dread_thrall");
	    this.spawnEntity(dread_thrall109, world, 92, -24, 78, start);
	    this.generateChest(world, Direction.NORTH, 92, -24, 83, start, 1);
	    this.generateChest(world, Direction.WEST, 97, -24, 78, start, 1);
	    this.generateChest(world, Direction.SOUTH, 98, -44, 22, start, 2);
	    CreatureEntity dread_knight110 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight110, "dread_knight");
	    this.spawnEntity(dread_knight110, world, 98, -44, 27, start);
	    CreatureEntity dread_lich111 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich111, "dread_lich");
	    this.spawnEntity(dread_lich111, world, 98, -44, 28, start);
	    CreatureEntity dread_knight112 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight112, "dread_knight");
	    this.spawnEntity(dread_knight112, world, 98, -44, 29, start);
	    this.generateChest(world, Direction.NORTH, 98, -44, 34, start, 2);
	    CreatureEntity dread_ghoul113 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul113, "dread_ghoul");
	    this.spawnEntity(dread_ghoul113, world, 104, -54, -16, start);
	    CreatureEntity dread_ghoul114 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul114, "dread_ghoul");
	    this.spawnEntity(dread_ghoul114, world, 104, -54, -12, start);
	    this.generateChest(world, Direction.WEST, 104, -44, 28, start, 2);
	    CreatureEntity dread_knight115 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight115, "dread_knight");
	    this.spawnEntity(dread_knight115, world, 109, -24, 46, start);
	    this.generateChest(world, Direction.SOUTH, 112, -14, 41, start, 1);
	    CreatureEntity dread_thrall116 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall116, "dread_thrall");
	    this.spawnEntity(dread_thrall116, world, 112, -14, 44, start);
	    CreatureEntity dread_thrall117 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall117, "dread_thrall");
	    this.spawnEntity(dread_thrall117, world, 112, -14, 48, start);
	    this.generateChest(world, Direction.NORTH, 112, -14, 51, start, 1);
	    this.generateChest(world, Direction.WEST, 115, -23, 46, start, 2);
	    this.generateChest(world, Direction.WEST, 117, -14, 46, start, 1);
	    CreatureEntity dread_lich118 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich118, "dread_lich");
	    this.spawnEntity(dread_lich118, world, 122, -54, -14, start);
	    this.executeCommand(world);
	}

}
