package mod.arcalitegames.odyssey.world.structure.structures.dungeons.shrine;

import java.util.Objects;

import mod.arcalitegames.odyssey.world.structure.StructureBase;
import mod.arcalitegames.system.parser.EntityParser;
import net.minecraft.block.Blocks;
import net.minecraft.entity.CreatureEntity;
import net.minecraft.util.Direction;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;

public class DesertShrine extends StructureBase
{

	public DesertShrine(World worldIn, BlockPos origin, int xRange, int yRange, int zRange)
	{
		super(worldIn, origin, xRange, yRange, zRange);
		ShrineComponent0.init(world, origin, this);
		ShrineComponent1.init(world, origin, this);
		ShrineComponent2.init(world, origin, this);
		ShrineComponent3.init(world, origin, this);
		ShrineComponent4.init(world, origin, this);
        this.fillWithBlocks(world, start, 21, 8, 14, 114, 75, 142, Blocks.AIR.getDefaultState());
	}

	@Override
	public void addEntitiesAndSpawn()
	{
	    this.generateChest(world, Direction.EAST, -23, -49, 48, start, 3);
	    this.generateChest(world, Direction.EAST, -20, -39, 48, start, 3);
	    CreatureEntity skeleton1 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton1, "skeleton");
	    this.spawnEntity(skeleton1, world, -18, -40, 48, start);
	    CreatureEntity skeleton2 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton2, "skeleton");
	    this.spawnEntity(skeleton2, world, -16, -40, 43, start);
	    CreatureEntity skeleton3 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton3, "skeleton");
	    this.spawnEntity(skeleton3, world, -16, -40, 53, start);
	    this.generateChest(world, Direction.EAST, -15, -28, 20, start, 1);
	    this.generateChest(world, Direction.EAST, -15, -28, 42, start, 1);
	    CreatureEntity skeleton4 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton4, "skeleton");
	    this.spawnEntity(skeleton4, world, -14, -29, 42, start);
	    CreatureEntity troll5 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:troll")).create(world);
	    this.setItemsForEntity(troll5, "troll");
	    this.spawnEntity(troll5, world, -13, -49, 48, start);
	    CreatureEntity skeleton6 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton6, "skeleton");
	    this.spawnEntity(skeleton6, world, -13, -29, 25, start);
	    this.generateChest(world, Direction.EAST, -12, -18, 48, start, 2);
	    CreatureEntity skeleton7 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton7, "skeleton");
	    this.spawnEntity(skeleton7, world, -10, -40, 43, start);
	    CreatureEntity skeleton8 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton8, "skeleton");
	    this.spawnEntity(skeleton8, world, -10, -40, 53, start);
	    CreatureEntity zombie9 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie9, "zombie");
	    this.spawnEntity(zombie9, world, -7, -29, 37, start);
	    this.generateChest(world, Direction.NORTH, -7, -28, 48, start, 2);
	    this.generateChest(world, Direction.EAST, -7, -28, 65, start, 2);
	    CreatureEntity skeleton10 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton10, "skeleton");
	    this.spawnEntity(skeleton10, world, -7, -19, 48, start);
	    this.generateChest(world, Direction.EAST, -6, -39, 31, start, 1);
	    CreatureEntity skeleton11 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton11, "skeleton");
	    this.spawnEntity(skeleton11, world, -6, -39, 48, start);
	    CreatureEntity zombie12 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie12, "zombie");
	    this.spawnEntity(zombie12, world, -6, -29, 14, start);
	    CreatureEntity zombie13 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie13, "zombie");
	    this.spawnEntity(zombie13, world, -4, -29, 17, start);
	    CreatureEntity zombie14 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie14, "zombie");
	    this.spawnEntity(zombie14, world, -4, -29, 65, start);
	    CreatureEntity skeleton15 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton15, "skeleton");
	    this.spawnEntity(skeleton15, world, -3, -40, 62, start);
	    CreatureEntity skeleton16 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton16, "skeleton");
	    this.spawnEntity(skeleton16, world, -3, -40, 68, start);
	    CreatureEntity skeleton17 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton17, "skeleton");
	    this.spawnEntity(skeleton17, world, -1, -29, 25, start);
	    CreatureEntity zombie18 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie18, "zombie");
	    this.spawnEntity(zombie18, world, -1, -29, 31, start);
	    this.generateChest(world, Direction.SOUTH, -1, -28, 6, start, 1);
	    this.generateChest(world, Direction.SOUTH, -1, -28, 57, start, 1);
	    this.generateChest(world, Direction.NORTH, -1, -28, 73, start, 1);
	    CreatureEntity zombie19 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie19, "zombie");
	    this.spawnEntity(zombie19, world, 0, -39, 31, start);
	    CreatureEntity skeleton20 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton20, "skeleton");
	    this.spawnEntity(skeleton20, world, 1, -40, 69, start);
	    this.generateChest(world, Direction.SOUTH, 1, -39, 24, start, 1);
	    CreatureEntity zombie21 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie21, "zombie");
	    this.spawnEntity(zombie21, world, 1, -39, 30, start);
	    CreatureEntity zombie22 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie22, "zombie");
	    this.spawnEntity(zombie22, world, 1, -39, 31, start);
	    CreatureEntity zombie23 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie23, "zombie");
	    this.spawnEntity(zombie23, world, 1, -39, 32, start);
	    CreatureEntity skeleton24 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton24, "skeleton");
	    this.spawnEntity(skeleton24, world, 1, -39, 57, start);
	    this.generateChest(world, Direction.NORTH, 1, -39, 72, start, 3);
	    this.generateChest(world, Direction.WEST, 1, -28, 42, start, 1);
	    CreatureEntity zombie25 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie25, "zombie");
	    this.spawnEntity(zombie25, world, 2, -39, 31, start);
	    CreatureEntity skeleton26 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton26, "skeleton");
	    this.spawnEntity(skeleton26, world, 5, -40, 62, start);
	    CreatureEntity skeleton27 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton27, "skeleton");
	    this.spawnEntity(skeleton27, world, 5, -40, 68, start);
	    CreatureEntity zombie28 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie28, "zombie");
	    this.spawnEntity(zombie28, world, 6, -19, 46, start);
	    CreatureEntity zombie29 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie29, "zombie");
	    this.spawnEntity(zombie29, world, 6, -19, 50, start);
	    this.generateChest(world, Direction.EAST, 6, -18, 31, start, 1);
	    CreatureEntity skeleton30 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton30, "skeleton");
	    this.spawnEntity(skeleton30, world, 7, -19, 73, start);
	    this.generateChest(world, Direction.NORTH, 7, -18, 78, start, 1);
	    this.generateChest(world, Direction.WEST, 8, -39, 31, start, 1);
	    CreatureEntity skeleton31 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton31, "skeleton");
	    this.spawnEntity(skeleton31, world, 8, -29, 60, start);
	    CreatureEntity zombie32 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie32, "zombie");
	    this.spawnEntity(zombie32, world, 8, -19, 31, start);
	    CreatureEntity husk33 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk33, "husk");
	    this.spawnEntity(husk33, world, 10, -29, 38, start);
	    CreatureEntity husk34 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk34, "husk");
	    this.spawnEntity(husk34, world, 10, -19, 46, start);
	    CreatureEntity husk35 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk35, "husk");
	    this.spawnEntity(husk35, world, 10, -19, 50, start);
	    CreatureEntity skeleton36 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton36, "skeleton");
	    this.spawnEntity(skeleton36, world, 11, -39, 48, start);
	    CreatureEntity skeleton37 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton37, "skeleton");
	    this.spawnEntity(skeleton37, world, 12, -29, 60, start);
	    this.generateChest(world, Direction.EAST, 18, -49, 82, start, 2);
	    CreatureEntity skeleton38 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton38, "skeleton");
	    this.spawnEntity(skeleton38, world, 20, -9, 46, start);
	    CreatureEntity skeleton39 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton39, "skeleton");
	    this.spawnEntity(skeleton39, world, 20, -9, 50, start);
	    this.generateChest(world, Direction.EAST, 20, -8, 48, start, 2);
	    CreatureEntity skeleton40 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton40, "skeleton");
	    this.spawnEntity(skeleton40, world, 21, -29, 58, start);
	    CreatureEntity skeleton41 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton41, "skeleton");
	    this.spawnEntity(skeleton41, world, 21, -29, 72, start);
	    this.generateChest(world, Direction.SOUTH, 21, -28, 57, start, 1);
	    this.generateChest(world, Direction.NORTH, 21, -28, 73, start, 1);
	    this.generateChest(world, Direction.EAST, 22, -38, 26, start, 1);
	    CreatureEntity zombie42 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie42, "zombie");
	    this.spawnEntity(zombie42, world, 22, -29, 14, start);
	    CreatureEntity zombie43 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie43, "zombie");
	    this.spawnEntity(zombie43, world, 23, -39, 26, start);
	    CreatureEntity troll44 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:troll")).create(world);
	    this.setItemsForEntity(troll44, "troll");
	    this.spawnEntity(troll44, world, 25, -49, 48, start);
	    CreatureEntity troll45 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:troll")).create(world);
	    this.setItemsForEntity(troll45, "troll");
	    this.spawnEntity(troll45, world, 25, -49, 81, start);
	    this.generateChest(world, Direction.NORTH, 25, -49, 89, start, 2);
	    this.generateChest(world, Direction.SOUTH, 25, -48, 31, start, 3);
	    CreatureEntity skeleton46 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton46, "skeleton");
	    this.spawnEntity(skeleton46, world, 27, -29, 8, start);
	    CreatureEntity husk47 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk47, "husk");
	    this.spawnEntity(husk47, world, 27, -29, 31, start);
	    CreatureEntity skeleton48 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton48, "skeleton");
	    this.spawnEntity(skeleton48, world, 27, -19, 31, start);
	    CreatureEntity skeleton49 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton49, "skeleton");
	    this.spawnEntity(skeleton49, world, 27, -19, 83, start);
	    this.generateChest(world, Direction.NORTH, 27, -18, 85, start, 1);
	    CreatureEntity skeleton50 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton50, "skeleton");
	    this.spawnEntity(skeleton50, world, 30, -39, 92, start);
	    this.generateChest(world, Direction.SOUTH, 30, -38, 20, start, 2);
	    this.generateChest(world, Direction.NORTH, 30, -38, 93, start, 1);
	    this.generateChest(world, Direction.WEST, 32, -49, 82, start, 2);
	    CreatureEntity zombie51 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie51, "zombie");
	    this.spawnEntity(zombie51, world, 32, -29, 14, start);
	    CreatureEntity husk52 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk52, "husk");
	    this.spawnEntity(husk52, world, 33, -29, 60, start);
	    CreatureEntity husk53 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk53, "husk");
	    this.spawnEntity(husk53, world, 33, -29, 63, start);
	    CreatureEntity husk54 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk54, "husk");
	    this.spawnEntity(husk54, world, 33, -29, 67, start);
	    CreatureEntity husk55 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk55, "husk");
	    this.spawnEntity(husk55, world, 33, -29, 70, start);
	    this.generateChest(world, Direction.SOUTH, 33, -28, 57, start, 1);
	    this.generateChest(world, Direction.NORTH, 33, -28, 73, start, 1);
	    CreatureEntity vindicator56 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator56, "vindicator");
	    this.spawnEntity(vindicator56, world, 33, 9, 107, start);
	    CreatureEntity vindicator57 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator57, "vindicator");
	    this.spawnEntity(vindicator57, world, 34, 9, 89, start);
	    CreatureEntity evoker58 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:evoker")).create(world);
	    this.setItemsForEntity(evoker58, "evoker");
	    this.spawnEntity(evoker58, world, 34, 9, 114, start);
	    this.generateChest(world, Direction.EAST, 36, -49, 75, start, 2);
	    CreatureEntity zombie59 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie59, "zombie");
	    this.spawnEntity(zombie59, world, 36, -39, 64, start);
	    CreatureEntity zombie60 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie60, "zombie");
	    this.spawnEntity(zombie60, world, 36, -39, 75, start);
	    CreatureEntity zombie61 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie61, "zombie");
	    this.spawnEntity(zombie61, world, 37, -39, 26, start);
	    this.generateChest(world, Direction.WEST, 38, -38, 26, start, 1);
	    CreatureEntity husk62 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk62, "husk");
	    this.spawnEntity(husk62, world, 40, -9, 48, start);
	    CreatureEntity zombie63 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie63, "zombie");
	    this.spawnEntity(zombie63, world, 41, -39, 93, start);
	    this.generateChest(world, Direction.SOUTH, 43, -49, 68, start, 2);
	    CreatureEntity troll64 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:troll")).create(world);
	    this.setItemsForEntity(troll64, "troll");
	    this.spawnEntity(troll64, world, 43, -49, 75, start);
	    this.generateChest(world, Direction.NORTH, 43, -49, 82, start, 2);
	    CreatureEntity pillager65 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager65, "pillager");
	    this.spawnEntity(pillager65, world, 43, 12, 91, start);
	    CreatureEntity skeleton66 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton66, "skeleton");
	    this.spawnEntity(skeleton66, world, 44, -39, 70, start);
	    this.generateChest(world, Direction.NORTH, 44, -38, 93, start, 2);
	    CreatureEntity zombie67 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie67, "zombie");
	    this.spawnEntity(zombie67, world, 44, -29, 32, start);
	    CreatureEntity zombie68 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie68, "zombie");
	    this.spawnEntity(zombie68, world, 44, -29, 43, start);
	    CreatureEntity skeleton69 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton69, "skeleton");
	    this.spawnEntity(skeleton69, world, 44, -29, 58, start);
	    CreatureEntity skeleton70 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton70, "skeleton");
	    this.spawnEntity(skeleton70, world, 44, -29, 72, start);
	    this.generateChest(world, Direction.WEST, 44, -28, 14, start, 1);
	    this.generateChest(world, Direction.WEST, 44, -28, 65, start, 3);
	    CreatureEntity vindicator71 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator71, "vindicator");
	    this.spawnEntity(vindicator71, world, 44, 9, 22, start);
	    this.generateChest(world, Direction.EAST, 45, -49, 28, start, 1);
	    CreatureEntity zombie72 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie72, "zombie");
	    this.spawnEntity(zombie72, world, 47, -39, 93, start);
	    this.generateChest(world, Direction.EAST, 50, -49, -7, start, 2);
	    CreatureEntity skeleton73 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton73, "skeleton");
	    this.spawnEntity(skeleton73, world, 50, -49, 17, start);
	    CreatureEntity skeleton74 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton74, "skeleton");
	    this.spawnEntity(skeleton74, world, 50, -9, 141, start);
	    CreatureEntity skeleton75 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton75, "skeleton");
	    this.spawnEntity(skeleton75, world, 51, -29, 65, start);
	    CreatureEntity vindicator76 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator76, "vindicator");
	    this.spawnEntity(vindicator76, world, 51, 9, 20, start);
	    CreatureEntity illusioner77 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:illusioner")).create(world);
	    this.setItemsForEntity(illusioner77, "illusioner");
	    this.spawnEntity(illusioner77, world, 51, 12, 59, start);
	    CreatureEntity skeleton78 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton78, "skeleton");
	    this.spawnEntity(skeleton78, world, 52, -40, 3, start);
	    CreatureEntity skeleton79 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton79, "skeleton");
	    this.spawnEntity(skeleton79, world, 52, -40, 9, start);
	    CreatureEntity skeleton80 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton80, "skeleton");
	    this.spawnEntity(skeleton80, world, 52, -19, 65, start);
	    CreatureEntity husk81 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk81, "husk");
	    this.spawnEntity(husk81, world, 52, -19, 95, start);
	    CreatureEntity husk82 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk82, "husk");
	    this.spawnEntity(husk82, world, 52, -19, 107, start);
	    CreatureEntity skeleton83 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton83, "skeleton");
	    this.spawnEntity(skeleton83, world, 52, -19, 119, start);
	    this.generateChest(world, Direction.NORTH, 52, -18, 121, start, 1);
	    CreatureEntity zombie84 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie84, "zombie");
	    this.spawnEntity(zombie84, world, 52, -9, 32, start);
	    CreatureEntity husk85 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk85, "husk");
	    this.spawnEntity(husk85, world, 52, -9, 53, start);
	    CreatureEntity husk86 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk86, "husk");
	    this.spawnEntity(husk86, world, 52, -9, 112, start);
	    this.generateChest(world, Direction.NORTH, 52, -8, 141, start, 2);
	    this.generateChest(world, Direction.SOUTH, 52, 12, 55, start, 2);
	    CreatureEntity zombie87 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie87, "zombie");
	    this.spawnEntity(zombie87, world, 54, -49, 14, start);
	    CreatureEntity zombie88 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie88, "zombie");
	    this.spawnEntity(zombie88, world, 54, -49, 20, start);
	    CreatureEntity skeleton89 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton89, "skeleton");
	    this.spawnEntity(skeleton89, world, 54, -9, 141, start);
	    CreatureEntity zombie90 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie90, "zombie");
	    this.spawnEntity(zombie90, world, 55, -39, 76, start);
	    CreatureEntity illusioner91 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:illusioner")).create(world);
	    this.setItemsForEntity(illusioner91, "illusioner");
	    this.spawnEntity(illusioner91, world, 55, 12, 57, start);
	    CreatureEntity husk92 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk92, "husk");
	    this.spawnEntity(husk92, world, 56, -19, 29, start);
	    CreatureEntity husk93 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk93, "husk");
	    this.spawnEntity(husk93, world, 56, -19, 33, start);
	    CreatureEntity evoker94 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:evoker")).create(world);
	    this.setItemsForEntity(evoker94, "evoker");
	    this.spawnEntity(evoker94, world, 56, 9, 19, start);
	    this.generateChest(world, Direction.SOUTH, 56, 12, 55, start, 2);
	    this.generateChest(world, Direction.SOUTH, 57, -49, -14, start, 2);
	    CreatureEntity troll95 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:troll")).create(world);
	    this.setItemsForEntity(troll95, "troll");
	    this.spawnEntity(troll95, world, 57, -49, -6, start);
	    CreatureEntity zombie96 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie96, "zombie");
	    this.spawnEntity(zombie96, world, 57, -49, 41, start);
	    CreatureEntity skeleton97 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton97, "skeleton");
	    this.spawnEntity(skeleton97, world, 57, -40, 1, start);
	    this.generateChest(world, Direction.SOUTH, 57, -39, -1, start, 3);
	    CreatureEntity zombie98 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie98, "zombie");
	    this.spawnEntity(zombie98, world, 57, -39, 19, start);
	    CreatureEntity zombie99 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie99, "zombie");
	    this.spawnEntity(zombie99, world, 57, -39, 29, start);
	    CreatureEntity zombie100 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie100, "zombie");
	    this.spawnEntity(zombie100, world, 57, -39, 41, start);
	    this.generateChest(world, Direction.NORTH, 57, -38, 79, start, 2);
	    CreatureEntity vindicator101 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator101, "vindicator");
	    this.spawnEntity(vindicator101, world, 58, 9, 139, start);
	    CreatureEntity zombie102 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie102, "zombie");
	    this.spawnEntity(zombie102, world, 59, -39, 76, start);
	    this.generateChest(world, Direction.WEST, 59, -18, 31, start, 2);
	    CreatureEntity zombie103 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie103, "zombie");
	    this.spawnEntity(zombie103, world, 60, -49, 14, start);
	    CreatureEntity zombie104 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie104, "zombie");
	    this.spawnEntity(zombie104, world, 60, -49, 20, start);
	    CreatureEntity evoker105 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:evoker")).create(world);
	    this.setItemsForEntity(evoker105, "evoker");
	    this.spawnEntity(evoker105, world, 60, 9, 138, start);
	    CreatureEntity husk106 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk106, "husk");
	    this.spawnEntity(husk106, world, 61, -9, 78, start);
	    this.generateChest(world, Direction.SOUTH, 61, 12, 55, start, 2);
	    CreatureEntity evoker107 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:evoker")).create(world);
	    this.setItemsForEntity(evoker107, "evoker");
	    this.spawnEntity(evoker107, world, 61, 12, 58, start);
	    CreatureEntity skeleton108 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton108, "skeleton");
	    this.spawnEntity(skeleton108, world, 62, -40, 3, start);
	    CreatureEntity skeleton109 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton109, "skeleton");
	    this.spawnEntity(skeleton109, world, 62, -40, 9, start);
	    this.generateChest(world, Direction.WEST, 64, -49, -7, start, 2);
	    CreatureEntity skeleton110 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton110, "skeleton");
	    this.spawnEntity(skeleton110, world, 64, -49, 17, start);
	    CreatureEntity husk111 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk111, "husk");
	    this.spawnEntity(husk111, world, 64, -9, 48, start);
	    this.generateChest(world, Direction.SOUTH, 66, 12, 57, start, 2);
	    CreatureEntity evoker112 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:evoker")).create(world);
	    this.setItemsForEntity(evoker112, "evoker");
	    this.spawnEntity(evoker112, world, 66, 12, 60, start);
	    CreatureEntity evoker113 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:evoker")).create(world);
	    this.setItemsForEntity(evoker113, "evoker");
	    this.spawnEntity(evoker113, world, 66, 12, 78, start);
	    CreatureEntity skeleton114 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton114, "skeleton");
	    this.spawnEntity(skeleton114, world, 67, -40, 75, start);
	    CreatureEntity skeleton115 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton115, "skeleton");
	    this.spawnEntity(skeleton115, world, 67, -40, 81, start);
	    CreatureEntity skeleton116 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton116, "skeleton");
	    this.spawnEntity(skeleton116, world, 67, -40, 87, start);
	    CreatureEntity skeleton117 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton117, "skeleton");
	    this.spawnEntity(skeleton117, world, 67, -9, 32, start);
	    CreatureEntity skeleton118 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton118, "skeleton");
	    this.spawnEntity(skeleton118, world, 69, -40, 65, start);
	    CreatureEntity skeleton119 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton119, "skeleton");
	    this.spawnEntity(skeleton119, world, 69, -19, 76, start);
	    CreatureEntity skeleton120 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton120, "skeleton");
	    this.spawnEntity(skeleton120, world, 69, -19, 88, start);
	    this.generateChest(world, Direction.WEST, 69, -8, 32, start, 1);
	    CreatureEntity zombie121 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie121, "zombie");
	    this.spawnEntity(zombie121, world, 70, -50, -15, start);
	    CreatureEntity zombie122 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie122, "zombie");
	    this.spawnEntity(zombie122, world, 70, -50, -9, start);
	    CreatureEntity skeleton123 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton123, "skeleton");
	    this.spawnEntity(skeleton123, world, 70, -49, 45, start);
	    CreatureEntity skeleton124 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton124, "skeleton");
	    this.spawnEntity(skeleton124, world, 70, -49, 51, start);
	    CreatureEntity husk125 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk125, "husk");
	    this.spawnEntity(husk125, world, 71, -19, 80, start);
	    CreatureEntity husk126 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk126, "husk");
	    this.spawnEntity(husk126, world, 71, -19, 84, start);
	    CreatureEntity skeleton127 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton127, "skeleton");
	    this.spawnEntity(skeleton127, world, 72, -49, 43, start);
	    CreatureEntity skeleton128 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton128, "skeleton");
	    this.spawnEntity(skeleton128, world, 72, -49, 53, start);
	    CreatureEntity skeleton129 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton129, "skeleton");
	    this.spawnEntity(skeleton129, world, 72, -40, 89, start);
	    this.generateChest(world, Direction.NORTH, 72, -39, 91, start, 3);
	    CreatureEntity skeleton130 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton130, "skeleton");
	    this.spawnEntity(skeleton130, world, 73, -19, 48, start);
	    CreatureEntity skeleton131 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton131, "skeleton");
	    this.spawnEntity(skeleton131, world, 74, -9, 48, start);
	    CreatureEntity zombie132 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie132, "zombie");
	    this.spawnEntity(zombie132, world, 75, -50, -17, start);
	    CreatureEntity troll133 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:troll")).create(world);
	    this.setItemsForEntity(troll133, "troll");
	    this.spawnEntity(troll133, world, 75, -50, 27, start);
	    this.generateChest(world, Direction.SOUTH, 75, -49, -19, start, 3);
	    CreatureEntity troll134 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:troll")).create(world);
	    this.setItemsForEntity(troll134, "troll");
	    this.spawnEntity(troll134, world, 75, -49, 75, start);
	    CreatureEntity skeleton135 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton135, "skeleton");
	    this.spawnEntity(skeleton135, world, 75, -40, 65, start);
	    this.generateChest(world, Direction.WEST, 75, -18, 82, start, 2);
	    this.generateChest(world, Direction.WEST, 76, -8, 48, start, 2);
	    CreatureEntity skeleton136 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton136, "skeleton");
	    this.spawnEntity(skeleton136, world, 77, -40, 70, start);
	    CreatureEntity skeleton137 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton137, "skeleton");
	    this.spawnEntity(skeleton137, world, 77, -40, 81, start);
	    CreatureEntity skeleton138 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton138, "skeleton");
	    this.spawnEntity(skeleton138, world, 77, -40, 87, start);
	    CreatureEntity skeleton139 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton139, "skeleton");
	    this.spawnEntity(skeleton139, world, 78, -49, 43, start);
	    CreatureEntity skeleton140 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton140, "skeleton");
	    this.spawnEntity(skeleton140, world, 78, -49, 53, start);
	    CreatureEntity zombie141 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie141, "zombie");
	    this.spawnEntity(zombie141, world, 80, -50, -15, start);
	    CreatureEntity zombie142 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie142, "zombie");
	    this.spawnEntity(zombie142, world, 80, -50, -9, start);
	    CreatureEntity skeleton143 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton143, "skeleton");
	    this.spawnEntity(skeleton143, world, 80, -49, 45, start);
	    CreatureEntity skeleton144 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton144, "skeleton");
	    this.spawnEntity(skeleton144, world, 80, -49, 51, start);
	    CreatureEntity skeleton145 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton145, "skeleton");
	    this.spawnEntity(skeleton145, world, 82, -40, 53, start);
	    CreatureEntity skeleton146 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton146, "skeleton");
	    this.spawnEntity(skeleton146, world, 82, -40, 67, start);
	    CreatureEntity skeleton147 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton147, "skeleton");
	    this.spawnEntity(skeleton147, world, 82, -40, 73, start);
	    CreatureEntity pillager148 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager148, "pillager");
	    this.spawnEntity(pillager148, world, 82, 9, 22, start);
	    CreatureEntity pillager149 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager149, "pillager");
	    this.spawnEntity(pillager149, world, 83, 12, 76, start);
	    CreatureEntity pillager150 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager150, "pillager");
	    this.spawnEntity(pillager150, world, 83, 12, 80, start);
	    CreatureEntity skeleton151 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton151, "skeleton");
	    this.spawnEntity(skeleton151, world, 84, -40, 43, start);
	    CreatureEntity skeleton152 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton152, "skeleton");
	    this.spawnEntity(skeleton152, world, 87, -40, 75, start);
	    this.generateChest(world, Direction.NORTH, 87, -39, 77, start, 3);
	    CreatureEntity zombie153 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie153, "zombie");
	    this.spawnEntity(zombie153, world, 88, -49, 28, start);
	    CreatureEntity skeleton154 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton154, "skeleton");
	    this.spawnEntity(skeleton154, world, 90, -40, 43, start);
	    this.generateChest(world, Direction.EAST, 91, 9, 101, start, 2);
	    CreatureEntity skeleton155 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton155, "skeleton");
	    this.spawnEntity(skeleton155, world, 92, -40, 53, start);
	    CreatureEntity skeleton156 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton156, "skeleton");
	    this.spawnEntity(skeleton156, world, 92, -40, 67, start);
	    CreatureEntity skeleton157 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton157, "skeleton");
	    this.spawnEntity(skeleton157, world, 92, -40, 73, start);
	    CreatureEntity pillager158 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager158, "pillager");
	    this.spawnEntity(pillager158, world, 92, 12, 131, start);
	    CreatureEntity evoker159 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:evoker")).create(world);
	    this.setItemsForEntity(evoker159, "evoker");
	    this.spawnEntity(evoker159, world, 93, 9, 101, start);
	    CreatureEntity zombie160 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie160, "zombie");
	    this.spawnEntity(zombie160, world, 94, -49, 28, start);
	    CreatureEntity skeleton161 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton161, "skeleton");
	    this.spawnEntity(skeleton161, world, 94, -19, 35, start);
	    CreatureEntity husk162 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk162, "husk");
	    this.spawnEntity(husk162, world, 94, -19, 48, start);
	    CreatureEntity skeleton163 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton163, "skeleton");
	    this.spawnEntity(skeleton163, world, 94, -19, 70, start);
	    this.generateChest(world, Direction.SOUTH, 94, -18, 33, start, 1);
	    this.generateChest(world, Direction.NORTH, 94, -18, 72, start, 1);
	    CreatureEntity skeleton164 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton164, "skeleton");
	    this.spawnEntity(skeleton164, world, 94, -9, 75, start);
	    CreatureEntity skeleton165 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton165, "skeleton");
	    this.spawnEntity(skeleton165, world, 94, -9, 81, start);
	    CreatureEntity zombie166 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie166, "zombie");
	    this.spawnEntity(zombie166, world, 100, -49, 28, start);
	    CreatureEntity skeleton167 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton167, "skeleton");
	    this.spawnEntity(skeleton167, world, 101, -50, 80, start);
	    CreatureEntity skeleton168 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton168, "skeleton");
	    this.spawnEntity(skeleton168, world, 102, -50, 70, start);
	    CreatureEntity vindicator169 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator169, "vindicator");
	    this.spawnEntity(vindicator169, world, 102, 9, 37, start);
	    CreatureEntity vindicator170 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator170, "vindicator");
	    this.spawnEntity(vindicator170, world, 102, 9, 39, start);
	    this.generateChest(world, Direction.WEST, 103, -38, 48, start, 2);
	    CreatureEntity evoker171 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:evoker")).create(world);
	    this.setItemsForEntity(evoker171, "evoker");
	    this.spawnEntity(evoker171, world, 103, 9, 25, start);
	    CreatureEntity husk172 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk172, "husk");
	    this.spawnEntity(husk172, world, 104, -49, 42, start);
	    CreatureEntity husk173 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk173, "husk");
	    this.spawnEntity(husk173, world, 104, -49, 54, start);
	    CreatureEntity vindicator174 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator174, "vindicator");
	    this.spawnEntity(vindicator174, world, 104, 9, 101, start);
	    CreatureEntity vindicator175 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator175, "vindicator");
	    this.spawnEntity(vindicator175, world, 105, 9, 64, start);
	    CreatureEntity vindicator176 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator176, "vindicator");
	    this.spawnEntity(vindicator176, world, 105, 9, 90, start);
	    CreatureEntity zombie177 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie177, "zombie");
	    this.spawnEntity(zombie177, world, 106, -49, 28, start);
	    this.generateChest(world, Direction.WEST, 106, -8, 78, start, 2);
	    CreatureEntity skeleton178 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton178, "skeleton");
	    this.spawnEntity(skeleton178, world, 107, -50, 70, start);
	    CreatureEntity skeleton179 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton179, "skeleton");
	    this.spawnEntity(skeleton179, world, 107, -50, 80, start);
	    CreatureEntity skeleton180 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton180, "skeleton");
	    this.spawnEntity(skeleton180, world, 109, -50, 75, start);
	    this.generateChest(world, Direction.WEST, 110, -48, 48, start, 3);
	    CreatureEntity zombie181 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie181, "zombie");
	    this.spawnEntity(zombie181, world, 111, -49, 28, start);
	    this.generateChest(world, Direction.WEST, 111, -49, 75, start, 3);
	    this.generateChest(world, Direction.WEST, 115, -48, 28, start, 3);
	    CreatureEntity skeleton182 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton182, "skeleton");
	    this.spawnEntity(skeleton182, world, 118, -49, 25, start);
	    CreatureEntity skeleton183 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton183, "skeleton");
	    this.spawnEntity(skeleton183, world, 118, -49, 31, start);
	    this.executeCommand(world);
	}

}
