package mod.arcalitegames.odyssey.world.structure.structures.dungeons.ziggurat;

import java.util.Objects;

import mod.arcalitegames.odyssey.world.structure.StructureBase;
import mod.arcalitegames.system.parser.EntityParser;
import net.minecraft.block.Blocks;
import net.minecraft.entity.CreatureEntity;
import net.minecraft.util.Direction;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;

public class ZigguratDungeon extends StructureBase
{

	public ZigguratDungeon(World worldIn, BlockPos origin, int xRange, int yRange, int zRange)
	{
		super(worldIn, origin, xRange, yRange, zRange);
		ZigguratComponent0.init(world, start, this);
		ZigguratComponent1.init(world, start, this);
		ZigguratComponent2.init(world, start, this);
		ZigguratComponent3.init(world, start, this);
		ZigguratComponent4.init(world, start, this);
        this.fillWithBlocks(world, start, 20, 6, 17, 192, 65, 139, Blocks.AIR.getDefaultState());

	}

	@Override
	public void addEntitiesAndSpawn()
	{
	    this.generateChest(world, Direction.EAST, 27, -49, 38, start, 3);
	    this.generateChest(world, Direction.EAST, 30, -39, 38, start, 3);
	    CreatureEntity skeleton1 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton1, "skeleton");
	    this.spawnEntity(skeleton1, world, 32, -40, 38, start);
	    CreatureEntity skeleton2 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton2, "skeleton");
	    this.spawnEntity(skeleton2, world, 34, -40, 33, start);
	    CreatureEntity skeleton3 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton3, "skeleton");
	    this.spawnEntity(skeleton3, world, 34, -40, 43, start);
	    this.generateChest(world, Direction.EAST, 35, -28, 10, start, 1);
	    this.generateChest(world, Direction.EAST, 35, -28, 32, start, 1);
	    CreatureEntity skeleton4 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton4, "skeleton");
	    this.spawnEntity(skeleton4, world, 36, -29, 32, start);
	    CreatureEntity troll5 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:troll")).create(world);
	    this.setItemsForEntity(troll5, "troll");
	    this.spawnEntity(troll5, world, 37, -49, 38, start);
	    CreatureEntity skeleton6 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton6, "skeleton");
	    this.spawnEntity(skeleton6, world, 37, -29, 15, start);
	    this.generateChest(world, Direction.EAST, 38, -18, 38, start, 2);
	    CreatureEntity skeleton7 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton7, "skeleton");
	    this.spawnEntity(skeleton7, world, 40, -40, 33, start);
	    CreatureEntity skeleton8 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton8, "skeleton");
	    this.spawnEntity(skeleton8, world, 40, -40, 43, start);
	    CreatureEntity zombie9 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie9, "zombie");
	    this.spawnEntity(zombie9, world, 43, -29, 27, start);
	    this.generateChest(world, Direction.NORTH, 43, -28, 38, start, 2);
	    this.generateChest(world, Direction.EAST, 43, -28, 55, start, 2);
	    CreatureEntity skeleton10 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton10, "skeleton");
	    this.spawnEntity(skeleton10, world, 43, -19, 38, start);
	    this.generateChest(world, Direction.EAST, 44, -39, 21, start, 1);
	    CreatureEntity skeleton11 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton11, "skeleton");
	    this.spawnEntity(skeleton11, world, 44, -39, 38, start);
	    CreatureEntity zombie12 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie12, "zombie");
	    this.spawnEntity(zombie12, world, 44, -29, 4, start);
	    CreatureEntity zombie13 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie13, "zombie");
	    this.spawnEntity(zombie13, world, 46, -29, 7, start);
	    CreatureEntity zombie14 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie14, "zombie");
	    this.spawnEntity(zombie14, world, 46, -29, 55, start);
	    CreatureEntity skeleton15 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton15, "skeleton");
	    this.spawnEntity(skeleton15, world, 47, -40, 52, start);
	    CreatureEntity skeleton16 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton16, "skeleton");
	    this.spawnEntity(skeleton16, world, 47, -40, 58, start);
	    CreatureEntity skeleton17 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton17, "skeleton");
	    this.spawnEntity(skeleton17, world, 49, -29, 15, start);
	    CreatureEntity zombie18 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie18, "zombie");
	    this.spawnEntity(zombie18, world, 49, -29, 21, start);
	    this.generateChest(world, Direction.SOUTH, 49, -28, -4, start, 1);
	    this.generateChest(world, Direction.SOUTH, 49, -28, 47, start, 1);
	    this.generateChest(world, Direction.NORTH, 49, -28, 63, start, 1);
	    CreatureEntity zombie19 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie19, "zombie");
	    this.spawnEntity(zombie19, world, 50, -39, 21, start);
	    CreatureEntity skeleton20 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton20, "skeleton");
	    this.spawnEntity(skeleton20, world, 51, -40, 59, start);
	    this.generateChest(world, Direction.SOUTH, 51, -39, 14, start, 1);
	    CreatureEntity zombie21 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie21, "zombie");
	    this.spawnEntity(zombie21, world, 51, -39, 20, start);
	    CreatureEntity zombie22 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie22, "zombie");
	    this.spawnEntity(zombie22, world, 51, -39, 21, start);
	    CreatureEntity zombie23 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie23, "zombie");
	    this.spawnEntity(zombie23, world, 51, -39, 22, start);
	    CreatureEntity skeleton24 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton24, "skeleton");
	    this.spawnEntity(skeleton24, world, 51, -39, 47, start);
	    this.generateChest(world, Direction.NORTH, 51, -39, 62, start, 3);
	    this.generateChest(world, Direction.WEST, 51, -28, 32, start, 1);
	    CreatureEntity zombie25 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie25, "zombie");
	    this.spawnEntity(zombie25, world, 52, -39, 21, start);
	    CreatureEntity skeleton26 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton26, "skeleton");
	    this.spawnEntity(skeleton26, world, 55, -40, 52, start);
	    CreatureEntity skeleton27 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton27, "skeleton");
	    this.spawnEntity(skeleton27, world, 55, -40, 58, start);
	    CreatureEntity zombie28 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie28, "zombie");
	    this.spawnEntity(zombie28, world, 56, -19, 36, start);
	    CreatureEntity zombie29 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie29, "zombie");
	    this.spawnEntity(zombie29, world, 56, -19, 40, start);
	    this.generateChest(world, Direction.EAST, 56, -18, 21, start, 1);
	    CreatureEntity skeleton30 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton30, "skeleton");
	    this.spawnEntity(skeleton30, world, 57, -19, 63, start);
	    this.generateChest(world, Direction.NORTH, 57, -18, 68, start, 1);
	    this.generateChest(world, Direction.WEST, 58, -39, 21, start, 1);
	    CreatureEntity skeleton31 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton31, "skeleton");
	    this.spawnEntity(skeleton31, world, 58, -29, 50, start);
	    CreatureEntity zombie32 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie32, "zombie");
	    this.spawnEntity(zombie32, world, 58, -19, 21, start);
	    CreatureEntity husk33 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk33, "husk");
	    this.spawnEntity(husk33, world, 60, -29, 28, start);
	    CreatureEntity husk34 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk34, "husk");
	    this.spawnEntity(husk34, world, 60, -19, 36, start);
	    CreatureEntity husk35 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk35, "husk");
	    this.spawnEntity(husk35, world, 60, -19, 40, start);
	    CreatureEntity skeleton36 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton36, "skeleton");
	    this.spawnEntity(skeleton36, world, 61, -39, 38, start);
	    CreatureEntity skeleton37 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton37, "skeleton");
	    this.spawnEntity(skeleton37, world, 62, -29, 50, start);
	    this.generateChest(world, Direction.EAST, 68, -49, 72, start, 2);
	    CreatureEntity skeleton38 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton38, "skeleton");
	    this.spawnEntity(skeleton38, world, 70, -9, 36, start);
	    CreatureEntity skeleton39 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton39, "skeleton");
	    this.spawnEntity(skeleton39, world, 70, -9, 40, start);
	    this.generateChest(world, Direction.EAST, 70, -8, 38, start, 2);
	    CreatureEntity skeleton40 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton40, "skeleton");
	    this.spawnEntity(skeleton40, world, 71, -29, 48, start);
	    CreatureEntity skeleton41 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton41, "skeleton");
	    this.spawnEntity(skeleton41, world, 71, -29, 62, start);
	    this.generateChest(world, Direction.SOUTH, 71, -28, 47, start, 1);
	    this.generateChest(world, Direction.NORTH, 71, -28, 63, start, 1);
	    this.generateChest(world, Direction.EAST, 72, -38, 16, start, 1);
	    CreatureEntity zombie42 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie42, "zombie");
	    this.spawnEntity(zombie42, world, 72, -29, 4, start);
	    CreatureEntity zombie43 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie43, "zombie");
	    this.spawnEntity(zombie43, world, 73, -39, 16, start);
	    CreatureEntity troll44 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:troll")).create(world);
	    this.setItemsForEntity(troll44, "troll");
	    this.spawnEntity(troll44, world, 75, -49, 38, start);
	    CreatureEntity troll45 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:troll")).create(world);
	    this.setItemsForEntity(troll45, "troll");
	    this.spawnEntity(troll45, world, 75, -49, 71, start);
	    this.generateChest(world, Direction.NORTH, 75, -49, 79, start, 2);
	    this.generateChest(world, Direction.SOUTH, 75, -48, 21, start, 3);
	    CreatureEntity skeleton46 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton46, "skeleton");
	    this.spawnEntity(skeleton46, world, 77, -29, -2, start);
	    CreatureEntity husk47 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk47, "husk");
	    this.spawnEntity(husk47, world, 77, -29, 21, start);
	    CreatureEntity skeleton48 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton48, "skeleton");
	    this.spawnEntity(skeleton48, world, 77, -19, 21, start);
	    CreatureEntity skeleton49 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton49, "skeleton");
	    this.spawnEntity(skeleton49, world, 77, -19, 73, start);
	    this.generateChest(world, Direction.NORTH, 77, -18, 75, start, 1);
	    CreatureEntity skeleton50 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton50, "skeleton");
	    this.spawnEntity(skeleton50, world, 80, -39, 82, start);
	    this.generateChest(world, Direction.SOUTH, 80, -38, 10, start, 2);
	    this.generateChest(world, Direction.NORTH, 80, -38, 83, start, 1);
	    this.generateChest(world, Direction.WEST, 82, -49, 72, start, 2);
	    CreatureEntity zombie51 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie51, "zombie");
	    this.spawnEntity(zombie51, world, 82, -29, 4, start);
	    CreatureEntity husk52 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk52, "husk");
	    this.spawnEntity(husk52, world, 83, -29, 50, start);
	    CreatureEntity husk53 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk53, "husk");
	    this.spawnEntity(husk53, world, 83, -29, 53, start);
	    CreatureEntity husk54 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk54, "husk");
	    this.spawnEntity(husk54, world, 83, -29, 57, start);
	    CreatureEntity husk55 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk55, "husk");
	    this.spawnEntity(husk55, world, 83, -29, 60, start);
	    this.generateChest(world, Direction.SOUTH, 83, -28, 47, start, 1);
	    this.generateChest(world, Direction.NORTH, 83, -28, 63, start, 1);
	    CreatureEntity bandit56 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit")).create(world);
	    this.setItemsForEntity(bandit56, "bandit");
	    this.spawnEntity(bandit56, world, 85, 19, 64, start);
	    CreatureEntity bandit57 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit")).create(world);
	    this.setItemsForEntity(bandit57, "bandit");
	    this.spawnEntity(bandit57, world, 85, 19, 82, start);
	    this.generateChest(world, Direction.EAST, 86, -49, 65, start, 2);
	    CreatureEntity zombie58 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie58, "zombie");
	    this.spawnEntity(zombie58, world, 86, -39, 54, start);
	    CreatureEntity zombie59 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie59, "zombie");
	    this.spawnEntity(zombie59, world, 86, -39, 65, start);
	    CreatureEntity zombie60 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie60, "zombie");
	    this.spawnEntity(zombie60, world, 87, -39, 16, start);
	    CreatureEntity bandit61 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit")).create(world);
	    this.setItemsForEntity(bandit61, "bandit");
	    this.spawnEntity(bandit61, world, 87, 19, 45, start);
	    this.generateChest(world, Direction.WEST, 88, -38, 16, start, 1);
	    CreatureEntity bandit62 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit")).create(world);
	    this.setItemsForEntity(bandit62, "bandit");
	    this.spawnEntity(bandit62, world, 88, 19, 92, start);
	    CreatureEntity husk63 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk63, "husk");
	    this.spawnEntity(husk63, world, 90, -9, 38, start);
	    CreatureEntity zombie64 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie64, "zombie");
	    this.spawnEntity(zombie64, world, 91, -39, 83, start);
	    this.generateChest(world, Direction.SOUTH, 91, 14, 49, start, 2);
	    this.generateChest(world, Direction.SOUTH, 93, -49, 58, start, 2);
	    CreatureEntity troll65 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:troll")).create(world);
	    this.setItemsForEntity(troll65, "troll");
	    this.spawnEntity(troll65, world, 93, -49, 65, start);
	    this.generateChest(world, Direction.NORTH, 93, -49, 72, start, 2);
	    CreatureEntity bandit_thug66 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit_thug")).create(world);
	    this.setItemsForEntity(bandit_thug66, "bandit_thug");
	    this.spawnEntity(bandit_thug66, world, 93, 12, 68, start);
	    CreatureEntity skeleton67 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton67, "skeleton");
	    this.spawnEntity(skeleton67, world, 94, -39, 60, start);
	    this.generateChest(world, Direction.NORTH, 94, -38, 83, start, 2);
	    CreatureEntity zombie68 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie68, "zombie");
	    this.spawnEntity(zombie68, world, 94, -29, 22, start);
	    CreatureEntity zombie69 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie69, "zombie");
	    this.spawnEntity(zombie69, world, 94, -29, 33, start);
	    CreatureEntity skeleton70 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton70, "skeleton");
	    this.spawnEntity(skeleton70, world, 94, -29, 48, start);
	    CreatureEntity skeleton71 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton71, "skeleton");
	    this.spawnEntity(skeleton71, world, 94, -29, 62, start);
	    this.generateChest(world, Direction.WEST, 94, -28, 4, start, 1);
	    this.generateChest(world, Direction.WEST, 94, -28, 55, start, 3);
	    CreatureEntity bandit_plunderer72 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit_plunderer")).create(world);
	    this.setItemsForEntity(bandit_plunderer72, "bandit_plunderer");
	    this.spawnEntity(bandit_plunderer72, world, 94, 14, 52, start);
	    this.generateChest(world, Direction.EAST, 95, -49, 18, start, 1);
	    CreatureEntity bandit73 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit")).create(world);
	    this.setItemsForEntity(bandit73, "bandit");
	    this.spawnEntity(bandit73, world, 95, 19, 95, start);
	    this.generateChest(world, Direction.EAST, 95, 21, 68, start, 2);
	    this.generateChest(world, Direction.SOUTH, 96, 19, 51, start, 1);
	    CreatureEntity bandit_plunderer74 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit_plunderer")).create(world);
	    this.setItemsForEntity(bandit_plunderer74, "bandit_plunderer");
	    this.spawnEntity(bandit_plunderer74, world, 96, 21, 66, start);
	    CreatureEntity zombie75 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie75, "zombie");
	    this.spawnEntity(zombie75, world, 97, -39, 83, start);
	    this.generateChest(world, Direction.WEST, 97, 12, 65, start, 1);
	    this.generateChest(world, Direction.WEST, 97, 12, 66, start, 1);
	    this.generateChest(world, Direction.SOUTH, 97, 14, 49, start, 2);
	    CreatureEntity bandit76 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit")).create(world);
	    this.setItemsForEntity(bandit76, "bandit");
	    this.spawnEntity(bandit76, world, 97, 19, 40, start);
	    this.generateChest(world, Direction.SOUTH, 97, 19, 57, start, 1);
	    this.generateChest(world, Direction.NORTH, 97, 26, 78, start, 1);
	    this.generateChest(world, Direction.SOUTH, 99, 14, 81, start, 1);
	    this.generateChest(world, Direction.NORTH, 99, 14, 87, start, 1);
	    this.generateChest(world, Direction.EAST, 100, -49, -17, start, 2);
	    CreatureEntity skeleton77 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton77, "skeleton");
	    this.spawnEntity(skeleton77, world, 100, -49, 7, start);
	    CreatureEntity skeleton78 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton78, "skeleton");
	    this.spawnEntity(skeleton78, world, 100, -9, 131, start);
	    CreatureEntity bandit79 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit")).create(world);
	    this.setItemsForEntity(bandit79, "bandit");
	    this.spawnEntity(bandit79, world, 100, 14, 83, start);
	    CreatureEntity bandit80 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit")).create(world);
	    this.setItemsForEntity(bandit80, "bandit");
	    this.spawnEntity(bandit80, world, 100, 26, 72, start);
	    CreatureEntity skeleton81 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton81, "skeleton");
	    this.spawnEntity(skeleton81, world, 101, -29, 55, start);
	    CreatureEntity skeleton82 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton82, "skeleton");
	    this.spawnEntity(skeleton82, world, 102, -40, -7, start);
	    CreatureEntity skeleton83 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton83, "skeleton");
	    this.spawnEntity(skeleton83, world, 102, -40, -1, start);
	    CreatureEntity skeleton84 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton84, "skeleton");
	    this.spawnEntity(skeleton84, world, 102, -19, 55, start);
	    CreatureEntity husk85 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk85, "husk");
	    this.spawnEntity(husk85, world, 102, -19, 85, start);
	    CreatureEntity husk86 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk86, "husk");
	    this.spawnEntity(husk86, world, 102, -19, 97, start);
	    CreatureEntity skeleton87 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton87, "skeleton");
	    this.spawnEntity(skeleton87, world, 102, -19, 109, start);
	    this.generateChest(world, Direction.NORTH, 102, -18, 111, start, 1);
	    CreatureEntity zombie88 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie88, "zombie");
	    this.spawnEntity(zombie88, world, 102, -9, 22, start);
	    CreatureEntity husk89 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk89, "husk");
	    this.spawnEntity(husk89, world, 102, -9, 43, start);
	    CreatureEntity husk90 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk90, "husk");
	    this.spawnEntity(husk90, world, 102, -9, 102, start);
	    this.generateChest(world, Direction.NORTH, 102, -8, 131, start, 2);
	    CreatureEntity bandit91 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit")).create(world);
	    this.setItemsForEntity(bandit91, "bandit");
	    this.spawnEntity(bandit91, world, 102, 14, 87, start);
	    CreatureEntity bandit92 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit")).create(world);
	    this.setItemsForEntity(bandit92, "bandit");
	    this.spawnEntity(bandit92, world, 102, 26, 64, start);
	    CreatureEntity zombie93 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie93, "zombie");
	    this.spawnEntity(zombie93, world, 104, -49, 4, start);
	    CreatureEntity zombie94 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie94, "zombie");
	    this.spawnEntity(zombie94, world, 104, -49, 10, start);
	    CreatureEntity skeleton95 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton95, "skeleton");
	    this.spawnEntity(skeleton95, world, 104, -9, 131, start);
	    CreatureEntity bandit96 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit")).create(world);
	    this.setItemsForEntity(bandit96, "bandit");
	    this.spawnEntity(bandit96, world, 104, 26, 62, start);
	    CreatureEntity zombie97 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie97, "zombie");
	    this.spawnEntity(zombie97, world, 105, -39, 66, start);
	    this.generateChest(world, Direction.SOUTH, 105, 14, 81, start, 1);
	    this.generateChest(world, Direction.NORTH, 105, 14, 87, start, 1);
	    this.generateChest(world, Direction.SOUTH, 105, 26, 59, start, 1);
	    CreatureEntity husk98 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk98, "husk");
	    this.spawnEntity(husk98, world, 106, -19, 19, start);
	    CreatureEntity husk99 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk99, "husk");
	    this.spawnEntity(husk99, world, 106, -19, 23, start);
	    this.generateChest(world, Direction.SOUTH, 107, -49, -24, start, 2);
	    CreatureEntity troll100 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:troll")).create(world);
	    this.setItemsForEntity(troll100, "troll");
	    this.spawnEntity(troll100, world, 107, -49, -16, start);
	    CreatureEntity zombie101 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie101, "zombie");
	    this.spawnEntity(zombie101, world, 107, -49, 31, start);
	    CreatureEntity skeleton102 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton102, "skeleton");
	    this.spawnEntity(skeleton102, world, 107, -40, -9, start);
	    this.generateChest(world, Direction.SOUTH, 107, -39, -11, start, 3);
	    CreatureEntity zombie103 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie103, "zombie");
	    this.spawnEntity(zombie103, world, 107, -39, 9, start);
	    CreatureEntity zombie104 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie104, "zombie");
	    this.spawnEntity(zombie104, world, 107, -39, 19, start);
	    CreatureEntity zombie105 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie105, "zombie");
	    this.spawnEntity(zombie105, world, 107, -39, 31, start);
	    this.generateChest(world, Direction.NORTH, 107, -38, 69, start, 2);
	    this.generateChest(world, Direction.NORTH, 107, 13, 55, start, 1);
	    CreatureEntity bandit106 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit")).create(world);
	    this.setItemsForEntity(bandit106, "bandit");
	    this.spawnEntity(bandit106, world, 108, 13, 53, start);
	    this.generateChest(world, Direction.WEST, 108, 26, 62, start, 1);
	    CreatureEntity bandit_thug107 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit_thug")).create(world);
	    this.setItemsForEntity(bandit_thug107, "bandit_thug");
	    this.spawnEntity(bandit_thug107, world, 108, 31, 68, start);
	    CreatureEntity zombie108 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie108, "zombie");
	    this.spawnEntity(zombie108, world, 109, -39, 66, start);
	    this.generateChest(world, Direction.WEST, 109, -18, 21, start, 2);
	    CreatureEntity bandit109 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit")).create(world);
	    this.setItemsForEntity(bandit109, "bandit");
	    this.spawnEntity(bandit109, world, 109, 14, 84, start);
	    CreatureEntity bandit110 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit")).create(world);
	    this.setItemsForEntity(bandit110, "bandit");
	    this.spawnEntity(bandit110, world, 109, 19, 94, start);
	    CreatureEntity zombie111 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie111, "zombie");
	    this.spawnEntity(zombie111, world, 110, -49, 4, start);
	    CreatureEntity zombie112 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie112, "zombie");
	    this.spawnEntity(zombie112, world, 110, -49, 10, start);
	    CreatureEntity bandit_outlaw113 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit_outlaw")).create(world);
	    this.setItemsForEntity(bandit_outlaw113, "bandit_outlaw");
	    this.spawnEntity(bandit_outlaw113, world, 110, 15, 68, start);
	    CreatureEntity bandit_outlaw114 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit_outlaw")).create(world);
	    this.setItemsForEntity(bandit_outlaw114, "bandit_outlaw");
	    this.spawnEntity(bandit_outlaw114, world, 110, 19, 65, start);
	    CreatureEntity husk115 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk115, "husk");
	    this.spawnEntity(husk115, world, 111, -9, 68, start);
	    CreatureEntity bandit116 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit")).create(world);
	    this.setItemsForEntity(bandit116, "bandit");
	    this.spawnEntity(bandit116, world, 111, 19, 59, start);
	    CreatureEntity skeleton117 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton117, "skeleton");
	    this.spawnEntity(skeleton117, world, 112, -40, -7, start);
	    CreatureEntity skeleton118 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton118, "skeleton");
	    this.spawnEntity(skeleton118, world, 112, -40, -1, start);
	    CreatureEntity bandit119 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit")).create(world);
	    this.setItemsForEntity(bandit119, "bandit");
	    this.spawnEntity(bandit119, world, 112, 13, 53, start);
	    this.generateChest(world, Direction.WEST, 113, 13, 55, start, 1);
	    this.generateChest(world, Direction.WEST, 113, 15, 67, start, 2);
	    this.generateChest(world, Direction.WEST, 113, 19, 60, start, 1);
	    this.generateChest(world, Direction.WEST, 113, 19, 61, start, 1);
	    this.generateChest(world, Direction.WEST, 113, 19, 64, start, 1);
	    this.generateChest(world, Direction.WEST, 113, 19, 71, start, 1);
	    this.generateChest(world, Direction.WEST, 114, -49, -17, start, 2);
	    CreatureEntity skeleton120 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton120, "skeleton");
	    this.spawnEntity(skeleton120, world, 114, -49, 7, start);
	    CreatureEntity husk121 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk121, "husk");
	    this.spawnEntity(husk121, world, 114, -9, 38, start);
	    CreatureEntity bandit122 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit")).create(world);
	    this.setItemsForEntity(bandit122, "bandit");
	    this.spawnEntity(bandit122, world, 114, 19, 43, start);
	    CreatureEntity skeleton123 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton123, "skeleton");
	    this.spawnEntity(skeleton123, world, 117, -40, 65, start);
	    CreatureEntity skeleton124 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton124, "skeleton");
	    this.spawnEntity(skeleton124, world, 117, -40, 71, start);
	    CreatureEntity skeleton125 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton125, "skeleton");
	    this.spawnEntity(skeleton125, world, 117, -40, 77, start);
	    CreatureEntity skeleton126 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton126, "skeleton");
	    this.spawnEntity(skeleton126, world, 117, -9, 22, start);
	    CreatureEntity bandit127 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit")).create(world);
	    this.setItemsForEntity(bandit127, "bandit");
	    this.spawnEntity(bandit127, world, 118, 19, 93, start);
	    CreatureEntity skeleton128 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton128, "skeleton");
	    this.spawnEntity(skeleton128, world, 119, -40, 55, start);
	    CreatureEntity skeleton129 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton129, "skeleton");
	    this.spawnEntity(skeleton129, world, 119, -19, 66, start);
	    CreatureEntity skeleton130 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton130, "skeleton");
	    this.spawnEntity(skeleton130, world, 119, -19, 78, start);
	    this.generateChest(world, Direction.WEST, 119, -8, 22, start, 1);
	    CreatureEntity bandit131 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit")).create(world);
	    this.setItemsForEntity(bandit131, "bandit");
	    this.spawnEntity(bandit131, world, 119, 19, 52, start);
	    CreatureEntity bandit132 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit")).create(world);
	    this.setItemsForEntity(bandit132, "bandit");
	    this.spawnEntity(bandit132, world, 119, 22, 63, start);
	    CreatureEntity bandit133 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit")).create(world);
	    this.setItemsForEntity(bandit133, "bandit");
	    this.spawnEntity(bandit133, world, 119, 22, 72, start);
	    CreatureEntity zombie134 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie134, "zombie");
	    this.spawnEntity(zombie134, world, 120, -50, -25, start);
	    CreatureEntity zombie135 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie135, "zombie");
	    this.spawnEntity(zombie135, world, 120, -50, -19, start);
	    CreatureEntity skeleton136 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton136, "skeleton");
	    this.spawnEntity(skeleton136, world, 120, -49, 35, start);
	    CreatureEntity skeleton137 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton137, "skeleton");
	    this.spawnEntity(skeleton137, world, 120, -49, 41, start);
	    CreatureEntity husk138 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk138, "husk");
	    this.spawnEntity(husk138, world, 121, -19, 70, start);
	    CreatureEntity husk139 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk139, "husk");
	    this.spawnEntity(husk139, world, 121, -19, 74, start);
	    CreatureEntity skeleton140 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton140, "skeleton");
	    this.spawnEntity(skeleton140, world, 122, -49, 33, start);
	    CreatureEntity skeleton141 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton141, "skeleton");
	    this.spawnEntity(skeleton141, world, 122, -49, 43, start);
	    CreatureEntity skeleton142 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton142, "skeleton");
	    this.spawnEntity(skeleton142, world, 122, -40, 79, start);
	    this.generateChest(world, Direction.NORTH, 122, -39, 81, start, 3);
	    CreatureEntity skeleton143 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton143, "skeleton");
	    this.spawnEntity(skeleton143, world, 123, -19, 38, start);
	    CreatureEntity skeleton144 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton144, "skeleton");
	    this.spawnEntity(skeleton144, world, 124, -9, 38, start);
	    CreatureEntity zombie145 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie145, "zombie");
	    this.spawnEntity(zombie145, world, 125, -50, -27, start);
	    CreatureEntity troll146 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:troll")).create(world);
	    this.setItemsForEntity(troll146, "troll");
	    this.spawnEntity(troll146, world, 125, -50, 17, start);
	    this.generateChest(world, Direction.SOUTH, 125, -49, -29, start, 3);
	    CreatureEntity troll147 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:troll")).create(world);
	    this.setItemsForEntity(troll147, "troll");
	    this.spawnEntity(troll147, world, 125, -49, 65, start);
	    CreatureEntity skeleton148 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton148, "skeleton");
	    this.spawnEntity(skeleton148, world, 125, -40, 55, start);
	    this.generateChest(world, Direction.WEST, 125, -18, 72, start, 2);
	    this.generateChest(world, Direction.WEST, 126, -8, 38, start, 2);
	    CreatureEntity skeleton149 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton149, "skeleton");
	    this.spawnEntity(skeleton149, world, 127, -40, 60, start);
	    CreatureEntity skeleton150 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton150, "skeleton");
	    this.spawnEntity(skeleton150, world, 127, -40, 71, start);
	    CreatureEntity skeleton151 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton151, "skeleton");
	    this.spawnEntity(skeleton151, world, 127, -40, 77, start);
	    CreatureEntity skeleton152 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton152, "skeleton");
	    this.spawnEntity(skeleton152, world, 128, -49, 33, start);
	    CreatureEntity skeleton153 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton153, "skeleton");
	    this.spawnEntity(skeleton153, world, 128, -49, 43, start);
	    this.generateChest(world, Direction.SOUTH, 129, 9, 51, start, 2);
	    this.generateChest(world, Direction.NORTH, 129, 9, 86, start, 2);
	    CreatureEntity zombie154 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie154, "zombie");
	    this.spawnEntity(zombie154, world, 130, -50, -25, start);
	    CreatureEntity zombie155 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie155, "zombie");
	    this.spawnEntity(zombie155, world, 130, -50, -19, start);
	    CreatureEntity skeleton156 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton156, "skeleton");
	    this.spawnEntity(skeleton156, world, 130, -49, 35, start);
	    CreatureEntity skeleton157 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton157, "skeleton");
	    this.spawnEntity(skeleton157, world, 130, -49, 41, start);
	    CreatureEntity skeleton158 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton158, "skeleton");
	    this.spawnEntity(skeleton158, world, 132, -40, 43, start);
	    CreatureEntity skeleton159 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton159, "skeleton");
	    this.spawnEntity(skeleton159, world, 132, -40, 57, start);
	    CreatureEntity skeleton160 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton160, "skeleton");
	    this.spawnEntity(skeleton160, world, 132, -40, 63, start);
	    CreatureEntity skeleton161 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton161, "skeleton");
	    this.spawnEntity(skeleton161, world, 134, -40, 33, start);
	    CreatureEntity skeleton162 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton162, "skeleton");
	    this.spawnEntity(skeleton162, world, 137, -40, 65, start);
	    this.generateChest(world, Direction.NORTH, 137, -39, 67, start, 3);
	    CreatureEntity zombie163 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie163, "zombie");
	    this.spawnEntity(zombie163, world, 138, -49, 18, start);
	    CreatureEntity skeleton164 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton164, "skeleton");
	    this.spawnEntity(skeleton164, world, 140, -40, 33, start);
	    CreatureEntity skeleton165 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton165, "skeleton");
	    this.spawnEntity(skeleton165, world, 142, -40, 43, start);
	    CreatureEntity skeleton166 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton166, "skeleton");
	    this.spawnEntity(skeleton166, world, 142, -40, 57, start);
	    CreatureEntity skeleton167 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton167, "skeleton");
	    this.spawnEntity(skeleton167, world, 142, -40, 63, start);
	    CreatureEntity zombie168 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie168, "zombie");
	    this.spawnEntity(zombie168, world, 144, -49, 18, start);
	    CreatureEntity skeleton169 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton169, "skeleton");
	    this.spawnEntity(skeleton169, world, 144, -19, 25, start);
	    CreatureEntity husk170 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk170, "husk");
	    this.spawnEntity(husk170, world, 144, -19, 38, start);
	    CreatureEntity skeleton171 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton171, "skeleton");
	    this.spawnEntity(skeleton171, world, 144, -19, 60, start);
	    this.generateChest(world, Direction.SOUTH, 144, -18, 23, start, 1);
	    this.generateChest(world, Direction.NORTH, 144, -18, 62, start, 1);
	    CreatureEntity skeleton172 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton172, "skeleton");
	    this.spawnEntity(skeleton172, world, 144, -9, 65, start);
	    CreatureEntity skeleton173 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton173, "skeleton");
	    this.spawnEntity(skeleton173, world, 144, -9, 71, start);
	    this.generateChest(world, Direction.WEST, 149, 9, 68, start, 3);
	    CreatureEntity zombie174 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie174, "zombie");
	    this.spawnEntity(zombie174, world, 150, -49, 18, start);
	    CreatureEntity skeleton175 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton175, "skeleton");
	    this.spawnEntity(skeleton175, world, 151, -50, 70, start);
	    CreatureEntity skeleton176 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton176, "skeleton");
	    this.spawnEntity(skeleton176, world, 152, -50, 60, start);
	    this.generateChest(world, Direction.WEST, 153, -38, 38, start, 2);
	    CreatureEntity husk177 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk177, "husk");
	    this.spawnEntity(husk177, world, 154, -49, 32, start);
	    CreatureEntity husk178 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk178, "husk");
	    this.spawnEntity(husk178, world, 154, -49, 44, start);
	    CreatureEntity zombie179 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie179, "zombie");
	    this.spawnEntity(zombie179, world, 156, -49, 18, start);
	    this.generateChest(world, Direction.WEST, 156, -8, 68, start, 2);
	    CreatureEntity skeleton180 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton180, "skeleton");
	    this.spawnEntity(skeleton180, world, 157, -50, 60, start);
	    CreatureEntity skeleton181 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton181, "skeleton");
	    this.spawnEntity(skeleton181, world, 157, -50, 70, start);
	    CreatureEntity skeleton182 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton182, "skeleton");
	    this.spawnEntity(skeleton182, world, 159, -50, 65, start);
	    this.generateChest(world, Direction.WEST, 160, -48, 38, start, 3);
	    CreatureEntity zombie183 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie183, "zombie");
	    this.spawnEntity(zombie183, world, 161, -49, 18, start);
	    this.generateChest(world, Direction.WEST, 161, -49, 65, start, 3);
	    this.generateChest(world, Direction.WEST, 165, -48, 18, start, 3);
	    CreatureEntity skeleton184 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton184, "skeleton");
	    this.spawnEntity(skeleton184, world, 168, -49, 15, start);
	    CreatureEntity skeleton185 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton185, "skeleton");
	    this.spawnEntity(skeleton185, world, 168, -49, 21, start);
	    this.executeCommand(world);
	}

}
