package mod.arcalitegames.odyssey.world.structure.structures.camps.illager_camp;

import java.util.Objects;

import mod.arcalitegames.odyssey.world.structure.StructureBase;
import mod.arcalitegames.system.parser.EntityParser;
import net.minecraft.block.Blocks;
import net.minecraft.entity.CreatureEntity;
import net.minecraft.util.Direction;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;

public class IllagerCamp extends StructureBase {

	public IllagerCamp(World worldIn, BlockPos origin, int xRange, int yRange, int zRange)
	{
		super(worldIn, origin, xRange, yRange, zRange);
		IllagerComponent0.init(world, origin, this);
		IllagerComponent1.init(world, origin, this);
	}

	@Override
	public void addEntitiesAndSpawn()
	{
	    CreatureEntity pillager385 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager385, "pillager");
	    this.spawnEntity(pillager385, world, 14, 7, 17, start);
	    CreatureEntity pillager386 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager386, "pillager");
	    this.spawnEntity(pillager386, world, 14, 7, 103, start);
	    CreatureEntity vindicator387 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator387, "vindicator");
	    this.spawnEntity(vindicator387, world, 15, 7, 58, start);
	    CreatureEntity vindicator388 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator388, "vindicator");
	    this.spawnEntity(vindicator388, world, 15, 7, 62, start);
	    CreatureEntity pillager389 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager389, "pillager");
	    this.spawnEntity(pillager389, world, 16, 18, 20, start);
	    CreatureEntity pillager390 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager390, "pillager");
	    this.spawnEntity(pillager390, world, 17, 15, 20, start);
	    CreatureEntity vindicator391 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator391, "vindicator");
	    this.spawnEntity(vindicator391, world, 17, 15, 40, start);
	    CreatureEntity vindicator392 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator392, "vindicator");
	    this.spawnEntity(vindicator392, world, 17, 15, 80, start);
	    CreatureEntity pillager393 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager393, "pillager");
	    this.spawnEntity(pillager393, world, 17, 15, 100, start);
	    CreatureEntity pillager394 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager394, "pillager");
	    this.spawnEntity(pillager394, world, 17, 16, 60, start);
	    CreatureEntity pillager395 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager395, "pillager");
	    this.spawnEntity(pillager395, world, 17, 18, 101, start);
	    CreatureEntity vindicator396 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator396, "vindicator");
	    this.spawnEntity(vindicator396, world, 19, 9, 58, start);
	    CreatureEntity vindicator397 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator397, "vindicator");
	    this.spawnEntity(vindicator397, world, 19, 9, 62, start);
	    this.generateChest(world, Direction.EAST, 22, 9, 29, start, 1);
	    CreatureEntity evoker398 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:evoker")).create(world);
	    this.setItemsForEntity(evoker398, "evoker");
	    this.spawnEntity(evoker398, world, 23, 9, 67, start);
	    CreatureEntity vindicator399 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator399, "vindicator");
	    this.spawnEntity(vindicator399, world, 24, 9, 28, start);
	    CreatureEntity evoker400 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:evoker")).create(world);
	    this.setItemsForEntity(evoker400, "evoker");
	    this.spawnEntity(evoker400, world, 24, 9, 36, start);
	    CreatureEntity vindicator401 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator401, "vindicator");
	    this.spawnEntity(vindicator401, world, 24, 9, 45, start);
	    CreatureEntity evoker402 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:evoker")).create(world);
	    this.setItemsForEntity(evoker402, "evoker");
	    this.spawnEntity(evoker402, world, 24, 9, 53, start);
	    CreatureEntity vindicator403 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator403, "vindicator");
	    this.spawnEntity(vindicator403, world, 24, 9, 75, start);
	    CreatureEntity ravager404 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:ravager")).create(world);
	    this.setItemsForEntity(ravager404, "ravager");
	    this.spawnEntity(ravager404, world, 27, 9, 60, start);
	    this.generateChest(world, Direction.SOUTH, 30, 9, 64, start, 1);
	    CreatureEntity evoker405 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:evoker")).create(world);
	    this.setItemsForEntity(evoker405, "evoker");
	    this.spawnEntity(evoker405, world, 31, 9, 27, start);
	    CreatureEntity vindicator406 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator406, "vindicator");
	    this.spawnEntity(vindicator406, world, 31, 9, 37, start);
	    CreatureEntity vindicator407 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator407, "vindicator");
	    this.spawnEntity(vindicator407, world, 31, 9, 44, start);
	    CreatureEntity vindicator408 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator408, "vindicator");
	    this.spawnEntity(vindicator408, world, 31, 9, 54, start);
	    CreatureEntity vindicator409 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator409, "vindicator");
	    this.spawnEntity(vindicator409, world, 31, 9, 66, start);
	    CreatureEntity evoker410 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:evoker")).create(world);
	    this.setItemsForEntity(evoker410, "evoker");
	    this.spawnEntity(evoker410, world, 31, 9, 77, start);
	    CreatureEntity vindicator411 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator411, "vindicator");
	    this.spawnEntity(vindicator411, world, 31, 15, 100, start);
	    this.generateChest(world, Direction.SOUTH, 32, 9, 42, start, 1);
	    CreatureEntity vindicator412 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator412, "vindicator");
	    this.spawnEntity(vindicator412, world, 37, 15, 20, start);
	    CreatureEntity evoker413 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:evoker")).create(world);
	    this.setItemsForEntity(evoker413, "evoker");
	    this.spawnEntity(evoker413, world, 39, 9, 27, start);
	    CreatureEntity evoker414 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:evoker")).create(world);
	    this.setItemsForEntity(evoker414, "evoker");
	    this.spawnEntity(evoker414, world, 39, 9, 54, start);
	    CreatureEntity vindicator415 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator415, "vindicator");
	    this.spawnEntity(vindicator415, world, 39, 9, 65, start);
	    CreatureEntity evoker416 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:evoker")).create(world);
	    this.setItemsForEntity(evoker416, "evoker");
	    this.spawnEntity(evoker416, world, 39, 9, 77, start);
	    this.generateChest(world, Direction.SOUTH, 47, 9, 32, start, 1);
	    this.generateChest(world, Direction.NORTH, 47, 9, 38, start, 1);
	    CreatureEntity vindicator417 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator417, "vindicator");
	    this.spawnEntity(vindicator417, world, 48, 9, 35, start);
	    CreatureEntity evoker418 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:evoker")).create(world);
	    this.setItemsForEntity(evoker418, "evoker");
	    this.spawnEntity(evoker418, world, 49, 9, 43, start);
	    CreatureEntity vindicator419 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator419, "vindicator");
	    this.spawnEntity(vindicator419, world, 51, 9, 27, start);
	    CreatureEntity pillager420 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager420, "pillager");
	    this.spawnEntity(pillager420, world, 51, 15, 100, start);
	    CreatureEntity pillager421 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager421, "pillager");
	    this.spawnEntity(pillager421, world, 51, 18, 100, start);
	    CreatureEntity evoker422 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:evoker")).create(world);
	    this.setItemsForEntity(evoker422, "evoker");
	    this.spawnEntity(evoker422, world, 52, 9, 60, start);
	    CreatureEntity vindicator423 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator423, "vindicator");
	    this.spawnEntity(vindicator423, world, 53, 7, 103, start);
	    CreatureEntity vindicator424 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator424, "vindicator");
	    this.spawnEntity(vindicator424, world, 53, 9, 97, start);
	    CreatureEntity vindicator425 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator425, "vindicator");
	    this.spawnEntity(vindicator425, world, 55, 7, 18, start);
	    CreatureEntity vindicator426 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator426, "vindicator");
	    this.spawnEntity(vindicator426, world, 55, 9, 22, start);
	    CreatureEntity evoker427 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:evoker")).create(world);
	    this.setItemsForEntity(evoker427, "evoker");
	    this.spawnEntity(evoker427, world, 57, 6, 65, start);
	    CreatureEntity ravager428 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:ravager")).create(world);
	    this.setItemsForEntity(ravager428, "ravager");
	    this.spawnEntity(ravager428, world, 57, 9, 35, start);
	    CreatureEntity evoker429 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:evoker")).create(world);
	    this.setItemsForEntity(evoker429, "evoker");
	    this.spawnEntity(evoker429, world, 57, 9, 55, start);
	    CreatureEntity ravager430 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:ravager")).create(world);
	    this.setItemsForEntity(ravager430, "ravager");
	    this.spawnEntity(ravager430, world, 57, 9, 88, start);
	    CreatureEntity pillager431 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager431, "pillager");
	    this.spawnEntity(pillager431, world, 57, 16, 20, start);
	    CreatureEntity illusioner432 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:illusioner")).create(world);
	    this.setItemsForEntity(illusioner432, "illusioner");
	    this.spawnEntity(illusioner432, world, 57, 23, 60, start);
	    this.generateChest(world, Direction.SOUTH, 57, 28, 60, start, 3);
	    CreatureEntity vindicator433 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator433, "vindicator");
	    this.spawnEntity(vindicator433, world, 59, 7, 18, start);
	    CreatureEntity vindicator434 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator434, "vindicator");
	    this.spawnEntity(vindicator434, world, 59, 9, 22, start);
	    CreatureEntity vindicator435 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator435, "vindicator");
	    this.spawnEntity(vindicator435, world, 61, 7, 103, start);
	    CreatureEntity evoker436 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:evoker")).create(world);
	    this.setItemsForEntity(evoker436, "evoker");
	    this.spawnEntity(evoker436, world, 61, 9, 60, start);
	    CreatureEntity vindicator437 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator437, "vindicator");
	    this.spawnEntity(vindicator437, world, 61, 9, 97, start);
	    CreatureEntity pillager438 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager438, "pillager");
	    this.spawnEntity(pillager438, world, 63, 15, 100, start);
	    CreatureEntity pillager439 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager439, "pillager");
	    this.spawnEntity(pillager439, world, 63, 18, 100, start);
	    CreatureEntity vindicator440 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator440, "vindicator");
	    this.spawnEntity(vindicator440, world, 65, 9, 26, start);
	    CreatureEntity vindicator441 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator441, "vindicator");
	    this.spawnEntity(vindicator441, world, 65, 9, 44, start);
	    CreatureEntity evoker442 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:evoker")).create(world);
	    this.setItemsForEntity(evoker442, "evoker");
	    this.spawnEntity(evoker442, world, 67, 9, 36, start);
	    this.generateChest(world, Direction.SOUTH, 74, 9, 64, start, 2);
	    CreatureEntity evoker443 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:evoker")).create(world);
	    this.setItemsForEntity(evoker443, "evoker");
	    this.spawnEntity(evoker443, world, 75, 9, 26, start);
	    CreatureEntity vindicator444 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator444, "vindicator");
	    this.spawnEntity(vindicator444, world, 75, 9, 54, start);
	    CreatureEntity vindicator445 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator445, "vindicator");
	    this.spawnEntity(vindicator445, world, 75, 9, 66, start);
	    CreatureEntity vindicator446 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator446, "vindicator");
	    this.spawnEntity(vindicator446, world, 75, 9, 77, start);
	    CreatureEntity vindicator447 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator447, "vindicator");
	    this.spawnEntity(vindicator447, world, 77, 15, 20, start);
	    CreatureEntity vindicator448 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator448, "vindicator");
	    this.spawnEntity(vindicator448, world, 77, 15, 100, start);
	    this.generateChest(world, Direction.SOUTH, 82, 9, 42, start, 1);
	    this.generateChest(world, Direction.NORTH, 82, 9, 78, start, 2);
	    CreatureEntity vindicator449 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator449, "vindicator");
	    this.spawnEntity(vindicator449, world, 83, 9, 26, start);
	    CreatureEntity evoker450 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:evoker")).create(world);
	    this.setItemsForEntity(evoker450, "evoker");
	    this.spawnEntity(evoker450, world, 83, 9, 44, start);
	    CreatureEntity vindicator451 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator451, "vindicator");
	    this.spawnEntity(vindicator451, world, 83, 9, 55, start);
	    CreatureEntity evoker452 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:evoker")).create(world);
	    this.setItemsForEntity(evoker452, "evoker");
	    this.spawnEntity(evoker452, world, 83, 9, 66, start);
	    CreatureEntity vindicator453 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator453, "vindicator");
	    this.spawnEntity(vindicator453, world, 83, 9, 77, start);
	    CreatureEntity ravager454 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:ravager")).create(world);
	    this.setItemsForEntity(ravager454, "ravager");
	    this.spawnEntity(ravager454, world, 87, 9, 60, start);
	    CreatureEntity evoker455 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:evoker")).create(world);
	    this.setItemsForEntity(evoker455, "evoker");
	    this.spawnEntity(evoker455, world, 90, 9, 75, start);
	    CreatureEntity evoker456 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:evoker")).create(world);
	    this.setItemsForEntity(evoker456, "evoker");
	    this.spawnEntity(evoker456, world, 91, 9, 28, start);
	    CreatureEntity vindicator457 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator457, "vindicator");
	    this.spawnEntity(vindicator457, world, 91, 9, 36, start);
	    CreatureEntity evoker458 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:evoker")).create(world);
	    this.setItemsForEntity(evoker458, "evoker");
	    this.spawnEntity(evoker458, world, 91, 9, 45, start);
	    CreatureEntity vindicator459 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator459, "vindicator");
	    this.spawnEntity(vindicator459, world, 91, 9, 53, start);
	    CreatureEntity vindicator460 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator460, "vindicator");
	    this.spawnEntity(vindicator460, world, 91, 9, 67, start);
	    CreatureEntity vindicator461 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator461, "vindicator");
	    this.spawnEntity(vindicator461, world, 95, 9, 58, start);
	    CreatureEntity vindicator462 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator462, "vindicator");
	    this.spawnEntity(vindicator462, world, 95, 9, 62, start);
	    CreatureEntity pillager463 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager463, "pillager");
	    this.spawnEntity(pillager463, world, 97, 15, 20, start);
	    CreatureEntity vindicator464 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator464, "vindicator");
	    this.spawnEntity(vindicator464, world, 97, 15, 40, start);
	    CreatureEntity vindicator465 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator465, "vindicator");
	    this.spawnEntity(vindicator465, world, 97, 15, 80, start);
	    CreatureEntity pillager466 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager466, "pillager");
	    this.spawnEntity(pillager466, world, 97, 15, 100, start);
	    CreatureEntity pillager467 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager467, "pillager");
	    this.spawnEntity(pillager467, world, 97, 16, 60, start);
	    CreatureEntity pillager468 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager468, "pillager");
	    this.spawnEntity(pillager468, world, 97, 18, 21, start);
	    CreatureEntity pillager469 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager469, "pillager");
	    this.spawnEntity(pillager469, world, 97, 18, 101, start);
	    CreatureEntity vindicator470 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator470, "vindicator");
	    this.spawnEntity(vindicator470, world, 99, 7, 58, start);
	    CreatureEntity vindicator471 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:vindicator")).create(world);
	    this.setItemsForEntity(vindicator471, "vindicator");
	    this.spawnEntity(vindicator471, world, 99, 7, 62, start);
	    CreatureEntity pillager472 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager472, "pillager");
	    this.spawnEntity(pillager472, world, 100, 7, 17, start);
	    CreatureEntity pillager473 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:pillager")).create(world);
	    this.setItemsForEntity(pillager473, "pillager");
	    this.spawnEntity(pillager473, world, 100, 7, 103, start);
	    this.executeCommand(world);
	}

}
