package mod.arcalitegames.odyssey.world.structure.structures.dungeons.desert_pyramid;

import java.util.Objects;

import mod.arcalitegames.odyssey.world.structure.StructureBase;
import mod.arcalitegames.system.parser.EntityParser;
import net.minecraft.block.Blocks;
import net.minecraft.entity.CreatureEntity;
import net.minecraft.util.Direction;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;

public class DesertPyramid extends StructureBase
{

	public DesertPyramid(World worldIn, BlockPos origin, int xRange, int yRange, int zRange)
	{
		super(worldIn, origin, xRange, yRange, zRange);
		PyramidComponent0.init(world, origin, this);
		PyramidComponent1.init(world, origin, this);
		PyramidComponent2.init(world, origin, this);
		PyramidComponent3.init(world, origin, this);
        this.fillWithBlocks(world, start, -83, 50, 27, -52, 83, 57, Blocks.AIR.getDefaultState());
	}

	@Override
	public void addEntitiesAndSpawn()
	{
	    this.generateChest(world, Direction.EAST, -54, -49, -9, start, 3);
	    this.generateChest(world, Direction.EAST, -51, -39, -9, start, 3);
	    CreatureEntity skeleton188 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton188, "skeleton");
	    this.spawnEntity(skeleton188, world, -49, -40, -9, start);
	    CreatureEntity skeleton189 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton189, "skeleton");
	    this.spawnEntity(skeleton189, world, -47, -40, -14, start);
	    CreatureEntity skeleton190 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton190, "skeleton");
	    this.spawnEntity(skeleton190, world, -47, -40, -4, start);
	    this.generateChest(world, Direction.EAST, -46, -28, -37, start, 1);
	    this.generateChest(world, Direction.EAST, -46, -28, -15, start, 1);
	    CreatureEntity skeleton191 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton191, "skeleton");
	    this.spawnEntity(skeleton191, world, -45, -29, -15, start);
	    CreatureEntity troll192 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:troll")).create(world);
	    this.setItemsForEntity(troll192, "troll");
	    this.spawnEntity(troll192, world, -44, -49, -9, start);
	    CreatureEntity skeleton193 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton193, "skeleton");
	    this.spawnEntity(skeleton193, world, -44, -29, -32, start);
	    this.generateChest(world, Direction.EAST, -43, -18, -9, start, 2);
	    CreatureEntity skeleton194 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton194, "skeleton");
	    this.spawnEntity(skeleton194, world, -41, -40, -14, start);
	    CreatureEntity skeleton195 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton195, "skeleton");
	    this.spawnEntity(skeleton195, world, -41, -40, -4, start);
	    CreatureEntity zombie196 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie196, "zombie");
	    this.spawnEntity(zombie196, world, -38, -29, -20, start);
	    this.generateChest(world, Direction.NORTH, -38, -28, -9, start, 2);
	    this.generateChest(world, Direction.EAST, -38, -28, 8, start, 2);
	    CreatureEntity skeleton197 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton197, "skeleton");
	    this.spawnEntity(skeleton197, world, -38, -19, -9, start);
	    this.generateChest(world, Direction.EAST, -37, -39, -26, start, 1);
	    CreatureEntity skeleton198 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton198, "skeleton");
	    this.spawnEntity(skeleton198, world, -37, -39, -9, start);
	    CreatureEntity zombie199 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie199, "zombie");
	    this.spawnEntity(zombie199, world, -37, -29, -43, start);
	    CreatureEntity zombie200 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie200, "zombie");
	    this.spawnEntity(zombie200, world, -35, -29, -40, start);
	    CreatureEntity zombie201 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie201, "zombie");
	    this.spawnEntity(zombie201, world, -35, -29, 8, start);
	    CreatureEntity skeleton202 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton202, "skeleton");
	    this.spawnEntity(skeleton202, world, -34, -40, 5, start);
	    CreatureEntity skeleton203 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton203, "skeleton");
	    this.spawnEntity(skeleton203, world, -34, -40, 11, start);
	    CreatureEntity skeleton204 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton204, "skeleton");
	    this.spawnEntity(skeleton204, world, -32, -29, -32, start);
	    CreatureEntity zombie205 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie205, "zombie");
	    this.spawnEntity(zombie205, world, -32, -29, -26, start);
	    this.generateChest(world, Direction.SOUTH, -32, -28, -51, start, 1);
	    this.generateChest(world, Direction.SOUTH, -32, -28, 0, start, 1);
	    this.generateChest(world, Direction.NORTH, -32, -28, 16, start, 1);
	    CreatureEntity zombie206 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie206, "zombie");
	    this.spawnEntity(zombie206, world, -31, -39, -26, start);
	    CreatureEntity skeleton207 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton207, "skeleton");
	    this.spawnEntity(skeleton207, world, -30, -40, 12, start);
	    this.generateChest(world, Direction.SOUTH, -30, -39, -33, start, 1);
	    CreatureEntity zombie208 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie208, "zombie");
	    this.spawnEntity(zombie208, world, -30, -39, -27, start);
	    CreatureEntity zombie209 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie209, "zombie");
	    this.spawnEntity(zombie209, world, -30, -39, -26, start);
	    CreatureEntity zombie210 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie210, "zombie");
	    this.spawnEntity(zombie210, world, -30, -39, -25, start);
	    CreatureEntity skeleton211 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton211, "skeleton");
	    this.spawnEntity(skeleton211, world, -30, -39, 0, start);
	    this.generateChest(world, Direction.NORTH, -30, -39, 15, start, 3);
	    this.generateChest(world, Direction.WEST, -30, -28, -15, start, 1);
	    CreatureEntity zombie212 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie212, "zombie");
	    this.spawnEntity(zombie212, world, -29, -39, -26, start);
	    CreatureEntity skeleton213 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton213, "skeleton");
	    this.spawnEntity(skeleton213, world, -26, -40, 5, start);
	    CreatureEntity skeleton214 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton214, "skeleton");
	    this.spawnEntity(skeleton214, world, -26, -40, 11, start);
	    CreatureEntity zombie215 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie215, "zombie");
	    this.spawnEntity(zombie215, world, -25, -19, -11, start);
	    CreatureEntity zombie216 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie216, "zombie");
	    this.spawnEntity(zombie216, world, -25, -19, -7, start);
	    this.generateChest(world, Direction.EAST, -25, -18, -26, start, 1);
	    CreatureEntity skeleton217 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton217, "skeleton");
	    this.spawnEntity(skeleton217, world, -24, -19, 16, start);
	    this.generateChest(world, Direction.NORTH, -24, -18, 21, start, 1);
	    this.generateChest(world, Direction.WEST, -23, -39, -26, start, 1);
	    CreatureEntity skeleton218 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton218, "skeleton");
	    this.spawnEntity(skeleton218, world, -23, -29, 3, start);
	    CreatureEntity zombie219 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie219, "zombie");
	    this.spawnEntity(zombie219, world, -23, -19, -26, start);
	    CreatureEntity husk220 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk220, "husk");
	    this.spawnEntity(husk220, world, -21, -29, -19, start);
	    CreatureEntity husk221 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk221, "husk");
	    this.spawnEntity(husk221, world, -21, -19, -11, start);
	    CreatureEntity husk222 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk222, "husk");
	    this.spawnEntity(husk222, world, -21, -19, -7, start);
	    CreatureEntity skeleton223 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton223, "skeleton");
	    this.spawnEntity(skeleton223, world, -20, -39, -9, start);
	    CreatureEntity skeleton224 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton224, "skeleton");
	    this.spawnEntity(skeleton224, world, -19, -29, 3, start);
	    this.generateChest(world, Direction.EAST, -13, -49, 25, start, 2);
	    CreatureEntity skeleton225 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton225, "skeleton");
	    this.spawnEntity(skeleton225, world, -11, -9, -11, start);
	    CreatureEntity skeleton226 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton226, "skeleton");
	    this.spawnEntity(skeleton226, world, -11, -9, -7, start);
	    this.generateChest(world, Direction.EAST, -11, -8, -9, start, 2);
	    CreatureEntity skeleton227 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton227, "skeleton");
	    this.spawnEntity(skeleton227, world, -10, -29, 1, start);
	    CreatureEntity skeleton228 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton228, "skeleton");
	    this.spawnEntity(skeleton228, world, -10, -29, 15, start);
	    this.generateChest(world, Direction.SOUTH, -10, -28, 0, start, 1);
	    this.generateChest(world, Direction.NORTH, -10, -28, 16, start, 1);
	    this.generateChest(world, Direction.EAST, -9, -38, -31, start, 1);
	    CreatureEntity zombie229 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie229, "zombie");
	    this.spawnEntity(zombie229, world, -9, -29, -43, start);
	    CreatureEntity zombie230 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie230, "zombie");
	    this.spawnEntity(zombie230, world, -8, -39, -31, start);
	    CreatureEntity troll231 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:troll")).create(world);
	    this.setItemsForEntity(troll231, "troll");
	    this.spawnEntity(troll231, world, -6, -49, -9, start);
	    CreatureEntity troll232 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:troll")).create(world);
	    this.setItemsForEntity(troll232, "troll");
	    this.spawnEntity(troll232, world, -6, -49, 24, start);
	    this.generateChest(world, Direction.NORTH, -6, -49, 32, start, 2);
	    this.generateChest(world, Direction.SOUTH, -6, -48, -26, start, 3);
	    CreatureEntity skeleton233 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton233, "skeleton");
	    this.spawnEntity(skeleton233, world, -4, -29, -49, start);
	    CreatureEntity husk234 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk234, "husk");
	    this.spawnEntity(husk234, world, -4, -29, -26, start);
	    CreatureEntity skeleton235 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton235, "skeleton");
	    this.spawnEntity(skeleton235, world, -4, -19, -26, start);
	    CreatureEntity skeleton236 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton236, "skeleton");
	    this.spawnEntity(skeleton236, world, -4, -19, 26, start);
	    this.generateChest(world, Direction.NORTH, -4, -18, 28, start, 1);
	    CreatureEntity skeleton237 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton237, "skeleton");
	    this.spawnEntity(skeleton237, world, -1, -39, 35, start);
	    this.generateChest(world, Direction.SOUTH, -1, -38, -37, start, 2);
	    this.generateChest(world, Direction.NORTH, -1, -38, 36, start, 1);
	    this.generateChest(world, Direction.WEST, 1, -49, 25, start, 2);
	    CreatureEntity zombie238 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie238, "zombie");
	    this.spawnEntity(zombie238, world, 1, -29, -43, start);
	    CreatureEntity husk239 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk239, "husk");
	    this.spawnEntity(husk239, world, 2, -29, 3, start);
	    CreatureEntity husk240 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk240, "husk");
	    this.spawnEntity(husk240, world, 2, -29, 6, start);
	    CreatureEntity husk241 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk241, "husk");
	    this.spawnEntity(husk241, world, 2, -29, 10, start);
	    CreatureEntity husk242 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk242, "husk");
	    this.spawnEntity(husk242, world, 2, -29, 13, start);
	    this.generateChest(world, Direction.SOUTH, 2, -28, 0, start, 1);
	    this.generateChest(world, Direction.NORTH, 2, -28, 16, start, 1);
	    this.generateChest(world, Direction.EAST, 5, -49, 18, start, 2);
	    CreatureEntity zombie243 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie243, "zombie");
	    this.spawnEntity(zombie243, world, 5, -39, 7, start);
	    CreatureEntity zombie244 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie244, "zombie");
	    this.spawnEntity(zombie244, world, 5, -39, 18, start);
	    CreatureEntity zombie245 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie245, "zombie");
	    this.spawnEntity(zombie245, world, 6, -39, -31, start);
	    this.generateChest(world, Direction.WEST, 7, -38, -31, start, 1);
	    CreatureEntity husk246 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk246, "husk");
	    this.spawnEntity(husk246, world, 9, -9, -9, start);
	    CreatureEntity zombie247 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie247, "zombie");
	    this.spawnEntity(zombie247, world, 10, -39, 36, start);
	    this.generateChest(world, Direction.SOUTH, 12, -49, 11, start, 2);
	    CreatureEntity troll248 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:troll")).create(world);
	    this.setItemsForEntity(troll248, "troll");
	    this.spawnEntity(troll248, world, 12, -49, 18, start);
	    this.generateChest(world, Direction.NORTH, 12, -49, 25, start, 2);
	    CreatureEntity skeleton249 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton249, "skeleton");
	    this.spawnEntity(skeleton249, world, 13, -39, 13, start);
	    this.generateChest(world, Direction.NORTH, 13, -38, 36, start, 2);
	    CreatureEntity zombie250 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie250, "zombie");
	    this.spawnEntity(zombie250, world, 13, -29, -25, start);
	    CreatureEntity zombie251 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie251, "zombie");
	    this.spawnEntity(zombie251, world, 13, -29, -14, start);
	    CreatureEntity skeleton252 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton252, "skeleton");
	    this.spawnEntity(skeleton252, world, 13, -29, 1, start);
	    CreatureEntity skeleton253 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton253, "skeleton");
	    this.spawnEntity(skeleton253, world, 13, -29, 15, start);
	    this.generateChest(world, Direction.WEST, 13, -28, -43, start, 1);
	    this.generateChest(world, Direction.WEST, 13, -28, 8, start, 3);
	    this.generateChest(world, Direction.EAST, 14, -49, -29, start, 1);
	    CreatureEntity zombie254 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie254, "zombie");
	    this.spawnEntity(zombie254, world, 16, -39, 36, start);
	    CreatureEntity husk255 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk255, "husk");
	    this.spawnEntity(husk255, world, 17, 7, 32, start);
	    CreatureEntity husk256 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk256, "husk");
	    this.spawnEntity(husk256, world, 18, 8, 21, start);
	    this.generateChest(world, Direction.EAST, 19, -49, -64, start, 2);
	    CreatureEntity skeleton257 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton257, "skeleton");
	    this.spawnEntity(skeleton257, world, 19, -49, -40, start);
	    CreatureEntity skeleton258 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton258, "skeleton");
	    this.spawnEntity(skeleton258, world, 19, -9, 84, start);
	    CreatureEntity skeleton259 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton259, "skeleton");
	    this.spawnEntity(skeleton259, world, 20, -29, 8, start);
	    CreatureEntity skeleton260 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton260, "skeleton");
	    this.spawnEntity(skeleton260, world, 21, -40, -54, start);
	    CreatureEntity skeleton261 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton261, "skeleton");
	    this.spawnEntity(skeleton261, world, 21, -40, -48, start);
	    CreatureEntity skeleton262 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton262, "skeleton");
	    this.spawnEntity(skeleton262, world, 21, -19, 8, start);
	    CreatureEntity husk263 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk263, "husk");
	    this.spawnEntity(husk263, world, 21, -19, 38, start);
	    CreatureEntity husk264 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk264, "husk");
	    this.spawnEntity(husk264, world, 21, -19, 50, start);
	    CreatureEntity skeleton265 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton265, "skeleton");
	    this.spawnEntity(skeleton265, world, 21, -19, 62, start);
	    this.generateChest(world, Direction.NORTH, 21, -18, 64, start, 1);
	    CreatureEntity zombie266 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie266, "zombie");
	    this.spawnEntity(zombie266, world, 21, -9, -25, start);
	    CreatureEntity husk267 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk267, "husk");
	    this.spawnEntity(husk267, world, 21, -9, -4, start);
	    CreatureEntity husk268 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk268, "husk");
	    this.spawnEntity(husk268, world, 21, -9, 55, start);
	    this.generateChest(world, Direction.NORTH, 21, -8, 84, start, 2);
	    CreatureEntity husk269 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk269, "husk");
	    this.spawnEntity(husk269, world, 21, 8, 17, start);
	    CreatureEntity zombie270 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie270, "zombie");
	    this.spawnEntity(zombie270, world, 23, -49, -43, start);
	    CreatureEntity zombie271 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie271, "zombie");
	    this.spawnEntity(zombie271, world, 23, -49, -37, start);
	    CreatureEntity skeleton272 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton272, "skeleton");
	    this.spawnEntity(skeleton272, world, 23, -9, 84, start);
	    CreatureEntity zombie273 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie273, "zombie");
	    this.spawnEntity(zombie273, world, 24, -39, 19, start);
	    CreatureEntity husk274 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk274, "husk");
	    this.spawnEntity(husk274, world, 24, 7, 32, start);
	    CreatureEntity husk275 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk275, "husk");
	    this.spawnEntity(husk275, world, 24, 8, 21, start);
	    CreatureEntity husk276 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk276, "husk");
	    this.spawnEntity(husk276, world, 25, -19, -28, start);
	    CreatureEntity husk277 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk277, "husk");
	    this.spawnEntity(husk277, world, 25, -19, -24, start);
	    this.generateChest(world, Direction.SOUTH, 26, -49, -71, start, 2);
	    CreatureEntity troll278 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:troll")).create(world);
	    this.setItemsForEntity(troll278, "troll");
	    this.spawnEntity(troll278, world, 26, -49, -63, start);
	    CreatureEntity zombie279 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie279, "zombie");
	    this.spawnEntity(zombie279, world, 26, -49, -16, start);
	    CreatureEntity skeleton280 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton280, "skeleton");
	    this.spawnEntity(skeleton280, world, 26, -40, -56, start);
	    this.generateChest(world, Direction.SOUTH, 26, -39, -58, start, 3);
	    CreatureEntity zombie281 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie281, "zombie");
	    this.spawnEntity(zombie281, world, 26, -39, -38, start);
	    CreatureEntity zombie282 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie282, "zombie");
	    this.spawnEntity(zombie282, world, 26, -39, -28, start);
	    CreatureEntity zombie283 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie283, "zombie");
	    this.spawnEntity(zombie283, world, 26, -39, -16, start);
	    this.generateChest(world, Direction.NORTH, 26, -38, 22, start, 2);
	    CreatureEntity zombie284 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie284, "zombie");
	    this.spawnEntity(zombie284, world, 28, -39, 19, start);
	    this.generateChest(world, Direction.WEST, 28, -18, -26, start, 2);
	    CreatureEntity zombie285 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie285, "zombie");
	    this.spawnEntity(zombie285, world, 29, -49, -43, start);
	    CreatureEntity zombie286 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie286, "zombie");
	    this.spawnEntity(zombie286, world, 29, -49, -37, start);
	    CreatureEntity husk287 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk287, "husk");
	    this.spawnEntity(husk287, world, 30, -9, 21, start);
	    CreatureEntity skeleton288 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton288, "skeleton");
	    this.spawnEntity(skeleton288, world, 31, -40, -54, start);
	    CreatureEntity skeleton289 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton289, "skeleton");
	    this.spawnEntity(skeleton289, world, 31, -40, -48, start);
	    this.generateChest(world, Direction.WEST, 33, -49, -64, start, 2);
	    CreatureEntity skeleton290 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton290, "skeleton");
	    this.spawnEntity(skeleton290, world, 33, -49, -40, start);
	    CreatureEntity husk291 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk291, "husk");
	    this.spawnEntity(husk291, world, 33, -9, -9, start);
	    CreatureEntity skeleton292 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton292, "skeleton");
	    this.spawnEntity(skeleton292, world, 36, -40, 18, start);
	    CreatureEntity skeleton293 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton293, "skeleton");
	    this.spawnEntity(skeleton293, world, 36, -40, 24, start);
	    CreatureEntity skeleton294 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton294, "skeleton");
	    this.spawnEntity(skeleton294, world, 36, -40, 30, start);
	    CreatureEntity skeleton295 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton295, "skeleton");
	    this.spawnEntity(skeleton295, world, 36, -9, -25, start);
	    CreatureEntity skeleton296 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton296, "skeleton");
	    this.spawnEntity(skeleton296, world, 38, -40, 8, start);
	    CreatureEntity skeleton297 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton297, "skeleton");
	    this.spawnEntity(skeleton297, world, 38, -19, 19, start);
	    CreatureEntity skeleton298 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton298, "skeleton");
	    this.spawnEntity(skeleton298, world, 38, -19, 31, start);
	    this.generateChest(world, Direction.WEST, 38, -8, -25, start, 1);
	    CreatureEntity zombie299 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie299, "zombie");
	    this.spawnEntity(zombie299, world, 39, -50, -72, start);
	    CreatureEntity zombie300 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie300, "zombie");
	    this.spawnEntity(zombie300, world, 39, -50, -66, start);
	    CreatureEntity skeleton301 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton301, "skeleton");
	    this.spawnEntity(skeleton301, world, 39, -49, -12, start);
	    CreatureEntity skeleton302 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton302, "skeleton");
	    this.spawnEntity(skeleton302, world, 39, -49, -6, start);
	    CreatureEntity husk303 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk303, "husk");
	    this.spawnEntity(husk303, world, 40, -19, 23, start);
	    CreatureEntity husk304 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk304, "husk");
	    this.spawnEntity(husk304, world, 40, -19, 27, start);
	    CreatureEntity skeleton305 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton305, "skeleton");
	    this.spawnEntity(skeleton305, world, 41, -49, -14, start);
	    CreatureEntity skeleton306 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton306, "skeleton");
	    this.spawnEntity(skeleton306, world, 41, -49, -4, start);
	    CreatureEntity skeleton307 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton307, "skeleton");
	    this.spawnEntity(skeleton307, world, 41, -40, 32, start);
	    this.generateChest(world, Direction.NORTH, 41, -39, 34, start, 3);
	    CreatureEntity skeleton308 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton308, "skeleton");
	    this.spawnEntity(skeleton308, world, 42, -19, -9, start);
	    CreatureEntity skeleton309 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton309, "skeleton");
	    this.spawnEntity(skeleton309, world, 43, -9, -9, start);
	    CreatureEntity zombie310 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie310, "zombie");
	    this.spawnEntity(zombie310, world, 44, -50, -74, start);
	    CreatureEntity troll311 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:troll")).create(world);
	    this.setItemsForEntity(troll311, "troll");
	    this.spawnEntity(troll311, world, 44, -50, -30, start);
	    this.generateChest(world, Direction.SOUTH, 44, -49, -76, start, 3);
	    CreatureEntity troll312 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:troll")).create(world);
	    this.setItemsForEntity(troll312, "troll");
	    this.spawnEntity(troll312, world, 44, -49, 18, start);
	    CreatureEntity skeleton313 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton313, "skeleton");
	    this.spawnEntity(skeleton313, world, 44, -40, 8, start);
	    this.generateChest(world, Direction.WEST, 44, -18, 25, start, 2);
	    this.generateChest(world, Direction.WEST, 45, -8, -9, start, 2);
	    CreatureEntity skeleton314 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton314, "skeleton");
	    this.spawnEntity(skeleton314, world, 46, -40, 13, start);
	    CreatureEntity skeleton315 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton315, "skeleton");
	    this.spawnEntity(skeleton315, world, 46, -40, 24, start);
	    CreatureEntity skeleton316 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton316, "skeleton");
	    this.spawnEntity(skeleton316, world, 46, -40, 30, start);
	    CreatureEntity skeleton317 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton317, "skeleton");
	    this.spawnEntity(skeleton317, world, 47, -49, -14, start);
	    CreatureEntity skeleton318 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton318, "skeleton");
	    this.spawnEntity(skeleton318, world, 47, -49, -4, start);
	    CreatureEntity zombie319 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie319, "zombie");
	    this.spawnEntity(zombie319, world, 49, -50, -72, start);
	    CreatureEntity zombie320 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie320, "zombie");
	    this.spawnEntity(zombie320, world, 49, -50, -66, start);
	    CreatureEntity skeleton321 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton321, "skeleton");
	    this.spawnEntity(skeleton321, world, 49, -49, -12, start);
	    CreatureEntity skeleton322 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton322, "skeleton");
	    this.spawnEntity(skeleton322, world, 49, -49, -6, start);
	    CreatureEntity skeleton323 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton323, "skeleton");
	    this.spawnEntity(skeleton323, world, 51, -40, -4, start);
	    CreatureEntity skeleton324 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton324, "skeleton");
	    this.spawnEntity(skeleton324, world, 51, -40, 10, start);
	    CreatureEntity skeleton325 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton325, "skeleton");
	    this.spawnEntity(skeleton325, world, 51, -40, 16, start);
	    CreatureEntity skeleton326 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton326, "skeleton");
	    this.spawnEntity(skeleton326, world, 53, -40, -14, start);
	    CreatureEntity skeleton327 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton327, "skeleton");
	    this.spawnEntity(skeleton327, world, 56, -40, 18, start);
	    this.generateChest(world, Direction.NORTH, 56, -39, 20, start, 3);
	    CreatureEntity zombie328 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie328, "zombie");
	    this.spawnEntity(zombie328, world, 57, -49, -29, start);
	    CreatureEntity skeleton329 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton329, "skeleton");
	    this.spawnEntity(skeleton329, world, 59, -40, -14, start);
	    CreatureEntity skeleton330 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton330, "skeleton");
	    this.spawnEntity(skeleton330, world, 61, -40, -4, start);
	    CreatureEntity skeleton331 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton331, "skeleton");
	    this.spawnEntity(skeleton331, world, 61, -40, 10, start);
	    CreatureEntity skeleton332 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton332, "skeleton");
	    this.spawnEntity(skeleton332, world, 61, -40, 16, start);
	    CreatureEntity zombie333 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie333, "zombie");
	    this.spawnEntity(zombie333, world, 63, -49, -29, start);
	    CreatureEntity skeleton334 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton334, "skeleton");
	    this.spawnEntity(skeleton334, world, 63, -19, -22, start);
	    CreatureEntity husk335 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk335, "husk");
	    this.spawnEntity(husk335, world, 63, -19, -9, start);
	    CreatureEntity skeleton336 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton336, "skeleton");
	    this.spawnEntity(skeleton336, world, 63, -19, 13, start);
	    this.generateChest(world, Direction.SOUTH, 63, -18, -24, start, 1);
	    this.generateChest(world, Direction.NORTH, 63, -18, 15, start, 1);
	    CreatureEntity skeleton337 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton337, "skeleton");
	    this.spawnEntity(skeleton337, world, 63, -9, 18, start);
	    CreatureEntity skeleton338 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton338, "skeleton");
	    this.spawnEntity(skeleton338, world, 63, -9, 24, start);
	    CreatureEntity zombie339 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie339, "zombie");
	    this.spawnEntity(zombie339, world, 69, -49, -29, start);
	    CreatureEntity skeleton340 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton340, "skeleton");
	    this.spawnEntity(skeleton340, world, 70, -50, 23, start);
	    CreatureEntity skeleton341 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton341, "skeleton");
	    this.spawnEntity(skeleton341, world, 71, -50, 13, start);
	    this.generateChest(world, Direction.WEST, 72, -38, -9, start, 2);
	    CreatureEntity husk342 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk342, "husk");
	    this.spawnEntity(husk342, world, 73, -49, -15, start);
	    CreatureEntity husk343 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:husk")).create(world);
	    this.setItemsForEntity(husk343, "husk");
	    this.spawnEntity(husk343, world, 73, -49, -3, start);
	    CreatureEntity zombie344 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie344, "zombie");
	    this.spawnEntity(zombie344, world, 75, -49, -29, start);
	    this.generateChest(world, Direction.WEST, 75, -8, 21, start, 2);
	    CreatureEntity skeleton345 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton345, "skeleton");
	    this.spawnEntity(skeleton345, world, 76, -50, 13, start);
	    CreatureEntity skeleton346 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton346, "skeleton");
	    this.spawnEntity(skeleton346, world, 76, -50, 23, start);
	    CreatureEntity skeleton347 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton347, "skeleton");
	    this.spawnEntity(skeleton347, world, 78, -50, 18, start);
	    this.generateChest(world, Direction.WEST, 79, -48, -9, start, 3);
	    CreatureEntity zombie348 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:zombie")).create(world);
	    this.setItemsForEntity(zombie348, "zombie");
	    this.spawnEntity(zombie348, world, 80, -49, -29, start);
	    this.generateChest(world, Direction.WEST, 80, -49, 18, start, 3);
	    this.generateChest(world, Direction.WEST, 84, -48, -29, start, 3);
	    CreatureEntity skeleton349 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton349, "skeleton");
	    this.spawnEntity(skeleton349, world, 87, -49, -32, start);
	    CreatureEntity skeleton350 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:skeleton")).create(world);
	    this.setItemsForEntity(skeleton350, "skeleton");
	    this.spawnEntity(skeleton350, world, 87, -49, -26, start);
	    this.executeCommand(world);
	}

}
