package mod.arcalitegames.odyssey.world.structure.structures.forts.neograd;

import java.util.Objects;

import mod.arcalitegames.odyssey.world.structure.StructureBase;
import mod.arcalitegames.system.parser.EntityParser;
import net.minecraft.block.Blocks;
import net.minecraft.entity.CreatureEntity;
import net.minecraft.util.Direction;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;

public class FortNeograd extends StructureBase
{

	public FortNeograd(World worldIn, BlockPos origin, int xRange, int yRange, int zRange)
	{
		super(worldIn, origin, xRange, yRange, zRange);
		NeogradComponent0.init(world, origin, this);
		NeogradComponent1.init(world, origin, this);
        this.fillWithBlocks(world, start, 12, 6, 8, 116, 66, 126, Blocks.AIR.getDefaultState());
	}

	@Override
	public void addEntitiesAndSpawn()
	{
	    CreatureEntity bandit_plunderer1 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit_plunderer")).create(world);
	    this.setItemsForEntity(bandit_plunderer1, "bandit_plunderer");
	    this.spawnEntity(bandit_plunderer1, world, 19, 25, 69, start);
	    CreatureEntity bandit2 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit")).create(world);
	    this.setItemsForEntity(bandit2, "bandit");
	    this.spawnEntity(bandit2, world, 26, 7, 83, start);
	    this.generateChest(world, Direction.EAST, 26, 25, 59, start, 1);
	    CreatureEntity bandit3 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit")).create(world);
	    this.setItemsForEntity(bandit3, "bandit");
	    this.spawnEntity(bandit3, world, 27, 15, 78, start);
	    this.generateChest(world, Direction.EAST, 29, 15, 57, start, 1);
	    CreatureEntity bandit_outlaw4 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit_outlaw")).create(world);
	    this.setItemsForEntity(bandit_outlaw4, "bandit_outlaw");
	    this.spawnEntity(bandit_outlaw4, world, 29, 25, 59, start);
	    CreatureEntity bandit_outlaw5 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit_outlaw")).create(world);
	    this.setItemsForEntity(bandit_outlaw5, "bandit_outlaw");
	    this.spawnEntity(bandit_outlaw5, world, 30, 15, 66, start);
	    this.generateChest(world, Direction.SOUTH, 30, 33, 57, start, 3);
	    CreatureEntity bandit6 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit")).create(world);
	    this.setItemsForEntity(bandit6, "bandit");
	    this.spawnEntity(bandit6, world, 31, 7, 88, start);
	    CreatureEntity bandit7 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit")).create(world);
	    this.setItemsForEntity(bandit7, "bandit");
	    this.spawnEntity(bandit7, world, 31, 15, 55, start);
	    CreatureEntity bandit_plunderer8 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit_plunderer")).create(world);
	    this.setItemsForEntity(bandit_plunderer8, "bandit_plunderer");
	    this.spawnEntity(bandit_plunderer8, world, 31, 33, 57, start);
	    CreatureEntity bandit9 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit")).create(world);
	    this.setItemsForEntity(bandit9, "bandit");
	    this.spawnEntity(bandit9, world, 33, 15, 35, start);
	    this.generateChest(world, Direction.EAST, 39, 7, 34, start, 1);
	    CreatureEntity bandit_thug10 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit_thug")).create(world);
	    this.setItemsForEntity(bandit_thug10, "bandit_thug");
	    this.spawnEntity(bandit_thug10, world, 40, 7, 65, start);
	    this.generateChest(world, Direction.SOUTH, 41, 33, 88, start, 2);
	    CreatureEntity bandit11 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit")).create(world);
	    this.setItemsForEntity(bandit11, "bandit");
	    this.spawnEntity(bandit11, world, 43, 25, 92, start);
	    CreatureEntity bandit_plunderer12 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit_plunderer")).create(world);
	    this.setItemsForEntity(bandit_plunderer12, "bandit_plunderer");
	    this.spawnEntity(bandit_plunderer12, world, 43, 33, 92, start);
	    this.generateChest(world, Direction.EAST, 45, 25, 118, start, 1);
	    CreatureEntity bandit_thug13 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit_thug")).create(world);
	    this.setItemsForEntity(bandit_thug13, "bandit_thug");
	    this.spawnEntity(bandit_thug13, world, 47, 7, 42, start);
	    this.generateChest(world, Direction.EAST, 47, 25, 15, start, 1);
	    CreatureEntity bandit_thug14 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit_thug")).create(world);
	    this.setItemsForEntity(bandit_thug14, "bandit_thug");
	    this.spawnEntity(bandit_thug14, world, 47, 25, 119, start);
	    CreatureEntity bandit_outlaw15 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit_outlaw")).create(world);
	    this.setItemsForEntity(bandit_outlaw15, "bandit_outlaw");
	    this.spawnEntity(bandit_outlaw15, world, 49, 15, 19, start);
	    CreatureEntity bandit16 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit")).create(world);
	    this.setItemsForEntity(bandit16, "bandit");
	    this.spawnEntity(bandit16, world, 49, 15, 112, start);
	    CreatureEntity bandit_outlaw17 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit_outlaw")).create(world);
	    this.setItemsForEntity(bandit_outlaw17, "bandit_outlaw");
	    this.spawnEntity(bandit_outlaw17, world, 49, 25, 15, start);
	    CreatureEntity bandit18 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit")).create(world);
	    this.setItemsForEntity(bandit18, "bandit");
	    this.spawnEntity(bandit18, world, 50, 16, 96, start);
	    this.generateChest(world, Direction.SOUTH, 56, 7, 76, start, 1);
	    CreatureEntity bandit_outlaw19 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit_outlaw")).create(world);
	    this.setItemsForEntity(bandit_outlaw19, "bandit_outlaw");
	    this.spawnEntity(bandit_outlaw19, world, 59, 15, 15, start);
	    CreatureEntity bandit20 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit")).create(world);
	    this.setItemsForEntity(bandit20, "bandit");
	    this.spawnEntity(bandit20, world, 61, 7, 11, start);
	    CreatureEntity bandit21 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit")).create(world);
	    this.setItemsForEntity(bandit21, "bandit");
	    this.spawnEntity(bandit21, world, 61, 7, 77, start);
	    CreatureEntity bandit22 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit")).create(world);
	    this.setItemsForEntity(bandit22, "bandit");
	    this.spawnEntity(bandit22, world, 61, 7, 87, start);
	    CreatureEntity bandit_outlaw23 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit_outlaw")).create(world);
	    this.setItemsForEntity(bandit_outlaw23, "bandit_outlaw");
	    this.spawnEntity(bandit_outlaw23, world, 62, 7, 34, start);
	    this.generateChest(world, Direction.SOUTH, 66, 7, 36, start, 2);
	    CreatureEntity bandit_thug24 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit_thug")).create(world);
	    this.setItemsForEntity(bandit_thug24, "bandit_thug");
	    this.spawnEntity(bandit_thug24, world, 66, 15, 95, start);
	    CreatureEntity bandit25 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit")).create(world);
	    this.setItemsForEntity(bandit25, "bandit");
	    this.spawnEntity(bandit25, world, 68, 7, 11, start);
	    CreatureEntity bandit_outlaw26 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit_outlaw")).create(world);
	    this.setItemsForEntity(bandit_outlaw26, "bandit_outlaw");
	    this.spawnEntity(bandit_outlaw26, world, 69, 15, 15, start);
	    CreatureEntity bandit_outlaw27 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit_outlaw")).create(world);
	    this.setItemsForEntity(bandit_outlaw27, "bandit_outlaw");
	    this.spawnEntity(bandit_outlaw27, world, 71, 8, 54, start);
	    CreatureEntity bandit_outlaw28 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit_outlaw")).create(world);
	    this.setItemsForEntity(bandit_outlaw28, "bandit_outlaw");
	    this.spawnEntity(bandit_outlaw28, world, 71, 8, 58, start);
	    CreatureEntity bandit_thug29 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit_thug")).create(world);
	    this.setItemsForEntity(bandit_thug29, "bandit_thug");
	    this.spawnEntity(bandit_thug29, world, 78, 23, 17, start);
	    this.generateChest(world, Direction.WEST, 81, 23, 15, start, 1);
	    this.generateChest(world, Direction.EAST, 82, 8, 72, start, 2);
	    this.generateChest(world, Direction.NORTH, 83, 8, 68, start, 1);
	    CreatureEntity bandit_outlaw30 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit_outlaw")).create(world);
	    this.setItemsForEntity(bandit_outlaw30, "bandit_outlaw");
	    this.spawnEntity(bandit_outlaw30, world, 83, 15, 56, start);
	    CreatureEntity bandit_plunderer31 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit_plunderer")).create(world);
	    this.setItemsForEntity(bandit_plunderer31, "bandit_plunderer");
	    this.spawnEntity(bandit_plunderer31, world, 86, 8, 75, start);
	    CreatureEntity bandit32 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit")).create(world);
	    this.setItemsForEntity(bandit32, "bandit");
	    this.spawnEntity(bandit32, world, 86, 9, 53, start);
	    CreatureEntity bandit33 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit")).create(world);
	    this.setItemsForEntity(bandit33, "bandit");
	    this.spawnEntity(bandit33, world, 86, 9, 58, start);
	    CreatureEntity bandit_outlaw34 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit_outlaw")).create(world);
	    this.setItemsForEntity(bandit_outlaw34, "bandit_outlaw");
	    this.spawnEntity(bandit_outlaw34, world, 88, 15, 27, start);
	    this.generateChest(world, Direction.EAST, 88, 20, 56, start, 3);
	    CreatureEntity bandit35 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit")).create(world);
	    this.setItemsForEntity(bandit35, "bandit");
	    this.spawnEntity(bandit35, world, 89, 15, 95, start);
	    CreatureEntity bandit_thug36 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit_thug")).create(world);
	    this.setItemsForEntity(bandit_thug36, "bandit_thug");
	    this.spawnEntity(bandit_thug36, world, 89, 25, 97, start);
	    this.generateChest(world, Direction.SOUTH, 90, 22, 51, start, 1);
	    CreatureEntity bandit_marauder37 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit_marauder")).create(world);
	    this.setItemsForEntity(bandit_marauder37, "bandit_marauder");
	    this.spawnEntity(bandit_marauder37, world, 91, 16, 56, start);
	    CreatureEntity bandit38 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit")).create(world);
	    this.setItemsForEntity(bandit38, "bandit");
	    this.spawnEntity(bandit38, world, 94, 15, 45, start);
	    this.generateChest(world, Direction.WEST, 94, 25, 95, start, 1);
	    CreatureEntity bandit39 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit")).create(world);
	    this.setItemsForEntity(bandit39, "bandit");
	    this.spawnEntity(bandit39, world, 98, 8, 36, start);
	    this.generateChest(world, Direction.NORTH, 102, 9, 49, start, 1);
	    CreatureEntity bandit_plunderer40 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit_plunderer")).create(world);
	    this.setItemsForEntity(bandit_plunderer40, "bandit_plunderer");
	    this.spawnEntity(bandit_plunderer40, world, 102, 24, 43, start);
	    CreatureEntity bandit_thug41 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit_thug")).create(world);
	    this.setItemsForEntity(bandit_thug41, "bandit_thug");
	    this.spawnEntity(bandit_thug41, world, 103, 8, 74, start);
	    this.generateChest(world, Direction.SOUTH, 103, 9, 44, start, 1);
	    CreatureEntity bandit42 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit")).create(world);
	    this.setItemsForEntity(bandit42, "bandit");
	    this.spawnEntity(bandit42, world, 103, 15, 70, start);
	    CreatureEntity bandit43 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit")).create(world);
	    this.setItemsForEntity(bandit43, "bandit");
	    this.spawnEntity(bandit43, world, 103, 15, 72, start);
	    this.generateChest(world, Direction.NORTH, 104, 11, 38, start, 1);
	    CreatureEntity bandit_plunderer44 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit_plunderer")).create(world);
	    this.setItemsForEntity(bandit_plunderer44, "bandit_plunderer");
	    this.spawnEntity(bandit_plunderer44, world, 104, 12, 56, start);
	    CreatureEntity bandit45 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit")).create(world);
	    this.setItemsForEntity(bandit45, "bandit");
	    this.spawnEntity(bandit45, world, 105, 8, 36, start);
	    this.generateChest(world, Direction.NORTH, 105, 11, 49, start, 1);
	    CreatureEntity bandit_outlaw46 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit_outlaw")).create(world);
	    this.setItemsForEntity(bandit_outlaw46, "bandit_outlaw");
	    this.spawnEntity(bandit_outlaw46, world, 106, 8, 46, start);
	    this.generateChest(world, Direction.NORTH, 107, 9, 49, start, 1);
	    this.generateChest(world, Direction.SOUTH, 107, 11, 44, start, 1);
	    CreatureEntity bandit_outlaw47 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:bandit_outlaw")).create(world);
	    this.setItemsForEntity(bandit_outlaw47, "bandit_outlaw");
	    this.spawnEntity(bandit_outlaw47, world, 108, 8, 41, start);
	    this.generateChest(world, Direction.WEST, 108, 25, 44, start, 2);
	    this.generateChest(world, Direction.WEST, 110, 11, 47, start, 1);
	    this.generateChest(world, Direction.WEST, 110, 32, 56, start, 2);
	    this.executeCommand(world);
	}

}
