package mod.arcalitegames.odyssey.world.structure.structures.dungeons.highguard_castle;

import java.util.Objects;

import mod.arcalitegames.odyssey.world.structure.StructureBase;
import mod.arcalitegames.system.parser.EntityParser;
import net.minecraft.block.Blocks;
import net.minecraft.entity.CreatureEntity;
import net.minecraft.util.Direction;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;

public class HighguardCastle extends StructureBase
{

	public HighguardCastle(World worldIn, BlockPos origin, int xRange, int yRange, int zRange)
	{
		super(worldIn, origin, xRange, yRange, zRange);
		HighguardComponent0.init(world, origin, this);
		HighguardComponent1.init(world, origin, this);
		HighguardComponent2.init(world, origin, this);
		HighguardComponent3.init(world, origin, this);
		HighguardComponent4.init(world, origin, this);
		HighguardComponent5.init(world, origin, this);
		HighguardComponent6.init(world, origin, this);
		HighguardComponent7.init(world, origin, this);
		HighguardComponent8.init(world, origin, this);
        this.fillWithBlocks(world, start, 9, 5, 12, 71, 81, 78, Blocks.AIR.getDefaultState());
	}

	@Override
	public void addEntitiesAndSpawn()
	{
	    this.generateChest(world, Direction.EAST, -48, -25, 44, start, 1);
	    this.generateChest(world, Direction.SOUTH, -43, -25, 39, start, 1);
	    CreatureEntity dread_knight105 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight105, "dread_knight");
	    this.spawnEntity(dread_knight105, world, -43, -25, 42, start);
	    CreatureEntity dread_knight106 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight106, "dread_knight");
	    this.spawnEntity(dread_knight106, world, -43, -25, 46, start);
	    this.generateChest(world, Direction.NORTH, -43, -25, 49, start, 1);
	    this.generateChest(world, Direction.EAST, -30, -15, 44, start, 1);
	    this.generateChest(world, Direction.EAST, -27, -44, 14, start, 3);
	    this.generateChest(world, Direction.EAST, -27, -25, 14, start, 2);
	    this.generateChest(world, Direction.EAST, -26, -25, 94, start, 2);
	    this.generateChest(world, Direction.SOUTH, -25, -15, 39, start, 1);
	    this.generateChest(world, Direction.NORTH, -25, -15, 49, start, 1);
	    this.generateChest(world, Direction.EAST, -25, -14, 44, start, 2);
	    CreatureEntity dread_knight107 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight107, "dread_knight");
	    this.spawnEntity(dread_knight107, world, -23, -35, -26, start);
	    CreatureEntity dread_knight108 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight108, "dread_knight");
	    this.spawnEntity(dread_knight108, world, -23, -35, -14, start);
	    this.generateChest(world, Direction.SOUTH, -22, -25, 9, start, 1);
	    CreatureEntity dread_lich109 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich109, "dread_lich");
	    this.spawnEntity(dread_lich109, world, -22, -25, 14, start);
	    this.generateChest(world, Direction.NORTH, -22, -25, 19, start, 1);
	    CreatureEntity dread_thrall110 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall110, "dread_thrall");
	    this.spawnEntity(dread_thrall110, world, -21, -25, 76, start);
	    this.generateChest(world, Direction.NORTH, -21, -25, 99, start, 2);
	    CreatureEntity dread_knight111 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight111, "dread_knight");
	    this.spawnEntity(dread_knight111, world, -19, -55, 10, start);
	    CreatureEntity dread_lich112 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich112, "dread_lich");
	    this.spawnEntity(dread_lich112, world, -17, -45, 8, start);
	    CreatureEntity dread_lich113 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich113, "dread_lich");
	    this.spawnEntity(dread_lich113, world, -17, -35, -20, start);
	    CreatureEntity dread_beast114 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_beast")).create(world);
	    this.setItemsForEntity(dread_beast114, "dread_beast");
	    this.spawnEntity(dread_beast114, world, -17, -35, 31, start);
	    this.generateChest(world, Direction.WEST, -16, -25, 94, start, 2);
	    this.generateChest(world, Direction.SOUTH, -13, -55, 4, start, 2);
	    this.generateChest(world, Direction.NORTH, -13, -55, 16, start, 2);
	    CreatureEntity dread_lich115 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich115, "dread_lich");
	    this.spawnEntity(dread_lich115, world, -13, -45, 26, start);
	    CreatureEntity dread_knight116 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight116, "dread_knight");
	    this.spawnEntity(dread_knight116, world, -11, -35, -26, start);
	    CreatureEntity dread_knight117 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight117, "dread_knight");
	    this.spawnEntity(dread_knight117, world, -11, -35, -14, start);
	    CreatureEntity dread_thrall118 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall118, "dread_thrall");
	    this.spawnEntity(dread_thrall118, world, -6, -35, 3, start);
	    this.generateChest(world, Direction.EAST, -6, -25, -13, start, 1);
	    CreatureEntity dread_thrall119 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall119, "dread_thrall");
	    this.spawnEntity(dread_thrall119, world, -6, -15, 37, start);
	    CreatureEntity dread_lich120 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich120, "dread_lich");
	    this.spawnEntity(dread_lich120, world, -6, -15, 44, start);
	    CreatureEntity dread_thrall121 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall121, "dread_thrall");
	    this.spawnEntity(dread_thrall121, world, -6, -15, 51, start);
	    CreatureEntity dread_knight122 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight122, "dread_knight");
	    this.spawnEntity(dread_knight122, world, -5, -45, 8, start);
	    CreatureEntity dread_knight123 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight123, "dread_knight");
	    this.spawnEntity(dread_knight123, world, -5, -45, 20, start);
	    CreatureEntity dread_lich124 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich124, "dread_lich");
	    this.spawnEntity(dread_lich124, world, -1, -35, 31, start);
	    this.generateChest(world, Direction.SOUTH, -1, -25, -18, start, 2);
	    CreatureEntity dread_lich125 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich125, "dread_lich");
	    this.spawnEntity(dread_lich125, world, -1, -25, -13, start);
	    CreatureEntity dread_lich126 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich126, "dread_lich");
	    this.spawnEntity(dread_lich126, world, -1, -25, 14, start);
	    CreatureEntity dread_lich127 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich127, "dread_lich");
	    this.spawnEntity(dread_lich127, world, -1, -25, 44, start);
	    CreatureEntity dread_beast128 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_beast")).create(world);
	    this.setItemsForEntity(dread_beast128, "dread_beast");
	    this.spawnEntity(dread_beast128, world, -1, -25, 76, start);
	    CreatureEntity dread_knight129 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight129, "dread_knight");
	    this.spawnEntity(dread_knight129, world, 0, -35, -3, start);
	    CreatureEntity dread_ghoul130 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul130, "dread_ghoul");
	    this.spawnEntity(dread_ghoul130, world, 0, -35, 14, start);
	    this.generateChest(world, Direction.WEST, 0, -34, -20, start, 3);
	    this.generateChest(world, Direction.EAST, 3, -55, -16, start, 2);
	    this.generateChest(world, Direction.WEST, 4, -25, -13, start, 1);
	    CreatureEntity dread_thrall131 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall131, "dread_thrall");
	    this.spawnEntity(dread_thrall131, world, 6, -35, -9, start);
	    CreatureEntity dread_lich132 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich132, "dread_lich");
	    this.spawnEntity(dread_lich132, world, 6, -35, -3, start);
	    CreatureEntity dread_ghoul133 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul133, "dread_ghoul");
	    this.spawnEntity(dread_ghoul133, world, 6, -35, 3, start);
	    CreatureEntity dread_knight134 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight134, "dread_knight");
	    this.spawnEntity(dread_knight134, world, 7, -45, 40, start);
	    CreatureEntity dread_thrall135 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall135, "dread_thrall");
	    this.spawnEntity(dread_thrall135, world, 7, -45, 41, start);
	    CreatureEntity dread_knight136 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight136, "dread_knight");
	    this.spawnEntity(dread_knight136, world, 7, -45, 42, start);
	    this.generateChest(world, Direction.EAST, 10, -58, 49, start, 3);
	    CreatureEntity dread_lich137 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich137, "dread_lich");
	    this.spawnEntity(dread_lich137, world, 10, -57, 49, start);
	    this.generateChest(world, Direction.EAST, 10, -35, 31, start, 1);
	    this.generateChest(world, Direction.EAST, 10, -25, 104, start, 1);
	    this.generateChest(world, Direction.EAST, 10, -15, 14, start, 1);
	    this.generateChest(world, Direction.EAST, 10, -14, 75, start, 1);
	    this.generateChest(world, Direction.EAST, 11, -45, 4, start, 1);
	    CreatureEntity dread_thrall138 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall138, "dread_thrall");
	    this.spawnEntity(dread_thrall138, world, 11, -45, 20, start);
	    this.generateChest(world, Direction.EAST, 12, -44, -16, start, 1);
	    CreatureEntity dread_knight139 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight139, "dread_knight");
	    this.spawnEntity(dread_knight139, world, 14, -15, 89, start);
	    this.generateChest(world, Direction.NORTH, 14, -14, 96, start, 2);
	    CreatureEntity dread_ghoul140 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul140, "dread_ghoul");
	    this.spawnEntity(dread_ghoul140, world, 15, -25, 52, start);
	    CreatureEntity dread_ghoul141 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul141, "dread_ghoul");
	    this.spawnEntity(dread_ghoul141, world, 15, -25, 74, start);
	    CreatureEntity dread_lich142 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich142, "dread_lich");
	    this.spawnEntity(dread_lich142, world, 15, -25, 104, start);
	    this.generateChest(world, Direction.NORTH, 15, -25, 109, start, 2);
	    this.generateChest(world, Direction.SOUTH, 15, -15, 9, start, 1);
	    CreatureEntity dread_knight143 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight143, "dread_knight");
	    this.spawnEntity(dread_knight143, world, 15, -15, 14, start);
	    CreatureEntity dread_knight144 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight144, "dread_knight");
	    this.spawnEntity(dread_knight144, world, 16, -45, 53, start);
	    CreatureEntity goblin_knocker145 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_knocker")).create(world);
	    this.setItemsForEntity(goblin_knocker145, "goblin_knocker");
	    this.spawnEntity(goblin_knocker145, world, 16, 7, 46, start);
	    CreatureEntity dread_lich146 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich146, "dread_lich");
	    this.spawnEntity(dread_lich146, world, 17, -45, 4, start);
	    CreatureEntity dread_thrall147 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall147, "dread_thrall");
	    this.spawnEntity(dread_thrall147, world, 17, -45, 53, start);
	    this.generateChest(world, Direction.SOUTH, 17, -44, -2, start, 2);
	    CreatureEntity dread_beast148 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_beast")).create(world);
	    this.setItemsForEntity(dread_beast148, "dread_beast");
	    this.spawnEntity(dread_beast148, world, 17, -35, -17, start);
	    CreatureEntity dread_lich149 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich149, "dread_lich");
	    this.spawnEntity(dread_lich149, world, 17, -35, 31, start);
	    this.generateChest(world, Direction.NORTH, 17, -35, 38, start, 1);
	    CreatureEntity dread_lich150 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich150, "dread_lich");
	    this.spawnEntity(dread_lich150, world, 18, -55, -21, start);
	    CreatureEntity dread_beast151 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_beast")).create(world);
	    this.setItemsForEntity(dread_beast151, "dread_beast");
	    this.spawnEntity(dread_beast151, world, 18, -55, 10, start);
	    CreatureEntity dread_knight152 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight152, "dread_knight");
	    this.spawnEntity(dread_knight152, world, 18, -45, 53, start);
	    CreatureEntity goblin_knocker153 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_knocker")).create(world);
	    this.setItemsForEntity(goblin_knocker153, "goblin_knocker");
	    this.spawnEntity(goblin_knocker153, world, 18, 7, 54, start);
	    CreatureEntity dread_knight154 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight154, "dread_knight");
	    this.spawnEntity(dread_knight154, world, 20, -45, -16, start);
	    this.generateChest(world, Direction.WEST, 20, -25, 104, start, 1);
	    this.generateChest(world, Direction.WEST, 20, -15, 14, start, 1);
	    this.generateChest(world, Direction.WEST, 23, -45, 4, start, 1);
	    CreatureEntity dread_knight155 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight155, "dread_knight");
	    this.spawnEntity(dread_knight155, world, 23, -45, 20, start);
	    CreatureEntity dread_knight156 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight156, "dread_knight");
	    this.spawnEntity(dread_knight156, world, 23, -45, 32, start);
	    CreatureEntity dread_knight157 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight157, "dread_knight");
	    this.spawnEntity(dread_knight157, world, 23, -45, 47, start);
	    CreatureEntity goblin_knocker158 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_knocker")).create(world);
	    this.setItemsForEntity(goblin_knocker158, "goblin_knocker");
	    this.spawnEntity(goblin_knocker158, world, 23, 7, 26, start);
	    CreatureEntity goblin_kobold159 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_kobold")).create(world);
	    this.setItemsForEntity(goblin_kobold159, "goblin_kobold");
	    this.spawnEntity(goblin_kobold159, world, 24, 8, 40, start);
	    CreatureEntity dread_knight160 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight160, "dread_knight");
	    this.spawnEntity(dread_knight160, world, 26, -25, 33, start);
	    this.generateChest(world, Direction.SOUTH, 26, -24, 28, start, 2);
	    this.generateChest(world, Direction.EAST, 26, -15, 95, start, 1);
	    CreatureEntity dread_thrall161 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall161, "dread_thrall");
	    this.spawnEntity(dread_thrall161, world, 27, -45, -36, start);
	    CreatureEntity dread_knight162 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight162, "dread_knight");
	    this.spawnEntity(dread_knight162, world, 28, -45, 42, start);
	    CreatureEntity dread_knight163 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight163, "dread_knight");
	    this.spawnEntity(dread_knight163, world, 28, -45, 54, start);
	    CreatureEntity dread_ghoul164 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul164, "dread_ghoul");
	    this.spawnEntity(dread_ghoul164, world, 28, -35, 25, start);
	    CreatureEntity dread_ghoul165 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul165, "dread_ghoul");
	    this.spawnEntity(dread_ghoul165, world, 28, -35, 37, start);
	    this.generateChest(world, Direction.EAST, 30, -44, -4, start, 1);
	    CreatureEntity dread_knight166 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight166, "dread_knight");
	    this.spawnEntity(dread_knight166, world, 30, -35, -24, start);
	    CreatureEntity dread_knight167 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight167, "dread_knight");
	    this.spawnEntity(dread_knight167, world, 30, -35, -16, start);
	    CreatureEntity dread_ghoul168 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul168, "dread_ghoul");
	    this.spawnEntity(dread_ghoul168, world, 31, -15, 75, start);
	    this.generateChest(world, Direction.NORTH, 31, -15, 100, start, 1);
	    CreatureEntity goblin_trow169 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_trow")).create(world);
	    this.setItemsForEntity(goblin_trow169, "goblin_trow");
	    this.spawnEntity(goblin_trow169, world, 31, 7, 44, start);
	    this.generateChest(world, Direction.EAST, 33, -25, -1, start, 1);
	    this.generateChest(world, Direction.EAST, 33, -25, 76, start, 1);
	    this.generateChest(world, Direction.EAST, 33, -25, 96, start, 1);
	    CreatureEntity goblin_kobold170 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_kobold")).create(world);
	    this.setItemsForEntity(goblin_kobold170, "goblin_kobold");
	    this.spawnEntity(goblin_kobold170, world, 33, 9, 51, start);
	    CreatureEntity dread_knight171 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight171, "dread_knight");
	    this.spawnEntity(dread_knight171, world, 34, -45, 8, start);
	    CreatureEntity dread_lich172 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich172, "dread_lich");
	    this.spawnEntity(dread_lich172, world, 34, -45, 66, start);
	    this.generateChest(world, Direction.SOUTH, 34, -44, -42, start, 2);
	    this.generateChest(world, Direction.SOUTH, 34, -34, -20, start, 3);
	    this.generateChest(world, Direction.WEST, 34, -34, 31, start, 2);
	    this.generateChest(world, Direction.WEST, 36, -15, 95, start, 1);
	    CreatureEntity goblin_kobold173 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_kobold")).create(world);
	    this.setItemsForEntity(goblin_kobold173, "goblin_kobold");
	    this.spawnEntity(goblin_kobold173, world, 36, 10, 38, start);
	    CreatureEntity dread_knight174 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight174, "dread_knight");
	    this.spawnEntity(dread_knight174, world, 38, -35, -24, start);
	    CreatureEntity dread_knight175 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight175, "dread_knight");
	    this.spawnEntity(dread_knight175, world, 38, -35, -16, start);
	    this.generateChest(world, Direction.SOUTH, 38, -25, -6, start, 1);
	    CreatureEntity dread_knight176 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight176, "dread_knight");
	    this.spawnEntity(dread_knight176, world, 38, -25, -1, start);
	    CreatureEntity dread_beast177 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_beast")).create(world);
	    this.setItemsForEntity(dread_beast177, "dread_beast");
	    this.spawnEntity(dread_beast177, world, 38, -25, 44, start);
	    CreatureEntity dread_ghoul178 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul178, "dread_ghoul");
	    this.spawnEntity(dread_ghoul178, world, 38, -25, 76, start);
	    CreatureEntity dread_thrall179 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall179, "dread_thrall");
	    this.spawnEntity(dread_thrall179, world, 38, -25, 96, start);
	    this.generateChest(world, Direction.NORTH, 38, -25, 101, start, 1);
	    CreatureEntity dread_thrall180 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall180, "dread_thrall");
	    this.spawnEntity(dread_thrall180, world, 40, -45, 42, start);
	    CreatureEntity dread_knight181 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight181, "dread_knight");
	    this.spawnEntity(dread_knight181, world, 40, -45, 54, start);
	    CreatureEntity dread_thrall182 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall182, "dread_thrall");
	    this.spawnEntity(dread_thrall182, world, 41, -45, -36, start);
	    CreatureEntity dread_thrall183 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall183, "dread_thrall");
	    this.spawnEntity(dread_thrall183, world, 41, -45, 20, start);
	    CreatureEntity dread_knight184 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight184, "dread_knight");
	    this.spawnEntity(dread_knight184, world, 41, -45, 32, start);
	    CreatureEntity goblin_knocker185 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_knocker")).create(world);
	    this.setItemsForEntity(goblin_knocker185, "goblin_knocker");
	    this.spawnEntity(goblin_knocker185, world, 42, 5, 16, start);
	    CreatureEntity hobgoblin186 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_hobgoblin")).create(world);
	    this.setItemsForEntity(hobgoblin186, "hobgoblin");
	    this.spawnEntity(hobgoblin186, world, 42, 14, 59, start);
	    CreatureEntity dread_knight187 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight187, "dread_knight");
	    this.spawnEntity(dread_knight187, world, 43, -58, 45, start);
	    CreatureEntity dread_knight188 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight188, "dread_knight");
	    this.spawnEntity(dread_knight188, world, 43, -58, 53, start);
	    this.generateChest(world, Direction.WEST, 43, -25, -1, start, 1);
	    this.generateChest(world, Direction.WEST, 43, -25, 96, start, 1);
	    CreatureEntity hobgoblin189 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_hobgoblin")).create(world);
	    this.setItemsForEntity(hobgoblin189, "hobgoblin");
	    this.spawnEntity(hobgoblin189, world, 43, 7, 35, start);
	    this.generateChest(world, Direction.SOUTH, 44, -45, -20, start, 2);
	    CreatureEntity goblin_knocker190 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_knocker")).create(world);
	    this.setItemsForEntity(goblin_knocker190, "goblin_knocker");
	    this.spawnEntity(goblin_knocker190, world, 45, 5, 16, start);
	    CreatureEntity hobgoblin191 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_hobgoblin")).create(world);
	    this.setItemsForEntity(hobgoblin191, "hobgoblin");
	    this.spawnEntity(hobgoblin191, world, 45, 12, 28, start);
	    this.generateChest(world, Direction.SOUTH, 47, -57, -50, start, 3);
	    CreatureEntity dread_beast192 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_beast")).create(world);
	    this.setItemsForEntity(dread_beast192, "dread_beast");
	    this.spawnEntity(dread_beast192, world, 47, -56, -50, start);
	    CreatureEntity dread_thrall193 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall193, "dread_thrall");
	    this.spawnEntity(dread_thrall193, world, 47, -55, -16, start);
	    CreatureEntity dread_ghoul194 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul194, "dread_ghoul");
	    this.spawnEntity(dread_ghoul194, world, 47, -55, 2, start);
	    CreatureEntity dread_ghoul195 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul195, "dread_ghoul");
	    this.spawnEntity(dread_ghoul195, world, 47, -55, 18, start);
	    CreatureEntity dread_thrall197 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall197, "dread_thrall");
	    this.spawnEntity(dread_thrall197, world, 47, -55, 71, start);
	    this.generateChest(world, Direction.NORTH, 47, -55, 77, start, 3);
	    CreatureEntity dread_knight198 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight198, "dread_knight");
	    this.spawnEntity(dread_knight198, world, 47, -45, 55, start);
	    this.generateChest(world, Direction.NORTH, 47, -44, 56, start, 2);
	    CreatureEntity hobgoblin199 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_hobgoblin")).create(world);
	    this.setItemsForEntity(hobgoblin199, "hobgoblin");
	    this.spawnEntity(hobgoblin199, world, 47, 9, 59, start);
	    CreatureEntity dread_knight200 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight200, "dread_knight");
	    this.spawnEntity(dread_knight200, world, 51, -58, 45, start);
	    CreatureEntity dread_knight201 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight201, "dread_knight");
	    this.spawnEntity(dread_knight201, world, 51, -58, 53, start);
	    CreatureEntity hobgoblin202 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_hobgoblin")).create(world);
	    this.setItemsForEntity(hobgoblin202, "hobgoblin");
	    this.spawnEntity(hobgoblin202, world, 52, 6, 29, start);
	    CreatureEntity hobgoblin203 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_hobgoblin")).create(world);
	    this.setItemsForEntity(hobgoblin203, "hobgoblin");
	    this.spawnEntity(hobgoblin203, world, 52, 8, 49, start);
	    CreatureEntity dread_knight204 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight204, "dread_knight");
	    this.spawnEntity(dread_knight204, world, 53, -45, 20, start);
	    CreatureEntity dread_thrall205 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall205, "dread_thrall");
	    this.spawnEntity(dread_thrall205, world, 53, -45, 32, start);
	    CreatureEntity goblin_knocker206 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_knocker")).create(world);
	    this.setItemsForEntity(goblin_knocker206, "goblin_knocker");
	    this.spawnEntity(goblin_knocker206, world, 53, 10, 24, start);
	    this.generateChest(world, Direction.WEST, 54, 37, 30, start, 2);
	    CreatureEntity hobgoblin207 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_hobgoblin")).create(world);
	    this.setItemsForEntity(hobgoblin207, "hobgoblin");
	    this.spawnEntity(hobgoblin207, world, 55, 8, 57, start);
	    CreatureEntity goblin_knocker208 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_knocker")).create(world);
	    this.setItemsForEntity(goblin_knocker208, "goblin_knocker");
	    this.spawnEntity(goblin_knocker208, world, 55, 8, 66, start);
	    CreatureEntity dread_ghoul209 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul209, "dread_ghoul");
	    this.spawnEntity(dread_ghoul209, world, 56, -15, 44, start);
	    CreatureEntity goblin_knocker210 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_knocker")).create(world);
	    this.setItemsForEntity(goblin_knocker210, "goblin_knocker");
	    this.spawnEntity(goblin_knocker210, world, 56, 6, 21, start);
	    CreatureEntity dread_knight211 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight211, "dread_knight");
	    this.spawnEntity(dread_knight211, world, 60, -45, 47, start);
	    CreatureEntity dread_thrall212 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall212, "dread_thrall");
	    this.spawnEntity(dread_thrall212, world, 60, -45, 48, start);
	    CreatureEntity dread_knight213 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight213, "dread_knight");
	    this.spawnEntity(dread_knight213, world, 60, -45, 49, start);
	    CreatureEntity goblin_knocker214 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_knocker")).create(world);
	    this.setItemsForEntity(goblin_knocker214, "goblin_knocker");
	    this.spawnEntity(goblin_knocker214, world, 60, 6, 42, start);
	    CreatureEntity dread_beast215 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_beast")).create(world);
	    this.setItemsForEntity(dread_beast215, "dread_beast");
	    this.spawnEntity(dread_beast215, world, 63, -45, -16, start);
	    CreatureEntity dread_knight216 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight216, "dread_knight");
	    this.spawnEntity(dread_knight216, world, 63, -25, 26, start);
	    CreatureEntity dread_lich217 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich217, "dread_lich");
	    this.spawnEntity(dread_lich217, world, 63, -25, 44, start);
	    this.generateChest(world, Direction.SOUTH, 63, -24, 18, start, 2);
	    CreatureEntity goblin_knocker218 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:goblin_knocker")).create(world);
	    this.setItemsForEntity(goblin_knocker218, "goblin_knocker");
	    this.spawnEntity(goblin_knocker218, world, 64, 6, 32, start);
	    this.generateChest(world, Direction.WEST, 69, -58, 49, start, 3);
	    CreatureEntity dread_beast219 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_beast")).create(world);
	    this.setItemsForEntity(dread_beast219, "dread_beast");
	    this.spawnEntity(dread_beast219, world, 69, -55, 70, start);
	    this.generateChest(world, Direction.SOUTH, 69, -25, 71, start, 1);
	    CreatureEntity dread_thrall220 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall220, "dread_thrall");
	    this.spawnEntity(dread_thrall220, world, 69, -25, 76, start);
	    this.generateChest(world, Direction.NORTH, 69, -25, 81, start, 1);
	    this.generateChest(world, Direction.WEST, 74, -25, 76, start, 1);
	    this.generateChest(world, Direction.SOUTH, 75, -45, 20, start, 2);
	    CreatureEntity dread_knight221 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight221, "dread_knight");
	    this.spawnEntity(dread_knight221, world, 75, -45, 25, start);
	    CreatureEntity dread_lich222 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich222, "dread_lich");
	    this.spawnEntity(dread_lich222, world, 75, -45, 26, start);
	    CreatureEntity dread_knight223 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight223, "dread_knight");
	    this.spawnEntity(dread_knight223, world, 75, -45, 27, start);
	    this.generateChest(world, Direction.NORTH, 75, -45, 32, start, 2);
	    CreatureEntity dread_ghoul224 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul224, "dread_ghoul");
	    this.spawnEntity(dread_ghoul224, world, 81, -55, -18, start);
	    CreatureEntity dread_ghoul225 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_ghoul")).create(world);
	    this.setItemsForEntity(dread_ghoul225, "dread_ghoul");
	    this.spawnEntity(dread_ghoul225, world, 81, -55, -14, start);
	    this.generateChest(world, Direction.WEST, 81, -45, 26, start, 2);
	    CreatureEntity dread_knight226 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_knight")).create(world);
	    this.setItemsForEntity(dread_knight226, "dread_knight");
	    this.spawnEntity(dread_knight226, world, 86, -25, 44, start);
	    this.generateChest(world, Direction.SOUTH, 89, -15, 39, start, 1);
	    CreatureEntity dread_thrall227 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall227, "dread_thrall");
	    this.spawnEntity(dread_thrall227, world, 89, -15, 42, start);
	    CreatureEntity dread_thrall228 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_thrall")).create(world);
	    this.setItemsForEntity(dread_thrall228, "dread_thrall");
	    this.spawnEntity(dread_thrall228, world, 89, -15, 46, start);
	    this.generateChest(world, Direction.NORTH, 89, -15, 49, start, 1);
	    this.generateChest(world, Direction.WEST, 92, -24, 44, start, 2);
	    this.generateChest(world, Direction.WEST, 94, -15, 44, start, 1);
	    CreatureEntity dread_lich229 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("iceandfire:dread_lich")).create(world);
	    this.setItemsForEntity(dread_lich229, "dread_lich");
	    this.spawnEntity(dread_lich229, world, 99, -55, -16, start);
	    this.executeCommand(world);
	}

}
