package mod.arcalitegames.odyssey.world.structure.town.boromirtown;

import java.util.Objects;

import mod.arcalitegames.odyssey.entity.CounterEntity;
import mod.arcalitegames.odyssey.entity.citizens.boromirtown.guards.BoromirPatrollingGuard;
import mod.arcalitegames.odyssey.entity.citizens.boromirtown.guards.BoromirStandingGuard;
import mod.arcalitegames.odyssey.entity.passive.CitizenEntity;
import mod.arcalitegames.odyssey.entity.passive.MerchantEntity;
import mod.arcalitegames.odyssey.world.structure.town.TownStructure;
import mod.arcalitegames.odyssey.world.structure.town.TownStructures;
import mod.arcalitegames.system.parser.EntityParser;
import net.minecraft.block.Blocks;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;

public class BoromirTown extends TownStructure
{

	public BoromirTown(World worldIn, BlockPos origin, int xRange, int yRange, int zRange)
	{
		super(worldIn, origin, xRange, yRange, zRange);
		BoromirComponent0.init(world, start, this);
		BoromirComponent1.init(world, start, this);
		BoromirComponent2.init(world, start, this);
		BoromirComponent3.init(world, start, this);
        this.fillWithBlocks(world, start, -80, 0, -54, 42, 100, 54, Blocks.AIR.getDefaultState());
        this.fillWithBlocks(world, start, -9, 0, 50, 42, 100, 59, Blocks.AIR.getDefaultState());
        this.fillWithBlocks(world, start, 8, 0, 59, 16, 100, 80, Blocks.AIR.getDefaultState());
        this.fillWithBlocks(world, start, 1, -1, 63, 7, 100, 68, Blocks.AIR.getDefaultState());
        this.fillWithBlocks(world, start, 16, -1, 62, 23, 100, 68, Blocks.AIR.getDefaultState());
	}

	@Override
	public void addEntitiesAndSpawn()
	{
	    MerchantEntity farming_merchant = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:farming_merchant")).create(world);
	    this.setItemsForEntity(farming_merchant, "merchant");
	    this.spawnEntity(farming_merchant, world, -71, 3, -9, start);
	    MerchantEntity alchemist = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:alchemist")).create(world);
	    this.setItemsForEntity(alchemist, "merchant");
	    this.spawnEntity(alchemist, world, -71, 3, 14, start);
	    CounterEntity counter3 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter3, "counter");
	    this.spawnEntity(counter3, world, -71, 4, -10, start);
	    CounterEntity counter4 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter4, "counter");
	    this.spawnEntity(counter4, world, -70, 4, 14, start);
	    BoromirStandingGuard standing_guard5 = (BoromirStandingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:boromir_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard5, "standing_guard");
	    this.spawnEntity(standing_guard5, world, -64, 3, -4, start);
	    CitizenEntity geoff_boeke = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:geoff_boeke")).create(world);
	    this.setItemsForEntity(geoff_boeke, "citizen");
	    this.spawnEntity(geoff_boeke, world, -62, 3, -9, start);
	    CitizenEntity imanie_karge = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:imanie_karge")).create(world);
	    this.setItemsForEntity(imanie_karge, "citizen");
	    this.spawnEntity(imanie_karge, world, -61, 3, -10, start);
	    CitizenEntity perina_yoxalle = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:perina_yoxalle")).create(world);
	    this.setItemsForEntity(perina_yoxalle, "citizen");
	    this.spawnEntity(perina_yoxalle, world, -61, 3, 12, start);
	    BoromirStandingGuard standing_guard9 = (BoromirStandingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:boromir_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard9, "standing_guard");
	    this.spawnEntity(standing_guard9, world, -60, -2, 32, start);
	    BoromirStandingGuard standing_guard10 = (BoromirStandingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:boromir_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard10, "standing_guard");
	    this.spawnEntity(standing_guard10, world, -60, 3, -4, start);
	    BoromirStandingGuard standing_guard11 = (BoromirStandingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:boromir_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard11, "standing_guard");
	    this.spawnEntity(standing_guard11, world, -60, 3, 8, start);
	    CitizenEntity alphaneus_lewin = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:alphaneus_lewin")).create(world);
	    this.setItemsForEntity(alphaneus_lewin, "citizen");
	    this.spawnEntity(alphaneus_lewin, world, -59, 3, 13, start);
	    BoromirStandingGuard standing_guard13 = (BoromirStandingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:boromir_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard13, "standing_guard");
	    this.spawnEntity(standing_guard13, world, -58, 2, -42, start);
	    BoromirPatrollingGuard patrolling_guard14 = (BoromirPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:boromir_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard14, "patrolling_guard");
	    this.spawnEntity(patrolling_guard14, world, -54, 3, -19, start);
	    MerchantEntity redstone_merchant = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:redstone_merchant")).create(world);
	    this.setItemsForEntity(redstone_merchant, "merchant");
	    this.spawnEntity(redstone_merchant, world, -54, 3, 10, start);
	    CounterEntity counter16 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter16, "counter");
	    this.spawnEntity(counter16, world, -53, 4, 10, start);
	    CitizenEntity landon_bakere = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:landon_bakere")).create(world);
	    this.setItemsForEntity(landon_bakere, "citizen");
	    this.spawnEntity(landon_bakere, world, -51, 1, -28, start);
	    BoromirPatrollingGuard patrolling_guard18 = (BoromirPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:boromir_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard18, "patrolling_guard");
	    this.spawnEntity(patrolling_guard18, world, -47, 1, -36, start);
	    CitizenEntity hilditha_bordeaux = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:hilditha_bordeaux")).create(world);
	    this.setItemsForEntity(hilditha_bordeaux, "citizen");
	    this.spawnEntity(hilditha_bordeaux, world, -46, 1, -33, start);
	    CitizenEntity hedley_bakere = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:hedley_bakere")).create(world);
	    this.setItemsForEntity(hedley_bakere, "citizen");
	    this.spawnEntity(hedley_bakere, world, -46, 1, -27, start);
	    BoromirStandingGuard standing_guard21 = (BoromirStandingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:boromir_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard21, "standing_guard");
	    this.spawnEntity(standing_guard21, world, -41, 4, 30, start);
	    BoromirPatrollingGuard patrolling_guard22 = (BoromirPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:boromir_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard22, "patrolling_guard");
	    this.spawnEntity(patrolling_guard22, world, -39, 3, -7, start);
	    BoromirPatrollingGuard patrolling_guard23 = (BoromirPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:boromir_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard23, "patrolling_guard");
	    this.spawnEntity(patrolling_guard23, world, -39, 3, 14, start);
	    MerchantEntity horse_merchant = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:horse_merchant")).create(world);
	    this.setItemsForEntity(horse_merchant, "merchant");
	    this.spawnEntity(horse_merchant, world, -37, 4, -1, start);
	    CitizenEntity gelther_echener = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:gelther_echener")).create(world);
	    this.setItemsForEntity(gelther_echener, "citizen");
	    this.spawnEntity(gelther_echener, world, -36, 3, 20, start);
	    CitizenEntity thaulos_raleigh = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:thaulos_raleigh")).create(world);
	    this.setItemsForEntity(thaulos_raleigh, "citizen");
	    this.spawnEntity(thaulos_raleigh, world, -36, 3, 22, start);
	    CounterEntity counter27 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter27, "counter");
	    this.spawnEntity(counter27, world, -36, 5, -1, start);
	    BoromirPatrollingGuard patrolling_guard28 = (BoromirPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:boromir_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard28, "patrolling_guard");
	    this.spawnEntity(patrolling_guard28, world, -31, 2, 34, start);
	    MerchantEntity mineshop_merchant = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:mineshop_merchant")).create(world);
	    this.setItemsForEntity(mineshop_merchant, "merchant");
	    this.spawnEntity(mineshop_merchant, world, -30, 2, 44, start);
	    BoromirPatrollingGuard patrolling_guard30 = (BoromirPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:boromir_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard30, "patrolling_guard");
	    this.spawnEntity(patrolling_guard30, world, -30, 3, -29, start);
	    CounterEntity counter31 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter31, "counter");
	    this.spawnEntity(counter31, world, -30, 3, 43, start);
	    MerchantEntity decor_merchant = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:decor_merchant")).create(world);
	    this.setItemsForEntity(decor_merchant, "merchant");
	    this.spawnEntity(decor_merchant, world, -29, 3, 16, start);
	    CounterEntity counter33 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter33, "counter");
	    this.spawnEntity(counter33, world, -29, 4, 17, start);
	    MerchantEntity fletching_merchant = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:fletching_merchant")).create(world);
	    this.setItemsForEntity(fletching_merchant, "merchant");
	    this.spawnEntity(fletching_merchant, world, -25, 3, -42, start);
	    CitizenEntity phaestus_hunte = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:phaestus_hunte")).create(world);
	    this.setItemsForEntity(phaestus_hunte, "citizen");
	    this.spawnEntity(phaestus_hunte, world, -25, 3, -29, start);
	    CounterEntity counter36 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter36, "counter");
	    this.spawnEntity(counter36, world, -25, 4, -43, start);
	    CitizenEntity ceas_rosmer = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:ceas_rosmer")).create(world);
	    this.setItemsForEntity(ceas_rosmer, "citizen");
	    this.spawnEntity(ceas_rosmer, world, -23, 3, -29, start);
	    CitizenEntity ludwig_winne = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:ludwig_winne")).create(world);
	    this.setItemsForEntity(ludwig_winne, "citizen");
	    this.spawnEntity(ludwig_winne, world, -20, 3, -4, start);
	    BoromirPatrollingGuard patrolling_guard39 = (BoromirPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:boromir_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard39, "patrolling_guard");
	    this.spawnEntity(patrolling_guard39, world, -19, 3, 25, start);
	    CitizenEntity yzebel_rousset = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:yzebel_rousset")).create(world);
	    this.setItemsForEntity(yzebel_rousset, "citizen");
	    this.spawnEntity(yzebel_rousset, world, -19, 3, 35, start);
	    CitizenEntity julienne_hunte = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:julienne_hunte")).create(world);
	    this.setItemsForEntity(julienne_hunte, "citizen");
	    this.spawnEntity(julienne_hunte, world, -19, 3, 38, start);
	    BoromirStandingGuard standing_guard42 = (BoromirStandingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:boromir_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard42, "standing_guard");
	    this.spawnEntity(standing_guard42, world, -17, 3, -46, start);
	    MerchantEntity baker = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:baker")).create(world);
	    this.setItemsForEntity(baker, "merchant");
	    this.spawnEntity(baker, world, -17, 3, 16, start);
	    BoromirPatrollingGuard patrolling_guard44 = (BoromirPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:boromir_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard44, "patrolling_guard");
	    this.spawnEntity(patrolling_guard44, world, -17, 3, 43, start);
	    CounterEntity counter45 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter45, "counter");
	    this.spawnEntity(counter45, world, -16, 4, 16, start);
	    BoromirPatrollingGuard patrolling_guard46 = (BoromirPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:boromir_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard46, "patrolling_guard");
	    this.spawnEntity(patrolling_guard46, world, -14, 3, -29, start);
	    BoromirStandingGuard standing_guard47 = (BoromirStandingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:boromir_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard47, "standing_guard");
	    this.spawnEntity(standing_guard47, world, -13, 3, 8, start);
	    BoromirPatrollingGuard patrolling_guard48 = (BoromirPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:boromir_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard48, "patrolling_guard");
	    this.spawnEntity(patrolling_guard48, world, -10, 3, 7, start);
	    MerchantEntity shop_keeper = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:shop_keeper")).create(world);
	    this.setItemsForEntity(shop_keeper, "merchant");
	    this.spawnEntity(shop_keeper, world, -9, 1, -9, start);
	    CounterEntity counter50 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter50, "counter");
	    this.spawnEntity(counter50, world, -8, 2, -9, start);
	    MerchantEntity blacksmith = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:blacksmith")).create(world);
	    this.setItemsForEntity(blacksmith, "merchant");
	    this.spawnEntity(blacksmith, world, -8, 3, 28, start);
	    CounterEntity counter52 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter52, "counter");
	    this.spawnEntity(counter52, world, -7, 4, 28, start);
	    CitizenEntity leanne_edgare = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:leanne_edgare")).create(world);
	    this.setItemsForEntity(leanne_edgare, "citizen");
	    this.spawnEntity(leanne_edgare, world, -4, 4, -28, start);
	    MerchantEntity guildmaster = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:guildmaster")).create(world);
	    this.setItemsForEntity(guildmaster, "merchant");
	    this.spawnEntity(guildmaster, world, -3, 9, -28, start);
	    CounterEntity counter55 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter55, "counter");
	    this.spawnEntity(counter55, world, -3, 10, -29, start);
	    BoromirPatrollingGuard patrolling_guard56 = (BoromirPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:boromir_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard56, "patrolling_guard");
	    this.spawnEntity(patrolling_guard56, world, -2, 1, -18, start);
	    CitizenEntity karles_hauser = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:karles_hauser")).create(world);
	    this.setItemsForEntity(karles_hauser, "citizen");
	    this.spawnEntity(karles_hauser, world, -2, 4, -28, start);
	    BoromirStandingGuard standing_guard58 = (BoromirStandingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:boromir_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard58, "standing_guard");
	    this.spawnEntity(standing_guard58, world, 0, 1, 20, start);
	    BoromirPatrollingGuard patrolling_guard59 = (BoromirPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:boromir_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard59, "patrolling_guard");
	    this.spawnEntity(patrolling_guard59, world, 0, 1, 43, start);
	    BoromirPatrollingGuard patrolling_guard60 = (BoromirPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:boromir_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard60, "patrolling_guard");
	    this.spawnEntity(patrolling_guard60, world, 1, 1, 8, start);
	    CitizenEntity fermin_blommen = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:fermin_blommen")).create(world);
	    this.setItemsForEntity(fermin_blommen, "citizen");
	    this.spawnEntity(fermin_blommen, world, 6, 1, 17, start);
	    BoromirPatrollingGuard patrolling_guard62 = (BoromirPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:boromir_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard62, "patrolling_guard");
	    this.spawnEntity(patrolling_guard62, world, 8, 1, 28, start);
	    BoromirStandingGuard standing_guard63 = (BoromirStandingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:boromir_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard63, "standing_guard");
	    this.spawnEntity(standing_guard63, world, 9, 1, 59, start);
	    CitizenEntity laurana_slyke = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:laurana_slyke")).create(world);
	    this.setItemsForEntity(laurana_slyke, "citizen");
	    this.spawnEntity(laurana_slyke, world, 11, 1, -8, start);
	    CitizenEntity jonathas_andretto = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:jonathas_andretto")).create(world);
	    this.setItemsForEntity(jonathas_andretto, "citizen");
	    this.spawnEntity(jonathas_andretto, world, 11, 1, -4, start);
	    MerchantEntity inn_keeper = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:inn_keeper")).create(world);
	    this.setItemsForEntity(inn_keeper, "merchant");
	    this.spawnEntity(inn_keeper, world, 13, 1, 3, start);
	    BoromirPatrollingGuard patrolling_guard67 = (BoromirPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:boromir_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard67, "patrolling_guard");
	    this.spawnEntity(patrolling_guard67, world, 13, 1, 40, start);
	    CitizenEntity leontina_crassinus = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:leontina_crassinus")).create(world);
	    this.setItemsForEntity(leontina_crassinus, "citizen");
	    this.spawnEntity(leontina_crassinus, world, 13, 1, 43, start);
	    CounterEntity counter69 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter69, "counter");
	    this.spawnEntity(counter69, world, 13, 2, 2, start);
	    BoromirPatrollingGuard patrolling_guard70 = (BoromirPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:boromir_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard70, "patrolling_guard");
	    this.spawnEntity(patrolling_guard70, world, 14, 1, -17, start);
	    CitizenEntity nicia_andretto = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:nicia_andretto")).create(world);
	    this.setItemsForEntity(nicia_andretto, "citizen");
	    this.spawnEntity(nicia_andretto, world, 15, 1, -8, start);
	    CitizenEntity picot_roelofs = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:picot_roelofs")).create(world);
	    this.setItemsForEntity(picot_roelofs, "citizen");
	    this.spawnEntity(picot_roelofs, world, 15, 1, 45, start);
	    BoromirStandingGuard standing_guard73 = (BoromirStandingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:boromir_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard73, "standing_guard");
	    this.spawnEntity(standing_guard73, world, 15, 1, 59, start);
	    CounterEntity counter74 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter74, "counter");
	    this.spawnEntity(counter74, world, 15, 2, 17, start);
	    MerchantEntity craftsman = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:craftsman")).create(world);
	    this.setItemsForEntity(craftsman, "merchant");
	    this.spawnEntity(craftsman, world, 16, 1, 17, start);
	    BoromirStandingGuard standing_guard76 = (BoromirStandingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:boromir_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard76, "standing_guard");
	    this.spawnEntity(standing_guard76, world, 17, 1, -49, start);
	    BoromirPatrollingGuard patrolling_guard77 = (BoromirPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:boromir_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard77, "patrolling_guard");
	    this.spawnEntity(patrolling_guard77, world, 18, 1, -37, start);
	    BoromirStandingGuard standing_guard78 = (BoromirStandingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:boromir_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard78, "standing_guard");
	    this.spawnEntity(standing_guard78, world, 18, 3, -24, start);
	    CounterEntity counter79 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter79, "counter");
	    this.spawnEntity(counter79, world, 19, 2, 33, start);
	    MerchantEntity butcher = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:butcher")).create(world);
	    this.setItemsForEntity(butcher, "merchant");
	    this.spawnEntity(butcher, world, 20, 1, 33, start);
	    BoromirPatrollingGuard patrolling_guard81 = (BoromirPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:boromir_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard81, "patrolling_guard");
	    this.spawnEntity(patrolling_guard81, world, 21, 1, 44, start);
	    CitizenEntity aureliana_huyler = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:aureliana_huyler")).create(world);
	    this.setItemsForEntity(aureliana_huyler, "citizen");
	    this.spawnEntity(aureliana_huyler, world, 23, 1, 23, start);
	    CitizenEntity velma_bordeaux = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:velma_bordeaux")).create(world);
	    this.setItemsForEntity(velma_bordeaux, "citizen");
	    this.spawnEntity(velma_bordeaux, world, 23, 1, 38, start);
	    BoromirStandingGuard standing_guard84 = (BoromirStandingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:boromir_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard84, "standing_guard");
	    this.spawnEntity(standing_guard84, world, 26, 1, 8, start);
	    CitizenEntity oswin_bryde = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:oswin_bryde")).create(world);
	    this.setItemsForEntity(oswin_bryde, "citizen");
	    this.spawnEntity(oswin_bryde, world, 26, 1, 19, start);
	    BoromirPatrollingGuard patrolling_guard86 = (BoromirPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:boromir_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard86, "patrolling_guard");
	    this.spawnEntity(patrolling_guard86, world, 31, 1, 18, start);
	    this.executeCommand(world);
	    if(TownStructures.teleportBoromirTown()) this.transportPlayertoTown(TownStructures.BASHKAR_CITY.get(), "Teleported player to Boromir Town.", 7, 6);
	}

}
