package mod.arcalitegames.odyssey.world.structure.town.saxontown;

import java.util.Objects;

import mod.arcalitegames.odyssey.entity.CounterEntity;
import mod.arcalitegames.odyssey.entity.citizens.saxontown.guards.SaxonPatrollingGuard;
import mod.arcalitegames.odyssey.entity.citizens.saxontown.guards.SaxonStandingGuard;
import mod.arcalitegames.odyssey.entity.passive.CitizenEntity;
import mod.arcalitegames.odyssey.entity.passive.MerchantEntity;
import mod.arcalitegames.odyssey.world.structure.town.TownStructure;
import mod.arcalitegames.odyssey.world.structure.town.TownStructures;
import mod.arcalitegames.system.parser.EntityParser;
import net.minecraft.block.Blocks;
import net.minecraft.entity.CreatureEntity;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;

public class SaxonTown extends TownStructure
{

	public SaxonTown(World worldIn, BlockPos origin, int xRange, int yRange, int zRange)
	{
		super(worldIn, origin, xRange, yRange, zRange);
		SaxonTownComponent0.init(world, origin, this);
		SaxonTownComponent1.init(world, origin, this);
		SaxonTownComponent2.init(world, origin, this);
        this.fillWithBlocks(world, start, -65, -1, -67, 64, 42, 71, Blocks.AIR.getDefaultState());
	}

	@Override
	public void addEntitiesAndSpawn()
	{
	    SaxonStandingGuard standing_guard1 = (SaxonStandingGuard) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard1, "standing_guard");
	    this.spawnEntity(standing_guard1, world, -49, 3, 0, start);
	    SaxonPatrollingGuard patrolling_guard2 = (SaxonPatrollingGuard) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard2, "patrolling_guard");
	    this.spawnEntity(patrolling_guard2, world, -43, 0, -2, start);
	    SaxonPatrollingGuard patrolling_guard3 = (SaxonPatrollingGuard) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard3, "patrolling_guard");
	    this.spawnEntity(patrolling_guard3, world, -41, 0, -26, start);
	    CitizenEntity joanna_cinna = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:joanna_cinna")).create(world);
	    this.setItemsForEntity(joanna_cinna, "citizen");
	    this.spawnEntity(joanna_cinna, world, -29, 0, 30, start);
	    SaxonPatrollingGuard patrolling_guard5 = (SaxonPatrollingGuard) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard5, "patrolling_guard");
	    this.spawnEntity(patrolling_guard5, world, -28, 0, 15, start);
	    CitizenEntity seraphinus_asellus = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:seraphinus_asellus")).create(world);
	    this.setItemsForEntity(seraphinus_asellus, "citizen");
	    this.spawnEntity(seraphinus_asellus, world, -27, 0, 2, start);
	    MerchantEntity produce_vendor = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:produce_vendor")).create(world);
	    this.setItemsForEntity(produce_vendor, "merchant");
	    this.spawnEntity(produce_vendor, world, -27, 0, 4, start);
	    CounterEntity counter8 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter8, "counter");
	    this.spawnEntity(counter8, world, -27, 1, 3, start);
	    CitizenEntity ianuarius_caecus = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:ianuarius_caecus")).create(world);
	    this.setItemsForEntity(ianuarius_caecus, "citizen");
	    this.spawnEntity(ianuarius_caecus, world, -26, 0, 15, start);
	    SaxonPatrollingGuard patrolling_guard10 = (SaxonPatrollingGuard) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard10, "patrolling_guard");
	    this.spawnEntity(patrolling_guard10, world, -25, 0, -2, start);
	    SaxonPatrollingGuard patrolling_guard11 = (SaxonPatrollingGuard) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard11, "patrolling_guard");
	    this.spawnEntity(patrolling_guard11, world, -23, 0, -31, start);
	    CitizenEntity caecus_caudex = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:caecus_caudex")).create(world);
	    this.setItemsForEntity(caecus_caudex, "citizen");
	    this.spawnEntity(caecus_caudex, world, -23, 0, 35, start);
	    CitizenEntity cyra_ambustus = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:cyra_ambustus")).create(world);
	    this.setItemsForEntity(cyra_ambustus, "citizen");
	    this.spawnEntity(cyra_ambustus, world, -17, 0, -7, start);
	    CitizenEntity helier_potitus = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:helier_potitus")).create(world);
	    this.setItemsForEntity(helier_potitus, "citizen");
	    this.spawnEntity(helier_potitus, world, -17, 0, 2, start);
	    MerchantEntity fruit_vendor = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:fruit_vendor")).create(world);
	    this.setItemsForEntity(fruit_vendor, "merchant");
	    this.spawnEntity(fruit_vendor, world, -17, 0, 4, start);
	    CounterEntity counter16 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter16, "counter");
	    this.spawnEntity(counter16, world, -17, 1, 3, start);
	    SaxonPatrollingGuard patrolling_guard17 = (SaxonPatrollingGuard) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard17, "patrolling_guard");
	    this.spawnEntity(patrolling_guard17, world, -16, 0, 38, start);
	    MerchantEntity guildmaster = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:guildmaster")).create(world);
	    this.setItemsForEntity(guildmaster, "merchant");
	    this.spawnEntity(guildmaster, world, -15, 0, 27, start);
	    CounterEntity counter19 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter19, "counter");
	    this.spawnEntity(counter19, world, -15, 1, 26, start);
	    CreatureEntity horse20 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:horse")).create(world);
	    this.setItemsForEntity(horse20, "horse");
	    this.spawnEntity(horse20, world, -13, 0, -41, start);
	    CreatureEntity horse21 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:horse")).create(world);
	    this.setItemsForEntity(horse21, "horse");
	    this.spawnEntity(horse21, world, -13, 0, -36, start);
	    MerchantEntity farming_merchant = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:farming_merchant")).create(world);
	    this.setItemsForEntity(farming_merchant, "merchant");
	    this.spawnEntity(farming_merchant, world, -13, 0, -18, start);
	    MerchantEntity shop_keeper = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:shop_keeper")).create(world);
	    this.setItemsForEntity(shop_keeper, "merchant");
	    this.spawnEntity(shop_keeper, world, -12, 0, -23, start);
	    CounterEntity counter24 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter24, "counter");
	    this.spawnEntity(counter24, world, -12, 1, -24, start);
	    CounterEntity counter25 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter25, "counter");
	    this.spawnEntity(counter25, world, -12, 1, -18, start);
	    MerchantEntity mineshop_merchant = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:mineshop_merchant")).create(world);
	    this.setItemsForEntity(mineshop_merchant, "merchant");
	    this.spawnEntity(mineshop_merchant, world, -10, 0, -7, start);
	    CreatureEntity horse27 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:horse")).create(world);
	    this.setItemsForEntity(horse27, "horse");
	    this.spawnEntity(horse27, world, -9, 0, -41, start);
	    CreatureEntity horse28 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:horse")).create(world);
	    this.setItemsForEntity(horse28, "horse");
	    this.spawnEntity(horse28, world, -9, 0, -36, start);
	    CounterEntity counter29 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter29, "counter");
	    this.spawnEntity(counter29, world, -9, 1, -7, start);
	    MerchantEntity fletching_merchant = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:fletching_merchant")).create(world);
	    this.setItemsForEntity(fletching_merchant, "merchant");
	    this.spawnEntity(fletching_merchant, world, -8, 0, -29, start);
	    MerchantEntity butcher = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:butcher")).create(world);
	    this.setItemsForEntity(butcher, "merchant");
	    this.spawnEntity(butcher, world, -8, 0, 42, start);
	    CounterEntity counter32 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter32, "counter");
	    this.spawnEntity(counter32, world, -8, 1, -28, start);
	    CounterEntity counter33 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter33, "counter");
	    this.spawnEntity(counter33, world, -8, 1, 41, start);
	    CitizenEntity elianna_sura = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:elianna_sura")).create(world);
	    this.setItemsForEntity(elianna_sura, "citizen");
	    this.spawnEntity(elianna_sura, world, -7, 0, 2, start);
	    MerchantEntity decor_merchant = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:decor_merchant")).create(world);
	    this.setItemsForEntity(decor_merchant, "merchant");
	    this.spawnEntity(decor_merchant, world, -7, 0, 4, start);
	    CounterEntity counter36 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter36, "counter");
	    this.spawnEntity(counter36, world, -7, 1, 3, start);
	    MerchantEntity horse_merchant = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:horse_merchant")).create(world);
	    this.setItemsForEntity(horse_merchant, "merchant");
	    this.spawnEntity(horse_merchant, world, -4, 0, -40, start);
	    SaxonPatrollingGuard patrolling_guard38 = (SaxonPatrollingGuard) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard38, "patrolling_guard");
	    this.spawnEntity(patrolling_guard38, world, -3, 0, -29, start);
	    CitizenEntity philotheus_blasio = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:philotheus_blasio")).create(world);
	    this.setItemsForEntity(philotheus_blasio, "citizen");
	    this.spawnEntity(philotheus_blasio, world, -3, 0, -21, start);
	    CitizenEntity lorina_vestalis = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:lorina_vestalis")).create(world);
	    this.setItemsForEntity(lorina_vestalis, "citizen");
	    this.spawnEntity(lorina_vestalis, world, -3, 0, -19, start);
	    SaxonPatrollingGuard patrolling_guard41 = (SaxonPatrollingGuard) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard41, "patrolling_guard");
	    this.spawnEntity(patrolling_guard41, world, -3, 0, 38, start);
	    CounterEntity counter42 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter42, "counter");
	    this.spawnEntity(counter42, world, -3, 1, -40, start);
	    SaxonStandingGuard standing_guard43 = (SaxonStandingGuard) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard43, "standing_guard");
	    this.spawnEntity(standing_guard43, world, -2, 0, -54, start);
	    SaxonStandingGuard standing_guard44 = (SaxonStandingGuard) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard44, "standing_guard");
	    this.spawnEntity(standing_guard44, world, -2, 0, -44, start);
	    SaxonPatrollingGuard patrolling_guard45 = (SaxonPatrollingGuard) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard45, "patrolling_guard");
	    this.spawnEntity(patrolling_guard45, world, -2, 0, -2, start);
	    SaxonPatrollingGuard patrolling_guard46 = (SaxonPatrollingGuard) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard46, "patrolling_guard");
	    this.spawnEntity(patrolling_guard46, world, -2, 0, 13, start);
	    CitizenEntity pantera_arvina = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:pantera_arvina")).create(world);
	    this.setItemsForEntity(pantera_arvina, "citizen");
	    this.spawnEntity(pantera_arvina, world, -2, 0, 29, start);
	    SaxonStandingGuard standing_guard48 = (SaxonStandingGuard) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard48, "standing_guard");
	    this.spawnEntity(standing_guard48, world, -2, 0, 47, start);
	    SaxonStandingGuard standing_guard49 = (SaxonStandingGuard) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard49, "standing_guard");
	    this.spawnEntity(standing_guard49, world, -2, 0, 57, start);
	    SaxonPatrollingGuard patrolling_guard50 = (SaxonPatrollingGuard) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard50, "patrolling_guard");
	    this.spawnEntity(patrolling_guard50, world, -1, 0, 36, start);
	    SaxonStandingGuard standing_guard51 = (SaxonStandingGuard) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard51, "standing_guard");
	    this.spawnEntity(standing_guard51, world, 2, 0, -54, start);
	    SaxonStandingGuard standing_guard52 = (SaxonStandingGuard) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard52, "standing_guard");
	    this.spawnEntity(standing_guard52, world, 2, 0, -44, start);
	    SaxonStandingGuard standing_guard53 = (SaxonStandingGuard) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard53, "standing_guard");
	    this.spawnEntity(standing_guard53, world, 2, 0, 47, start);
	    SaxonStandingGuard standing_guard54 = (SaxonStandingGuard) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard54, "standing_guard");
	    this.spawnEntity(standing_guard54, world, 2, 0, 57, start);
	    CitizenEntity naevius_salinator = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:naevius_salinator")).create(world);
	    this.setItemsForEntity(naevius_salinator, "citizen");
	    this.spawnEntity(naevius_salinator, world, 3, 0, 18, start);
	    CitizenEntity egnatius_hispallus = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:egnatius_hispallus")).create(world);
	    this.setItemsForEntity(egnatius_hispallus, "citizen");
	    this.spawnEntity(egnatius_hispallus, world, 4, 0, 17, start);
	    MerchantEntity blacksmith = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:blacksmith")).create(world);
	    this.setItemsForEntity(blacksmith, "merchant");
	    this.spawnEntity(blacksmith, world, 8, 0, -3, start);
	    MerchantEntity craftsman = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:craftsman")).create(world);
	    this.setItemsForEntity(craftsman, "merchant");
	    this.spawnEntity(craftsman, world, 8, 0, 28, start);
	    CounterEntity counter59 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter59, "counter");
	    this.spawnEntity(counter59, world, 8, 1, -26, start);
	    CounterEntity counter60 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter60, "counter");
	    this.spawnEntity(counter60, world, 8, 1, -2, start);
	    CounterEntity counter61 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter61, "counter");
	    this.spawnEntity(counter61, world, 8, 1, 29, start);
	    CounterEntity counter62 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter62, "counter");
	    this.spawnEntity(counter62, world, 8, 1, 41, start);
	    MerchantEntity baker = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:baker")).create(world);
	    this.setItemsForEntity(baker, "merchant");
	    this.spawnEntity(baker, world, 9, 0, -26, start);
	    MerchantEntity redstone_merchant = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:redstone_merchant")).create(world);
	    this.setItemsForEntity(redstone_merchant, "merchant");
	    this.spawnEntity(redstone_merchant, world, 9, 0, 41, start);
	    SaxonPatrollingGuard patrolling_guard65 = (SaxonPatrollingGuard) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard65, "patrolling_guard");
	    this.spawnEntity(patrolling_guard65, world, 11, 0, 2, start);
	    CitizenEntity oenone_merula = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:oenone_merula")).create(world);
	    this.setItemsForEntity(oenone_merula, "citizen");
	    this.spawnEntity(oenone_merula, world, 13, 0, 12, start);
	    CitizenEntity hester_geta = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:hester_geta")).create(world);
	    this.setItemsForEntity(hester_geta, "citizen");
	    this.spawnEntity(hester_geta, world, 16, 0, 16, start);
	    SaxonPatrollingGuard patrolling_guard68 = (SaxonPatrollingGuard) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard68, "patrolling_guard");
	    this.spawnEntity(patrolling_guard68, world, 17, 0, 41, start);
	    CitizenEntity athanasius_glaber = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:athanasius_glaber")).create(world);
	    this.setItemsForEntity(athanasius_glaber, "citizen");
	    this.spawnEntity(athanasius_glaber, world, 18, 0, 12, start);
	    SaxonPatrollingGuard patrolling_guard70 = (SaxonPatrollingGuard) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard70, "patrolling_guard");
	    this.spawnEntity(patrolling_guard70, world, 19, 0, -18, start);
	    SaxonPatrollingGuard patrolling_guard71 = (SaxonPatrollingGuard) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard71, "patrolling_guard");
	    this.spawnEntity(patrolling_guard71, world, 20, 0, -34, start);
	    CitizenEntity aurelia_procillus = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:aurelia_procillus")).create(world);
	    this.setItemsForEntity(aurelia_procillus, "citizen");
	    this.spawnEntity(aurelia_procillus, world, 23, 0, -32, start);
	    CitizenEntity krista_vibulanus = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:krista_vibulanus")).create(world);
	    this.setItemsForEntity(krista_vibulanus, "citizen");
	    this.spawnEntity(krista_vibulanus, world, 23, 0, -24, start);
	    MerchantEntity alchemist = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:alchemist")).create(world);
	    this.setItemsForEntity(alchemist, "merchant");
	    this.spawnEntity(alchemist, world, 23, 0, -4, start);
	    CounterEntity counter75 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter75, "counter");
	    this.spawnEntity(counter75, world, 23, 1, -3, start);
	    CitizenEntity valerian_junianus = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:valerian_junianus")).create(world);
	    this.setItemsForEntity(valerian_junianus, "citizen");
	    this.spawnEntity(valerian_junianus, world, 24, 0, 14, start);
	    CitizenEntity rufus_calussa = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:rufus_calussa")).create(world);
	    this.setItemsForEntity(rufus_calussa, "citizen");
	    this.spawnEntity(rufus_calussa, world, 25, 0, 3, start);
	    MerchantEntity inn_keeper = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:inn_keeper")).create(world);
	    this.setItemsForEntity(inn_keeper, "merchant");
	    this.spawnEntity(inn_keeper, world, 25, 0, 12, start);
	    CounterEntity counter79 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter79, "counter");
	    this.spawnEntity(counter79, world, 25, 1, 13, start);
	    CitizenEntity sera_albus = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:sera_albus")).create(world);
	    this.setItemsForEntity(sera_albus, "citizen");
	    this.spawnEntity(sera_albus, world, 26, 0, 14, start);
	    CitizenEntity ferox_augur = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:ferox_augur")).create(world);
	    this.setItemsForEntity(ferox_augur, "citizen");
	    this.spawnEntity(ferox_augur, world, 27, 0, 3, start);
	    SaxonPatrollingGuard patrolling_guard82 = (SaxonPatrollingGuard) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard82, "patrolling_guard");
	    this.spawnEntity(patrolling_guard82, world, 28, 0, 39, start);
	    CitizenEntity quique_unimanus = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:quique_unimanus")).create(world);
	    this.setItemsForEntity(quique_unimanus, "citizen");
	    this.spawnEntity(quique_unimanus, world, 32, 0, -26, start);
	    CitizenEntity adelia_messala = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:adelia_messala")).create(world);
	    this.setItemsForEntity(adelia_messala, "citizen");
	    this.spawnEntity(adelia_messala, world, 34, 0, 31, start);
	    SaxonPatrollingGuard patrolling_guard85 = (SaxonPatrollingGuard) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard85, "patrolling_guard");
	    this.spawnEntity(patrolling_guard85, world, 37, 0, 2, start);
	    CitizenEntity cosmo_getha = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:cosmo_getha")).create(world);
	    this.setItemsForEntity(cosmo_getha, "citizen");
	    this.spawnEntity(cosmo_getha, world, 39, 0, 6, start);
	    SaxonPatrollingGuard patrolling_guard87 = (SaxonPatrollingGuard) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard87, "patrolling_guard");
	    this.spawnEntity(patrolling_guard87, world, 39, 0, 21, start);
	    SaxonStandingGuard standing_guard88 = (SaxonStandingGuard) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard88, "standing_guard");
	    this.spawnEntity(standing_guard88, world, 49, 3, 0, start);
	    this.executeCommand(world);
	    if(TownStructures.teleportSaxonTown()) this.transportPlayertoTown(TownStructures.SAXON_TOWN.get(), "Teleported player to Saxon Town.", 7, 6);
	}
	
}
