package mod.arcalitegames.odyssey.world.structure.town.fortmesa;

import java.util.Objects;

import mod.arcalitegames.odyssey.entity.CounterEntity;
import mod.arcalitegames.odyssey.entity.citizens.fort_mesa.sheriffs.DeputySheriff;
import mod.arcalitegames.odyssey.entity.citizens.fort_mesa.sheriffs.SheriffGuard;
import mod.arcalitegames.odyssey.entity.passive.CitizenEntity;
import mod.arcalitegames.odyssey.entity.passive.MerchantEntity;
import mod.arcalitegames.odyssey.world.gen.MapGenerator;
import mod.arcalitegames.odyssey.world.structure.town.TownStructure;
import mod.arcalitegames.odyssey.world.structure.town.TownStructures;
import mod.arcalitegames.system.parser.EntityParser;
import mod.arcalitegames.system.util.Counter;
import net.minecraft.block.Blocks;
import net.minecraft.command.CommandSource;
import net.minecraft.command.Commands;
import net.minecraft.entity.CreatureEntity;
import net.minecraft.entity.player.PlayerEntity;
import net.minecraft.server.MinecraftServer;
import net.minecraft.util.math.BlockPos;
import net.minecraft.util.text.StringTextComponent;
import net.minecraft.world.World;

public class FortMesa extends TownStructure
{

	public FortMesa(World worldIn, BlockPos origin, int xRange, int yRange, int zRange)
	{
		super(worldIn, origin, xRange, yRange, zRange);
		FortMesaComponent0.init(world, origin, this);
		FortMesaComponent1.init(world, origin, this);
        this.fillWithBlocks(world, start, -60, -1, -70, 85, 37, 31, Blocks.AIR.getDefaultState());
	}

	@Override
	public void addEntitiesAndSpawn()
	{
	    SheriffGuard standing_guard1 = (SheriffGuard) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:sheriff")).create(world);
	    this.setItemsForEntity(standing_guard1, "standing_guard");
	    this.spawnEntity(standing_guard1, world, -57, 0, -52, start);
	    DeputySheriff patrolling_guard2 = (DeputySheriff) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:deputy_sheriff")).create(world);
	    this.setItemsForEntity(patrolling_guard2, "patrolling_guard");
	    this.spawnEntity(patrolling_guard2, world, -37, 0, -20, start);
	    DeputySheriff patrolling_guard3 = (DeputySheriff) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:deputy_sheriff")).create(world);
	    this.setItemsForEntity(patrolling_guard3, "patrolling_guard");
	    this.spawnEntity(patrolling_guard3, world, -37, 0, -17, start);
	    DeputySheriff patrolling_guard4 = (DeputySheriff) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:deputy_sheriff")).create(world);
	    this.setItemsForEntity(patrolling_guard4, "patrolling_guard");
	    this.spawnEntity(patrolling_guard4, world, -30, 1, -62, start);
	    CitizenEntity delfina_whiting = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:delfina_whiting")).create(world);
	    this.setItemsForEntity(delfina_whiting, "citizen");
	    this.spawnEntity(delfina_whiting, world, -30, 1, -12, start);
	    DeputySheriff patrolling_guard6 = (DeputySheriff) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:deputy_sheriff")).create(world);
	    this.setItemsForEntity(patrolling_guard6, "patrolling_guard");
	    this.spawnEntity(patrolling_guard6, world, -23, 0, -31, start);
	    CitizenEntity blueford_blakeley = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:blueford_blakeley")).create(world);
	    this.setItemsForEntity(blueford_blakeley, "citizen");
	    this.spawnEntity(blueford_blakeley, world, -23, 0, -19, start);
	    CitizenEntity huge_coolidge = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:huge_coolidge")).create(world);
	    this.setItemsForEntity(huge_coolidge, "citizen");
	    this.spawnEntity(huge_coolidge, world, -23, 1, -39, start);
	    DeputySheriff patrolling_guard9 = (DeputySheriff) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:deputy_sheriff")).create(world);
	    this.setItemsForEntity(patrolling_guard9, "patrolling_guard");
	    this.spawnEntity(patrolling_guard9, world, -21, 1, -56, start);
	    SheriffGuard standing_guard10 = (SheriffGuard) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:sheriff")).create(world);
	    this.setItemsForEntity(standing_guard10, "standing_guard");
	    this.spawnEntity(standing_guard10, world, -20, 0, 15, start);
	    CitizenEntity eyes_coulter = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:eyes_coulter")).create(world);
	    this.setItemsForEntity(eyes_coulter, "citizen");
	    this.spawnEntity(eyes_coulter, world, -18, 1, -23, start);
	    CitizenEntity rebecca_slawter = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:rebecca_slawter")).create(world);
	    this.setItemsForEntity(rebecca_slawter, "citizen");
	    this.spawnEntity(rebecca_slawter, world, -16, -1, 13, start);
	    CitizenEntity corrina_mccandles = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:corrina_mccandles")).create(world);
	    this.setItemsForEntity(corrina_mccandles, "citizen");
	    this.spawnEntity(corrina_mccandles, world, -15, 1, -28, start);
	    MerchantEntity guildmaster = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:guildmaster")).create(world);
	    this.setItemsForEntity(guildmaster, "merchant");
	    this.spawnEntity(guildmaster, world, -13, 1, -7, start);
	    CounterEntity counter15 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter15, "counter");
	    this.spawnEntity(counter15, world, -13, 2, -6, start);
	    CitizenEntity gabrielle_lavera = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:gabrielle_lavera")).create(world);
	    this.setItemsForEntity(gabrielle_lavera, "citizen");
	    this.spawnEntity(gabrielle_lavera, world, -12, 1, -29, start);
	    CitizenEntity julie_berrsheim = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:julie_berrsheim")).create(world);
	    this.setItemsForEntity(julie_berrsheim, "citizen");
	    this.spawnEntity(julie_berrsheim, world, -12, 1, -26, start);
	    CounterEntity counter18 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter18, "counter");
	    this.spawnEntity(counter18, world, -10, 2, -28, start);
	    CitizenEntity nuna_skenandore = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:nuna_skenandore")).create(world);
	    this.setItemsForEntity(nuna_skenandore, "citizen");
	    this.spawnEntity(nuna_skenandore, world, -9, 0, 20, start);
	    MerchantEntity inn_keeper = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:inn_keeper")).create(world);
	    this.setItemsForEntity(inn_keeper, "merchant");
	    this.spawnEntity(inn_keeper, world, -9, 1, -28, start);
	    SheriffGuard standing_guard21 = (SheriffGuard) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:sheriff")).create(world);
	    this.setItemsForEntity(standing_guard21, "standing_guard");
	    this.spawnEntity(standing_guard21, world, -7, 1, 0, start);
	    CitizenEntity ned_hively = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:ned_hively")).create(world);
	    this.setItemsForEntity(ned_hively, "citizen");
	    this.spawnEntity(ned_hively, world, -4, 0, -18, start);
	    CitizenEntity orlander_mattengley = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:orlander_mattengley")).create(world);
	    this.setItemsForEntity(orlander_mattengley, "citizen");
	    this.spawnEntity(orlander_mattengley, world, -4, 0, -2, start);
	    CitizenEntity hayden_waufle = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:hayden_waufle")).create(world);
	    this.setItemsForEntity(hayden_waufle, "citizen");
	    this.spawnEntity(hayden_waufle, world, -4, 0, 4, start);
	    DeputySheriff patrolling_guard25 = (DeputySheriff) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:deputy_sheriff")).create(world);
	    this.setItemsForEntity(patrolling_guard25, "patrolling_guard");
	    this.spawnEntity(patrolling_guard25, world, -3, 1, -42, start);
	    CreatureEntity horse26 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:horse")).create(world);
	    this.setItemsForEntity(horse26, "horse");
	    this.spawnEntity(horse26, world, -2, 1, -54, start);
	    CitizenEntity calwin_sapelet = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:calwin_sapelet")).create(world);
	    this.setItemsForEntity(calwin_sapelet, "citizen");
	    this.spawnEntity(calwin_sapelet, world, -1, -1, 24, start);
	    CreatureEntity horse28 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:horse")).create(world);
	    this.setItemsForEntity(horse28, "horse");
	    this.spawnEntity(horse28, world, -1, 1, -50, start);
	    DeputySheriff patrolling_guard29 = (DeputySheriff) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:deputy_sheriff")).create(world);
	    this.setItemsForEntity(patrolling_guard29, "patrolling_guard");
	    this.spawnEntity(patrolling_guard29, world, 1, 1, -13, start);
	    MerchantEntity butcher = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:butcher")).create(world);
	    this.setItemsForEntity(butcher, "merchant");
	    this.spawnEntity(butcher, world, 1, 1, -7, start);
	    CounterEntity counter31 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter31, "counter");
	    this.spawnEntity(counter31, world, 1, 2, -8, start);
	    MerchantEntity shop_keeper = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:shop_keeper")).create(world);
	    this.setItemsForEntity(shop_keeper, "merchant");
	    this.spawnEntity(shop_keeper, world, 2, 1, -29, start);
	    CounterEntity counter33 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter33, "counter");
	    this.spawnEntity(counter33, world, 2, 2, -28, start);
	    MerchantEntity horse_merchant = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:horse_merchant")).create(world);
	    this.setItemsForEntity(horse_merchant, "merchant");
	    this.spawnEntity(horse_merchant, world, 3, 1, -55, start);
	    CounterEntity counter35 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter35, "counter");
	    this.spawnEntity(counter35, world, 3, 2, -54, start);
	    CitizenEntity evelina_millican = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:evelina_millican")).create(world);
	    this.setItemsForEntity(evelina_millican, "citizen");
	    this.spawnEntity(evelina_millican, world, 6, 1, -42, start);
	    MerchantEntity baker = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:baker")).create(world);
	    this.setItemsForEntity(baker, "merchant");
	    this.spawnEntity(baker, world, 7, 1, 13, start);
	    CounterEntity counter38 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter38, "counter");
	    this.spawnEntity(counter38, world, 7, 2, 12, start);
	    CreatureEntity horse39 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:horse")).create(world);
	    this.setItemsForEntity(horse39, "horse");
	    this.spawnEntity(horse39, world, 8, 1, -54, start);
	    CreatureEntity horse40 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:horse")).create(world);
	    this.setItemsForEntity(horse40, "horse");
	    this.spawnEntity(horse40, world, 8, 1, -50, start);
	    DeputySheriff patrolling_guard41 = (DeputySheriff) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:deputy_sheriff")).create(world);
	    this.setItemsForEntity(patrolling_guard41, "patrolling_guard");
	    this.spawnEntity(patrolling_guard41, world, 10, 0, 3, start);
	    DeputySheriff patrolling_guard42 = (DeputySheriff) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:deputy_sheriff")).create(world);
	    this.setItemsForEntity(patrolling_guard42, "patrolling_guard");
	    this.spawnEntity(patrolling_guard42, world, 10, 1, -42, start);
	    MerchantEntity alchemist = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:alchemist")).create(world);
	    this.setItemsForEntity(alchemist, "merchant");
	    this.spawnEntity(alchemist, world, 11, 1, -9, start);
	    CounterEntity counter44 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter44, "counter");
	    this.spawnEntity(counter44, world, 11, 2, -8, start);
	    DeputySheriff patrolling_guard45 = (DeputySheriff) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:deputy_sheriff")).create(world);
	    this.setItemsForEntity(patrolling_guard45, "patrolling_guard");
	    this.spawnEntity(patrolling_guard45, world, 12, 0, -16, start);
	    CitizenEntity horton_mavity = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:horton_mavity")).create(world);
	    this.setItemsForEntity(horton_mavity, "citizen");
	    this.spawnEntity(horton_mavity, world, 16, 1, -2, start);
	    CitizenEntity fleet_martz = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:fleet_martz")).create(world);
	    this.setItemsForEntity(fleet_martz, "citizen");
	    this.spawnEntity(fleet_martz, world, 21, 0, -14, start);
	    CitizenEntity maxie_breithaupt = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:maxie_breithaupt")).create(world);
	    this.setItemsForEntity(maxie_breithaupt, "citizen");
	    this.spawnEntity(maxie_breithaupt, world, 22, 1, -35, start);
	    MerchantEntity blacksmith = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:blacksmith")).create(world);
	    this.setItemsForEntity(blacksmith, "merchant");
	    this.spawnEntity(blacksmith, world, 22, 1, 13, start);
	    CounterEntity counter50 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter50, "counter");
	    this.spawnEntity(counter50, world, 22, 2, 12, start);
	    CitizenEntity pete_rutles = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:pete_rutles")).create(world);
	    this.setItemsForEntity(pete_rutles, "citizen");
	    this.spawnEntity(pete_rutles, world, 26, 0, 3, start);
	    SheriffGuard standing_guard52 = (SheriffGuard) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:sheriff")).create(world);
	    this.setItemsForEntity(standing_guard52, "standing_guard");
	    this.spawnEntity(standing_guard52, world, 26, 1, -18, start);
	    CounterEntity counter53 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter53, "counter");
	    this.spawnEntity(counter53, world, 31, 2, -6, start);
	    MerchantEntity decor_merchant = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:decor_merchant")).create(world);
	    this.setItemsForEntity(decor_merchant, "merchant");
	    this.spawnEntity(decor_merchant, world, 32, 1, -6, start);
	    CitizenEntity berry_gester = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:berry_gester")).create(world);
	    this.setItemsForEntity(berry_gester, "citizen");
	    this.spawnEntity(berry_gester, world, 36, 1, -38, start);
	    CitizenEntity cash_hassestatzel = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:cash_hassestatzel")).create(world);
	    this.setItemsForEntity(cash_hassestatzel, "citizen");
	    this.spawnEntity(cash_hassestatzel, world, 36, 1, 7, start);
	    MerchantEntity craftsman = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:craftsman")).create(world);
	    this.setItemsForEntity(craftsman, "merchant");
	    this.spawnEntity(craftsman, world, 36, 1, 13, start);
	    CounterEntity counter58 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter58, "counter");
	    this.spawnEntity(counter58, world, 36, 2, 12, start);
	    CitizenEntity nova_okhmhaka = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:nova_okhmhaka")).create(world);
	    this.setItemsForEntity(nova_okhmhaka, "citizen");
	    this.spawnEntity(nova_okhmhaka, world, 37, 1, -49, start);
	    DeputySheriff patrolling_guard60 = (DeputySheriff) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:deputy_sheriff")).create(world);
	    this.setItemsForEntity(patrolling_guard60, "patrolling_guard");
	    this.spawnEntity(patrolling_guard60, world, 38, 1, -45, start);
	    CitizenEntity kanti_chaney = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:kanti_chaney")).create(world);
	    this.setItemsForEntity(kanti_chaney, "citizen");
	    this.spawnEntity(kanti_chaney, world, 40, 0, 3, start);
	    MerchantEntity fletching_merchant = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:fletching_merchant")).create(world);
	    this.setItemsForEntity(fletching_merchant, "merchant");
	    this.spawnEntity(fletching_merchant, world, 47, 1, 14, start);
	    CounterEntity counter63 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter63, "counter");
	    this.spawnEntity(counter63, world, 47, 2, 13, start);
	    DeputySheriff patrolling_guard64 = (DeputySheriff) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:deputy_sheriff")).create(world);
	    this.setItemsForEntity(patrolling_guard64, "patrolling_guard");
	    this.spawnEntity(patrolling_guard64, world, 48, 0, 3, start);
	    MerchantEntity redstone_merchant = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:redstone_merchant")).create(world);
	    this.setItemsForEntity(redstone_merchant, "merchant");
	    this.spawnEntity(redstone_merchant, world, 51, 1, -7, start);
	    CounterEntity counter66 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter66, "counter");
	    this.spawnEntity(counter66, world, 51, 2, -6, start);
	    CitizenEntity atticus_livereux = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:atticus_livereux")).create(world);
	    this.setItemsForEntity(atticus_livereux, "citizen");
	    this.spawnEntity(atticus_livereux, world, 53, 0, 3, start);
	    DeputySheriff patrolling_guard68 = (DeputySheriff) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:deputy_sheriff")).create(world);
	    this.setItemsForEntity(patrolling_guard68, "patrolling_guard");
	    this.spawnEntity(patrolling_guard68, world, 55, 1, -18, start);
	    CitizenEntity zachary_anman = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:zachary_anman")).create(world);
	    this.setItemsForEntity(zachary_anman, "citizen");
	    this.spawnEntity(zachary_anman, world, 57, 1, 7, start);
	    MerchantEntity farming_merchant = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:farming_merchant")).create(world);
	    this.setItemsForEntity(farming_merchant, "merchant");
	    this.spawnEntity(farming_merchant, world, 57, 1, 13, start);
	    CounterEntity counter71 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter71, "counter");
	    this.spawnEntity(counter71, world, 57, 2, 12, start);
	    DeputySheriff patrolling_guard72 = (DeputySheriff) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:deputy_sheriff")).create(world);
	    this.setItemsForEntity(patrolling_guard72, "patrolling_guard");
	    this.spawnEntity(patrolling_guard72, world, 59, 1, -32, start);
	    MerchantEntity mineshop_merchant = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:mineshop_merchant")).create(world);
	    this.setItemsForEntity(mineshop_merchant, "merchant");
	    this.spawnEntity(mineshop_merchant, world, 63, 1, -7, start);
	    CitizenEntity dink_dunker = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:dink_dunker")).create(world);
	    this.setItemsForEntity(dink_dunker, "citizen");
	    this.spawnEntity(dink_dunker, world, 63, 1, -1, start);
	    CounterEntity counter75 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter75, "counter");
	    this.spawnEntity(counter75, world, 63, 2, -6, start);
	    DeputySheriff patrolling_guard76 = (DeputySheriff) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:deputy_sheriff")).create(world);
	    this.setItemsForEntity(patrolling_guard76, "patrolling_guard");
	    this.spawnEntity(patrolling_guard76, world, 75, 0, 3, start);
	    this.executeCommand(world);
	    if(TownStructures.teleportFortMesa()) this.transportPlayertoTown(TownStructures.FORT_MESA.get(), "Teleported player to Fort Mesa.", 7, 6);
	}
	
}
