package mod.arcalitegames.odyssey.world.structure.town.saxon_snow;

import java.util.Objects;

import mod.arcalitegames.odyssey.entity.CounterEntity;
import mod.arcalitegames.odyssey.entity.citizens.saxontown.guards.SaxonPatrollingGuard;
import mod.arcalitegames.odyssey.entity.citizens.saxontown.guards.SaxonStandingGuard;
import mod.arcalitegames.odyssey.entity.passive.CitizenEntity;
import mod.arcalitegames.odyssey.entity.passive.MerchantEntity;
import mod.arcalitegames.odyssey.world.gen.MapGenerator;
import mod.arcalitegames.odyssey.world.structure.town.TownStructure;
import mod.arcalitegames.odyssey.world.structure.town.TownStructures;
import mod.arcalitegames.system.parser.EntityParser;
import mod.arcalitegames.system.util.Counter;
import net.minecraft.block.Blocks;
import net.minecraft.command.CommandSource;
import net.minecraft.command.Commands;
import net.minecraft.entity.CreatureEntity;
import net.minecraft.entity.player.PlayerEntity;
import net.minecraft.server.MinecraftServer;
import net.minecraft.util.math.BlockPos;
import net.minecraft.util.text.StringTextComponent;
import net.minecraft.world.World;

public class SaxonSnow extends TownStructure
{

	public SaxonSnow(World worldIn, BlockPos origin, int xRange, int yRange, int zRange)
	{
		super(worldIn, origin, xRange, yRange, zRange);
		SaxonSnowComponent0.init(world, origin, this);
		SaxonSnowComponent1.init(world, origin, this);
		SaxonSnowComponent2.init(world, origin, this);
        this.fillWithBlocks(world, start, -65, -1, -67, 64, 42, 71, Blocks.AIR.getDefaultState());
	}

	@Override
	public void addEntitiesAndSpawn()
	{
	    SaxonStandingGuard standing_guard89 = (SaxonStandingGuard) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard89, "standing_guard");
	    this.spawnEntity(standing_guard89, world, -49, 3, 0, start);
	    SaxonPatrollingGuard patrolling_guard90 = (SaxonPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard90, "patrolling_guard");
	    this.spawnEntity(patrolling_guard90, world, -43, 0, -2, start);
	    SaxonPatrollingGuard patrolling_guard91 = (SaxonPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard91, "patrolling_guard");
	    this.spawnEntity(patrolling_guard91, world, -41, 0, -26, start);
	    CitizenEntity ferox_augur = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:ferox_augur")).create(world);
	    this.setItemsForEntity(ferox_augur, "citizen");
	    this.spawnEntity(ferox_augur, world, -29, 0, 30, start);
	    SaxonPatrollingGuard patrolling_guard93 = (SaxonPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard93, "patrolling_guard");
	    this.spawnEntity(patrolling_guard93, world, -28, 0, 15, start);
	    CitizenEntity egnatius_hispallus = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:egnatius_hispallus")).create(world);
	    this.setItemsForEntity(egnatius_hispallus, "citizen");
	    this.spawnEntity(egnatius_hispallus, world, -27, 0, 2, start);
	    MerchantEntity produce_vendor = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:produce_vendor")).create(world);
	    this.setItemsForEntity(produce_vendor, "merchant");
	    this.spawnEntity(produce_vendor, world, -27, 0, 4, start);
	    CounterEntity counter96 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter96, "counter");
	    this.spawnEntity(counter96, world, -27, 1, 3, start);
	    CitizenEntity krista_vibulanus = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:krista_vibulanus")).create(world);
	    this.setItemsForEntity(krista_vibulanus, "citizen");
	    this.spawnEntity(krista_vibulanus, world, -26, 0, 15, start);
	    SaxonPatrollingGuard patrolling_guard98 = (SaxonPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard98, "patrolling_guard");
	    this.spawnEntity(patrolling_guard98, world, -25, 0, -2, start);
	    SaxonPatrollingGuard patrolling_guard99 = (SaxonPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard99, "patrolling_guard");
	    this.spawnEntity(patrolling_guard99, world, -23, 0, -31, start);
	    CitizenEntity philotheus_blasio = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:philotheus_blasio")).create(world);
	    this.setItemsForEntity(philotheus_blasio, "citizen");
	    this.spawnEntity(philotheus_blasio, world, -23, 0, 35, start);
	    CitizenEntity pantera_arvina = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:pantera_arvina")).create(world);
	    this.setItemsForEntity(pantera_arvina, "citizen");
	    this.spawnEntity(pantera_arvina, world, -17, 0, -7, start);
	    CitizenEntity elianna_sura = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:elianna_sura")).create(world);
	    this.setItemsForEntity(elianna_sura, "citizen");
	    this.spawnEntity(elianna_sura, world, -17, 0, 2, start);
	    MerchantEntity fruit_vendor = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:fruit_vendor")).create(world);
	    this.setItemsForEntity(fruit_vendor, "merchant");
	    this.spawnEntity(fruit_vendor, world, -17, 0, 4, start);
	    CounterEntity counter104 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter104, "counter");
	    this.spawnEntity(counter104, world, -17, 1, 3, start);
	    SaxonPatrollingGuard patrolling_guard105 = (SaxonPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard105, "patrolling_guard");
	    this.spawnEntity(patrolling_guard105, world, -16, 0, 38, start);
	    MerchantEntity guildmaster = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:guildmaster")).create(world);
	    this.setItemsForEntity(guildmaster, "merchant");
	    this.spawnEntity(guildmaster, world, -15, 0, 27, start);
	    CounterEntity counter107 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter107, "counter");
	    this.spawnEntity(counter107, world, -15, 1, 26, start);
	    CreatureEntity horse108 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:horse")).create(world);
	    this.setItemsForEntity(horse108, "horse");
	    this.spawnEntity(horse108, world, -13, 0, -41, start);
	    CreatureEntity horse109 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:horse")).create(world);
	    this.setItemsForEntity(horse109, "horse");
	    this.spawnEntity(horse109, world, -13, 0, -36, start);
	    MerchantEntity farming_merchant = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:farming_merchant")).create(world);
	    this.setItemsForEntity(farming_merchant, "merchant");
	    this.spawnEntity(farming_merchant, world, -13, 0, -18, start);
	    MerchantEntity shop_keeper = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:shop_keeper")).create(world);
	    this.setItemsForEntity(shop_keeper, "merchant");
	    this.spawnEntity(shop_keeper, world, -12, 0, -23, start);
	    CounterEntity counter112 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter112, "counter");
	    this.spawnEntity(counter112, world, -12, 1, -24, start);
	    CounterEntity counter113 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter113, "counter");
	    this.spawnEntity(counter113, world, -12, 1, -18, start);
	    MerchantEntity mineshop_merchant = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:mineshop_merchant")).create(world);
	    this.setItemsForEntity(mineshop_merchant, "merchant");
	    this.spawnEntity(mineshop_merchant, world, -10, 0, -7, start);
	    CreatureEntity horse115 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:horse")).create(world);
	    this.setItemsForEntity(horse115, "horse");
	    this.spawnEntity(horse115, world, -9, 0, -41, start);
	    CreatureEntity horse116 = (CreatureEntity) Objects.requireNonNull(EntityParser.getEntityFromName("minecraft:horse")).create(world);
	    this.setItemsForEntity(horse116, "horse");
	    this.spawnEntity(horse116, world, -9, 0, -36, start);
	    CounterEntity counter117 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter117, "counter");
	    this.spawnEntity(counter117, world, -9, 1, -7, start);
	    MerchantEntity fletching_merchant = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:fletching_merchant")).create(world);
	    this.setItemsForEntity(fletching_merchant, "merchant");
	    this.spawnEntity(fletching_merchant, world, -8, 0, -29, start);
	    MerchantEntity butcher = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:butcher")).create(world);
	    this.setItemsForEntity(butcher, "merchant");
	    this.spawnEntity(butcher, world, -8, 0, 42, start);
	    CounterEntity counter120 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter120, "counter");
	    this.spawnEntity(counter120, world, -8, 1, -28, start);
	    CounterEntity counter121 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter121, "counter");
	    this.spawnEntity(counter121, world, -8, 1, 41, start);
	    CitizenEntity helier_potitus = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:helier_potitus")).create(world);
	    this.setItemsForEntity(helier_potitus, "citizen");
	    this.spawnEntity(helier_potitus, world, -7, 0, 2, start);
	    MerchantEntity decor_merchant = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:decor_merchant")).create(world);
	    this.setItemsForEntity(decor_merchant, "merchant");
	    this.spawnEntity(decor_merchant, world, -7, 0, 4, start);
	    CounterEntity counter124 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter124, "counter");
	    this.spawnEntity(counter124, world, -7, 1, 3, start);
	    MerchantEntity horse_merchant = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:horse_merchant")).create(world);
	    this.setItemsForEntity(horse_merchant, "merchant");
	    this.spawnEntity(horse_merchant, world, -4, 0, -40, start);
	    SaxonPatrollingGuard patrolling_guard126 = (SaxonPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard126, "patrolling_guard");
	    this.spawnEntity(patrolling_guard126, world, -3, 0, -29, start);
	    CitizenEntity lorina_vestalis = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:lorina_vestalis")).create(world);
	    this.setItemsForEntity(lorina_vestalis, "citizen");
	    this.spawnEntity(lorina_vestalis, world, -3, 0, -21, start);
	    CitizenEntity ianuarius_caecus = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:ianuarius_caecus")).create(world);
	    this.setItemsForEntity(ianuarius_caecus, "citizen");
	    this.spawnEntity(ianuarius_caecus, world, -3, 0, -19, start);
	    SaxonPatrollingGuard patrolling_guard129 = (SaxonPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard129, "patrolling_guard");
	    this.spawnEntity(patrolling_guard129, world, -3, 0, 38, start);
	    CounterEntity counter130 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter130, "counter");
	    this.spawnEntity(counter130, world, -3, 1, -40, start);
	    SaxonStandingGuard standing_guard131 = (SaxonStandingGuard) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard131, "standing_guard");
	    this.spawnEntity(standing_guard131, world, -2, 0, -54, start);
	    SaxonStandingGuard standing_guard132 = (SaxonStandingGuard) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard132, "standing_guard");
	    this.spawnEntity(standing_guard132, world, -2, 0, -44, start);
	    SaxonPatrollingGuard patrolling_guard133 = (SaxonPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard133, "patrolling_guard");
	    this.spawnEntity(patrolling_guard133, world, -2, 0, -2, start);
	    SaxonPatrollingGuard patrolling_guard134 = (SaxonPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard134, "patrolling_guard");
	    this.spawnEntity(patrolling_guard134, world, -2, 0, 13, start);
	    CitizenEntity cosmo_getha = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:cosmo_getha")).create(world);
	    this.setItemsForEntity(cosmo_getha, "citizen");
	    this.spawnEntity(cosmo_getha, world, -2, 0, 29, start);
	    SaxonStandingGuard standing_guard136 = (SaxonStandingGuard) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard136, "standing_guard");
	    this.spawnEntity(standing_guard136, world, -2, 0, 47, start);
	    SaxonStandingGuard standing_guard137 = (SaxonStandingGuard) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard137, "standing_guard");
	    this.spawnEntity(standing_guard137, world, -2, 0, 57, start);
	    SaxonPatrollingGuard patrolling_guard138 = (SaxonPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard138, "patrolling_guard");
	    this.spawnEntity(patrolling_guard138, world, -1, 0, 36, start);
	    SaxonStandingGuard standing_guard139 = (SaxonStandingGuard) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard139, "standing_guard");
	    this.spawnEntity(standing_guard139, world, 2, 0, -54, start);
	    SaxonStandingGuard standing_guard140 = (SaxonStandingGuard) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard140, "standing_guard");
	    this.spawnEntity(standing_guard140, world, 2, 0, -44, start);
	    SaxonStandingGuard standing_guard141 = (SaxonStandingGuard) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard141, "standing_guard");
	    this.spawnEntity(standing_guard141, world, 2, 0, 47, start);
	    SaxonStandingGuard standing_guard142 = (SaxonStandingGuard) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard142, "standing_guard");
	    this.spawnEntity(standing_guard142, world, 2, 0, 57, start);
	    CitizenEntity naevius_salinator = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:naevius_salinator")).create(world);
	    this.setItemsForEntity(naevius_salinator, "citizen");
	    this.spawnEntity(naevius_salinator, world, 3, 0, 18, start);
	    CitizenEntity adelia_messala = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:adelia_messala")).create(world);
	    this.setItemsForEntity(adelia_messala, "citizen");
	    this.spawnEntity(adelia_messala, world, 4, 0, 17, start);
	    MerchantEntity blacksmith = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:blacksmith")).create(world);
	    this.setItemsForEntity(blacksmith, "merchant");
	    this.spawnEntity(blacksmith, world, 8, 0, -3, start);
	    MerchantEntity craftsman = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:craftsman")).create(world);
	    this.setItemsForEntity(craftsman, "merchant");
	    this.spawnEntity(craftsman, world, 8, 0, 28, start);
	    CounterEntity counter147 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter147, "counter");
	    this.spawnEntity(counter147, world, 8, 1, -26, start);
	    CounterEntity counter148 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter148, "counter");
	    this.spawnEntity(counter148, world, 8, 1, -2, start);
	    CounterEntity counter149 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter149, "counter");
	    this.spawnEntity(counter149, world, 8, 1, 29, start);
	    CounterEntity counter150 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter150, "counter");
	    this.spawnEntity(counter150, world, 8, 1, 41, start);
	    MerchantEntity baker = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:baker")).create(world);
	    this.setItemsForEntity(baker, "merchant");
	    this.spawnEntity(baker, world, 9, 0, -26, start);
	    MerchantEntity redstone_merchant = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:redstone_merchant")).create(world);
	    this.setItemsForEntity(redstone_merchant, "merchant");
	    this.spawnEntity(redstone_merchant, world, 9, 0, 41, start);
	    SaxonPatrollingGuard patrolling_guard153 = (SaxonPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard153, "patrolling_guard");
	    this.spawnEntity(patrolling_guard153, world, 11, 0, 2, start);
	    CitizenEntity cyra_ambustus = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:cyra_ambustus")).create(world);
	    this.setItemsForEntity(cyra_ambustus, "citizen");
	    this.spawnEntity(cyra_ambustus, world, 13, 0, 12, start);
	    CitizenEntity didymus_acisculus = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:didymus_acisculus")).create(world);
	    this.setItemsForEntity(didymus_acisculus, "citizen");
	    this.spawnEntity(didymus_acisculus, world, 16, 0, 16, start);
	    SaxonPatrollingGuard patrolling_guard156 = (SaxonPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard156, "patrolling_guard");
	    this.spawnEntity(patrolling_guard156, world, 17, 0, 41, start);
	    CitizenEntity seraphinus_asellus = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:seraphinus_asellus")).create(world);
	    this.setItemsForEntity(seraphinus_asellus, "citizen");
	    this.spawnEntity(seraphinus_asellus, world, 18, 0, 12, start);
	    SaxonPatrollingGuard patrolling_guard158 = (SaxonPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard158, "patrolling_guard");
	    this.spawnEntity(patrolling_guard158, world, 19, 0, -18, start);
	    SaxonPatrollingGuard patrolling_guard159 = (SaxonPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard159, "patrolling_guard");
	    this.spawnEntity(patrolling_guard159, world, 20, 0, -34, start);
	    CitizenEntity aurelia_procillus = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:aurelia_procillus")).create(world);
	    this.setItemsForEntity(aurelia_procillus, "citizen");
	    this.spawnEntity(aurelia_procillus, world, 23, 0, -32, start);
	    CitizenEntity oenone_merula = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:oenone_merula")).create(world);
	    this.setItemsForEntity(oenone_merula, "citizen");
	    this.spawnEntity(oenone_merula, world, 23, 0, -24, start);
	    MerchantEntity alchemist = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:alchemist")).create(world);
	    this.setItemsForEntity(alchemist, "merchant");
	    this.spawnEntity(alchemist, world, 23, 0, -4, start);
	    CounterEntity counter163 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter163, "counter");
	    this.spawnEntity(counter163, world, 23, 1, -3, start);
	    CitizenEntity caecus_caudex = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:caecus_caudex")).create(world);
	    this.setItemsForEntity(caecus_caudex, "citizen");
	    this.spawnEntity(caecus_caudex, world, 24, 0, 14, start);
	    CitizenEntity joanna_cinna = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:joanna_cinna")).create(world);
	    this.setItemsForEntity(joanna_cinna, "citizen");
	    this.spawnEntity(joanna_cinna, world, 25, 0, 3, start);
	    MerchantEntity inn_keeper = (MerchantEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:inn_keeper")).create(world);
	    this.setItemsForEntity(inn_keeper, "merchant");
	    this.spawnEntity(inn_keeper, world, 25, 0, 12, start);
	    CounterEntity counter167 = (CounterEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:counter")).create(world);
	    this.setItemsForEntity(counter167, "counter");
	    this.spawnEntity(counter167, world, 25, 1, 13, start);
	    CitizenEntity sera_albus = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:sera_albus")).create(world);
	    this.setItemsForEntity(sera_albus, "citizen");
	    this.spawnEntity(sera_albus, world, 26, 0, 14, start);
	    CitizenEntity quique_unimanus = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:quique_unimanus")).create(world);
	    this.setItemsForEntity(quique_unimanus, "citizen");
	    this.spawnEntity(quique_unimanus, world, 27, 0, 3, start);
	    SaxonPatrollingGuard patrolling_guard170 = (SaxonPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard170, "patrolling_guard");
	    this.spawnEntity(patrolling_guard170, world, 28, 0, 39, start);
	    CitizenEntity hester_geta = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:hester_geta")).create(world);
	    this.setItemsForEntity(hester_geta, "citizen");
	    this.spawnEntity(hester_geta, world, 32, 0, -26, start);
	    CitizenEntity athanasius_glaber = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:athanasius_glaber")).create(world);
	    this.setItemsForEntity(athanasius_glaber, "citizen");
	    this.spawnEntity(athanasius_glaber, world, 34, 0, 31, start);
	    SaxonPatrollingGuard patrolling_guard173 = (SaxonPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard173, "patrolling_guard");
	    this.spawnEntity(patrolling_guard173, world, 37, 0, 2, start);
	    CitizenEntity rufus_calussa = (CitizenEntity) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:rufus_calussa")).create(world);
	    this.setItemsForEntity(rufus_calussa, "citizen");
	    this.spawnEntity(rufus_calussa, world, 39, 0, 6, start);
	    SaxonPatrollingGuard patrolling_guard175 = (SaxonPatrollingGuard ) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_patrolling_guard")).create(world);
	    this.setItemsForEntity(patrolling_guard175, "patrolling_guard");
	    this.spawnEntity(patrolling_guard175, world, 39, 0, 21, start);
	    SaxonStandingGuard standing_guard176 = (SaxonStandingGuard) Objects.requireNonNull(EntityParser.getEntityFromName("odysseymod:saxon_standing_guard")).create(world);
	    this.setItemsForEntity(standing_guard176, "standing_guard");
	    this.spawnEntity(standing_guard176, world, 49, 3, 0, start);
	    this.executeCommand(world);
	    if(TownStructures.teleportSaxonSnow()) this.transportPlayertoTown(TownStructures.SAXON_SNOW.get(), "Teleported player to Saxon Town.", 7, 6);
	}
	
}
